#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

SERVICE="${1:-${SERVICE_NAME:-}}"
if [[ -z "${SERVICE}" ]]; then
  echo "Usage: $0 <service_short_name>"
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

export ONLY_TEST_APIGROUPS="${SERVICE}.cnrm.cloud.google.com"

extra_services="${SERVICE}.googleapis.com"
case "${SERVICE}" in
  "analytics") extra_services="analyticsadmin.googleapis.com" ;;
  "bigqueryanalyticshub") extra_services="analyticshub.googleapis.com" ;;
  "bigquerybiglake") extra_services="biglake.googleapis.com" ;;
  "certificatemanager") extra_services="certificatemanager.googleapis.com servicedirectory.googleapis.com privateca.googleapis.com" ;;
  "clouddms") extra_services="datamigration.googleapis.com" ;;
  "cloudfunctions2") extra_services="cloudfunctions.googleapis.com" ;;
  "cloudids") extra_services="ids.googleapis.com" ;;
  "containerattached") extra_services="gkemulticloud.googleapis.com" ;;
  "dialogflowcx") extra_services="dialogflow.googleapis.com" ;;
  "filestore") extra_services="file.googleapis.com" ;;
  "kms") extra_services="cloudkms.googleapis.com" ;;
  "mlengine") extra_services="ml.googleapis.com" ;;
  "resourcemanager") extra_services="cloudresourcemanager.googleapis.com" ;;
  "sql") extra_services="sqladmin.googleapis.com" ;;
  "tags") extra_services="cloudresourcemanager.googleapis.com" ;;
esac

export EXTRA_GCP_SERVICES="${extra_services}"

dev/ci/periodics/_create_project_and_run_e2e
