//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	k8sv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assignment) DeepCopyInto(out *Assignment) {
	*out = *in
	if in.Assignee != nil {
		in, out := &in.Assignee, &out.Assignee
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assignment.
func (in *Assignment) DeepCopy() *Assignment {
	if in == nil {
		return nil
	}
	out := new(Assignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentIdentity) DeepCopyInto(out *AssignmentIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(BQReservation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentIdentity.
func (in *AssignmentIdentity) DeepCopy() *AssignmentIdentity {
	if in == nil {
		return nil
	}
	out := new(AssignmentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentObservedState) DeepCopyInto(out *AssignmentObservedState) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentObservedState.
func (in *AssignmentObservedState) DeepCopy() *AssignmentObservedState {
	if in == nil {
		return nil
	}
	out := new(AssignmentObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentRef) DeepCopyInto(out *AssignmentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentRef.
func (in *AssignmentRef) DeepCopy() *AssignmentRef {
	if in == nil {
		return nil
	}
	out := new(AssignmentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleObservedState) DeepCopyInto(out *AutoscaleObservedState) {
	*out = *in
	if in.CurrentSlots != nil {
		in, out := &in.CurrentSlots, &out.CurrentSlots
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleObservedState.
func (in *AutoscaleObservedState) DeepCopy() *AutoscaleObservedState {
	if in == nil {
		return nil
	}
	out := new(AutoscaleObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleSpec) DeepCopyInto(out *AutoscaleSpec) {
	*out = *in
	if in.MaxSlots != nil {
		in, out := &in.MaxSlots, &out.MaxSlots
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleSpec.
func (in *AutoscaleSpec) DeepCopy() *AutoscaleSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BQReservation) DeepCopyInto(out *BQReservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BQReservation.
func (in *BQReservation) DeepCopy() *BQReservation {
	if in == nil {
		return nil
	}
	out := new(BQReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationAssignment) DeepCopyInto(out *BigQueryReservationAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationAssignment.
func (in *BigQueryReservationAssignment) DeepCopy() *BigQueryReservationAssignment {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigQueryReservationAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationAssignmentList) DeepCopyInto(out *BigQueryReservationAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BigQueryReservationAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationAssignmentList.
func (in *BigQueryReservationAssignmentList) DeepCopy() *BigQueryReservationAssignmentList {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigQueryReservationAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationAssignmentObservedState) DeepCopyInto(out *BigQueryReservationAssignmentObservedState) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationAssignmentObservedState.
func (in *BigQueryReservationAssignmentObservedState) DeepCopy() *BigQueryReservationAssignmentObservedState {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationAssignmentObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationAssignmentSpec) DeepCopyInto(out *BigQueryReservationAssignmentSpec) {
	*out = *in
	if in.ReservationRef != nil {
		in, out := &in.ReservationRef, &out.ReservationRef
		*out = new(ReservationRef)
		**out = **in
	}
	if in.Assignee != nil {
		in, out := &in.Assignee, &out.Assignee
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationAssignmentSpec.
func (in *BigQueryReservationAssignmentSpec) DeepCopy() *BigQueryReservationAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationAssignmentStatus) DeepCopyInto(out *BigQueryReservationAssignmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(BigQueryReservationAssignmentObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationAssignmentStatus.
func (in *BigQueryReservationAssignmentStatus) DeepCopy() *BigQueryReservationAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationReservation) DeepCopyInto(out *BigQueryReservationReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationReservation.
func (in *BigQueryReservationReservation) DeepCopy() *BigQueryReservationReservation {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigQueryReservationReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationReservationList) DeepCopyInto(out *BigQueryReservationReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BigQueryReservationReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationReservationList.
func (in *BigQueryReservationReservationList) DeepCopy() *BigQueryReservationReservationList {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BigQueryReservationReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationReservationObservedState) DeepCopyInto(out *BigQueryReservationReservationObservedState) {
	*out = *in
	if in.FailOver != nil {
		in, out := &in.FailOver, &out.FailOver
		*out = new(FailoverObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(AutoscaleObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationReservationObservedState.
func (in *BigQueryReservationReservationObservedState) DeepCopy() *BigQueryReservationReservationObservedState {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationReservationObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationReservationSpec) DeepCopyInto(out *BigQueryReservationReservationSpec) {
	*out = *in
	in.Parent.DeepCopyInto(&out.Parent)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.SlotCapacity != nil {
		in, out := &in.SlotCapacity, &out.SlotCapacity
		*out = new(int64)
		**out = **in
	}
	if in.IgnoreIdleSlots != nil {
		in, out := &in.IgnoreIdleSlots, &out.IgnoreIdleSlots
		*out = new(bool)
		**out = **in
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(AutoscaleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int64)
		**out = **in
	}
	if in.Edition != nil {
		in, out := &in.Edition, &out.Edition
		*out = new(string)
		**out = **in
	}
	if in.FailOver != nil {
		in, out := &in.FailOver, &out.FailOver
		*out = new(FailoverSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationReservationSpec.
func (in *BigQueryReservationReservationSpec) DeepCopy() *BigQueryReservationReservationSpec {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryReservationReservationStatus) DeepCopyInto(out *BigQueryReservationReservationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(BigQueryReservationReservationObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryReservationReservationStatus.
func (in *BigQueryReservationReservationStatus) DeepCopy() *BigQueryReservationReservationStatus {
	if in == nil {
		return nil
	}
	out := new(BigQueryReservationReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverObservedState) DeepCopyInto(out *FailoverObservedState) {
	*out = *in
	if in.PrimaryLocation != nil {
		in, out := &in.PrimaryLocation, &out.PrimaryLocation
		*out = new(string)
		**out = **in
	}
	if in.SecondaryLocation != nil {
		in, out := &in.SecondaryLocation, &out.SecondaryLocation
		*out = new(string)
		**out = **in
	}
	if in.OriginalPrimaryLocation != nil {
		in, out := &in.OriginalPrimaryLocation, &out.OriginalPrimaryLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverObservedState.
func (in *FailoverObservedState) DeepCopy() *FailoverObservedState {
	if in == nil {
		return nil
	}
	out := new(FailoverObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
	if in.SecondaryLocation != nil {
		in, out := &in.SecondaryLocation, &out.SecondaryLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverSpec.
func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parent) DeepCopyInto(out *Parent) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parent.
func (in *Parent) DeepCopy() *Parent {
	if in == nil {
		return nil
	}
	out := new(Parent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SlotCapacity != nil {
		in, out := &in.SlotCapacity, &out.SlotCapacity
		*out = new(int64)
		**out = **in
	}
	if in.IgnoreIdleSlots != nil {
		in, out := &in.IgnoreIdleSlots, &out.IgnoreIdleSlots
		*out = new(bool)
		**out = **in
	}
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(Reservation_Autoscale)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int64)
		**out = **in
	}
	if in.MultiRegionAuxiliary != nil {
		in, out := &in.MultiRegionAuxiliary, &out.MultiRegionAuxiliary
		*out = new(bool)
		**out = **in
	}
	if in.Edition != nil {
		in, out := &in.Edition, &out.Edition
		*out = new(string)
		**out = **in
	}
	if in.PrimaryLocation != nil {
		in, out := &in.PrimaryLocation, &out.PrimaryLocation
		*out = new(string)
		**out = **in
	}
	if in.SecondaryLocation != nil {
		in, out := &in.SecondaryLocation, &out.SecondaryLocation
		*out = new(string)
		**out = **in
	}
	if in.OriginalPrimaryLocation != nil {
		in, out := &in.OriginalPrimaryLocation, &out.OriginalPrimaryLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationIdentity) DeepCopyInto(out *ReservationIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(ReservationParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationIdentity.
func (in *ReservationIdentity) DeepCopy() *ReservationIdentity {
	if in == nil {
		return nil
	}
	out := new(ReservationIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationObservedState) DeepCopyInto(out *ReservationObservedState) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(Reservation_AutoscaleObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationObservedState.
func (in *ReservationObservedState) DeepCopy() *ReservationObservedState {
	if in == nil {
		return nil
	}
	out := new(ReservationObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationParent) DeepCopyInto(out *ReservationParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationParent.
func (in *ReservationParent) DeepCopy() *ReservationParent {
	if in == nil {
		return nil
	}
	out := new(ReservationParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationRef) DeepCopyInto(out *ReservationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationRef.
func (in *ReservationRef) DeepCopy() *ReservationRef {
	if in == nil {
		return nil
	}
	out := new(ReservationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation_Autoscale) DeepCopyInto(out *Reservation_Autoscale) {
	*out = *in
	if in.MaxSlots != nil {
		in, out := &in.MaxSlots, &out.MaxSlots
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation_Autoscale.
func (in *Reservation_Autoscale) DeepCopy() *Reservation_Autoscale {
	if in == nil {
		return nil
	}
	out := new(Reservation_Autoscale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation_AutoscaleObservedState) DeepCopyInto(out *Reservation_AutoscaleObservedState) {
	*out = *in
	if in.CurrentSlots != nil {
		in, out := &in.CurrentSlots, &out.CurrentSlots
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation_AutoscaleObservedState.
func (in *Reservation_AutoscaleObservedState) DeepCopy() *Reservation_AutoscaleObservedState {
	if in == nil {
		return nil
	}
	out := new(Reservation_AutoscaleObservedState)
	in.DeepCopyInto(out)
	return out
}
