apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: discoveryenginesessions.discoveryengine.cnrm.cloud.google.com
spec:
  group: discoveryengine.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: DiscoveryEngineSession
    listKind: DiscoveryEngineSessionList
    plural: discoveryenginesessions
    shortNames:
    - gcpdiscoveryenginesession
    - gcpdiscoveryenginesessions
    singular: discoveryenginesession
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DiscoveryEngineSession is the Schema for the DiscoveryEngineSession
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DiscoveryEngineSessionSpec defines the desired state of DiscoveryEngineSession
            properties:
              displayName:
                description: |-
                  Optional. The display name of the session.

                   This field is used to identify the session in the UI.
                   By default, the display name is the first turn query text in the session.
                type: string
              isPinned:
                description: Optional. Whether the session is pinned, pinned session
                  will be displayed on the top of the session list.
                type: boolean
              labels:
                description: Optional. The labels for the session. Can be set as filter
                  in ListSessionsRequest.
                items:
                  type: string
                type: array
              location:
                description: The location of this resource.
                type: string
              projectRef:
                description: The project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              resourceID:
                description: The DiscoveryEngineSession name. If not given, the metadata.name
                  will be used.
                type: string
              state:
                description: The state of the session.
                type: string
              turns:
                description: Turns.
                items:
                  properties:
                    answer:
                      description: |-
                        Optional. The resource name of the answer to the user query.

                         Only set if the answer generation (/answer API call) happened in this
                         turn.
                      type: string
                    query:
                      description: Optional. The user query. May not be set if this
                        turn is merely regenerating an answer to a different turn
                      properties:
                        text:
                          description: Plain text.
                          type: string
                      type: object
                    queryConfig:
                      additionalProperties:
                        type: string
                      description: Optional. Represents metadata related to the query
                        config, for example LLM model and version used, model parameters
                        (temperature, grounding parameters, etc.). The prefix "google."
                        is reserved for Google-developed functionality.
                      type: object
                  type: object
                type: array
              userPseudoID:
                description: A unique identifier for tracking users.
                type: string
            required:
            - location
            type: object
          status:
            description: DiscoveryEngineSessionStatus defines the config connector
              machine state of DiscoveryEngineSession
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the DiscoveryEngineSession resource
                  in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  endTime:
                    description: Output only. The time the session finished.
                    type: string
                  startTime:
                    description: Output only. The time the session started.
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
