// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.

// +generated:identity
// krm.group: vmwareengine.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.message: google.cloud.vmwareengine.v1.ManagementDnsZoneBinding

package v1alpha1

import (
	"testing"

	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/common/identity"
)

func TestVMwareEngineManagementDNSZoneBindingIdentity_Conformance(t *testing.T) {
	identity.AssertConformance(t, identity.ConformanceCase[VMwareEngineManagementDNSZoneBindingIdentity]{
		SampleExternal: "projects/my-project/locations/us-central1/privateClouds/my-private-cloud/managementDnsZoneBindings/my-management-dns-zone-binding",
		WantHost:       "vmwareengine.googleapis.com",
		WantParent:     "projects/my-project/locations/us-central1/privateClouds/my-private-cloud",
		WantIdentity: &VMwareEngineManagementDNSZoneBindingIdentity{
			Project:                  "my-project",
			Location:                 "us-central1",
			PrivateCloud:             "my-private-cloud",
			ManagementDnsZoneBinding: "my-management-dns-zone-binding",
		},
		Ref: &VMwareEngineManagementDNSZoneBindingRef{},
	})
}
