#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Force the image names, to avoid depending on the current gcloud project
export SHORT_SHA=$(git rev-parse --short=7 HEAD)
export BUILDER_IMG=builder:${SHORT_SHA}
export CONTROLLER_IMG=controller:${SHORT_SHA}
export RECORDER_IMG=recorder:${SHORT_SHA}
export WEBHOOK_IMG=webhook:${SHORT_SHA}
export DELETION_DEFENDER_IMG=deletiondefender:${SHORT_SHA}
export UNMANAGED_DETECTOR_IMG=unmanageddetector:${SHORT_SHA}

export OPERATOR_IMG=cnrm/operator:${SHORT_SHA}

cd ${REPO_ROOT}
make docker-build

cd ${REPO_ROOT}/operator
make docker-build