#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

echo "===> [$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Compiling Go binaries natively on host..."
mkdir -p bin/ THIRD_PARTY_NOTICES/ MIRRORED_LIBRARY_SOURCE/

export CGO_ENABLED=0
export GOOS=linux
export GOARCH=amd64

LDFLAGS="-s -w -buildid="

BUILD_CLI="${BUILD_CLI:-1}"
SKIP_LICENSES="${SKIP_LICENSES:-0}"

targets=(
  ./cmd/deletiondefender
  ./cmd/webhook
  ./cmd/recorder
  ./cmd/unmanageddetector
  ./cmd/manager
)

if [[ "${BUILD_CLI}" != "0" ]]; then
  targets+=(./cmd/config-connector)
else
  touch bin/config-connector
fi

# Unified single go build invocation to share the apis/ and pkg/ compilation graph
go build -trimpath -p 6 -ldflags "${LDFLAGS}" -o bin/ "${targets[@]}"
go build -trimpath -p 6 -ldflags "${LDFLAGS}" -o bin/operator ./operator/cmd/manager
go build -trimpath -p 6 -ldflags "${LDFLAGS}" -o bin/gke_addon_poststart ./operator/cmd/gke_addon_poststart

if [[ "${SKIP_LICENSES}" == "0" ]]; then
  echo "===> [$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Generating third-party notices..."
  GOWORK=off go mod vendor -o temp-vendor
  go run scripts/generate-third-party-licenses/main.go
  rm -rf temp-vendor
else
  echo "===> [$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Skipping third-party notices (SKIP_LICENSES=1)"
  mkdir -p THIRD_PARTY_NOTICES MIRRORED_LIBRARY_SOURCE
  touch THIRD_PARTY_NOTICES/.placeholder MIRRORED_LIBRARY_SOURCE/.placeholder
fi

echo "===> [$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Generating operator channels..."
dev/tasks/generate-channels

echo "===> [$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Native host compilation complete."
