#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

go test -v ./pkg/fuzztesting/fuzztests/ -fuzz=FuzzAllMappers -fuzztime 600s # fuzz for 10 minutes because we are fuzzing all the registered mappers

go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceAttachmentObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/  -fuzz=FuzzEnvgroupAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/  -fuzz=FuzzEnvgroupAttachmentObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/compute/firewallpolicyrule -fuzz=FuzzComputeFirewallPolicyRuleSpec -fuzztime 60s
go test -v ./pkg/controller/direct/compute/forwardingrule -fuzz=FuzzComputeForwardingRuleSpec -fuzztime 60s
go test -v ./pkg/controller/direct/compute/targettcpproxy -fuzz=FuzzComputeTargetTCPProxySpec -fuzztime 60s

go test -v ./pkg/controller/direct/discoveryengine/ -fuzz=FuzzDiscoveryEngineChatEngineSpec -fuzztime 60s
go test -v ./pkg/controller/direct/discoveryengine/ -fuzz=FuzzDiscoveryEngineChatEngineObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/networkconnectivity/ -fuzz=FuzzServiceConnectionPolicySpec -fuzztime 60s
go test -v ./pkg/controller/direct/networkconnectivity/ -fuzz=FuzzServiceConnectionPolicyObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/dataflow/ -fuzz=FuzzDataflowFlexTemplateJobSpec -fuzztime 60s

go test -v ./pkg/controller/direct/redis/cluster/ -fuzz=FuzzRedisClusterSpec -fuzztime 60s
go test -v ./pkg/controller/direct/redis/cluster/ -fuzz=FuzzRedisClusterObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/monitoring/ -fuzz=FuzzMonitoringDashboardSpec -fuzztime 60s
go test -v ./pkg/controller/direct/securesourcemanager/ -fuzz=FuzzSecureSourceManagerInstanceSpec -fuzztime 60s
go test -v ./pkg/controller/direct/securesourcemanager/ -fuzz=FuzzSecureSourceManagerInstanceObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/securesourcemanager/ -fuzz=FuzzSecureSourceManagerRepositorySpec -fuzztime 60s
go test -v ./pkg/controller/direct/securesourcemanager/ -fuzz=FuzzSecureSourceManagerRepositoryObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/dataform/ -fuzz=FuzzDataformRepositorySpec -fuzztime 60s

go test -v ./pkg/controller/direct/bigquerydatatransfer/ -fuzz=FuzzBigQueryDataTransferConfigSpec -fuzztime 60s

go test -v ./pkg/controller/direct/certificatemanager/ -fuzz=FuzzDNSAuthorizationSpec -fuzztime 60s