#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

set -x

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}


for group in $(rgrep --no-filename '^[ ]*group:' config/crds | sort | uniq | awk '{print $2}'); do
  if [[ "${group}" == "" ]]; then
    continue
  fi
  
  short=$(echo ${group} | sed s@.cnrm.cloud.google.com@@g)
  

cat > ${REPO_ROOT}/dev/ci/periodics/e2e-service-${short} <<EOF
#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="\$(git rev-parse --show-toplevel)"
cd "\${REPO_ROOT}"

export ONLY_TEST_APIGROUPS=${group}

dev/ci/periodics/_create_project_and_run_e2e
EOF

  chmod +x ${REPO_ROOT}/dev/ci/periodics/e2e-service-${short}
done
