#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Update the manifests etc in the repository to reflect a new tagged release.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

BUILD_DIR="${REPO_ROOT}/.build"
mkdir -p "${BUILD_DIR}"

WORKDIR="${BUILD_DIR}/workdir"
rm -rf "${WORKDIR}"
mkdir -p "${WORKDIR}"


BIN_DIR="${BUILD_DIR}/bin"
mkdir -p "${BIN_DIR}"

GOBIN=${BIN_DIR}/ go install sigs.k8s.io/kustomize/kustomize/v5@v5.3.0
export PATH=${BIN_DIR}/:$PATH

if [[ -z "${VERSION:-}" ]]; then
  echo "VERSION must be set"
  exit 1
fi

# Update our version marker file (used for user agent etc)
cat <<EOF > version/VERSION
${VERSION}
EOF

# Update the version label in our kustomization files
sed -i -e "s@cnrm.cloud.google.com/operator-version:.*@cnrm.cloud.google.com/operator-version: \"${VERSION}\"@g" \
  operator/config/autopilot/kustomization.yaml \
  operator/config/default/kustomization.yaml \
  config/installbundle/release-manifests/standard/kustomization.yaml \
  config/installbundle/release-manifests/autopilot/kustomization.yaml

# Update the default version in the "default" operator channel
cat <<EOF > operator/channels/stable
manifests:
 - version: ${VERSION}
EOF

# Update the default version in the "autopilot" operator channel
cat <<EOF > operator/autopilot-channels/stable
manifests:
 - version: ${VERSION}
EOF


# Build the release bundle and generate manifests
dev/tasks/generate-channels

# Update operator RBAC.  
cp ${REPO_ROOT}/config/installbundle/components/clusterroles/cnrm_viewer.yaml ${REPO_ROOT}/operator/config/rbac/cnrm_viewer_patch.yaml


# Generate operator/config/gke-addon/image_configmap.yaml
make -C ${REPO_ROOT}/operator manifests

# find the STALE_VERSION
folder_path="${REPO_ROOT}/operator/channels/packages/configconnector"
if [ ! -d "$folder_path" ]; then
    echo "Error: Directory $folder_path does not exist"
    exit 1
fi

# List all directories in the specified path and store them in an array
versions=($(ls -d "$folder_path"/*/ 2>/dev/null | xargs -n 1 basename))

if [ ${#versions[@]} -eq 0 ]; then
    echo "Error: No version directories found in $folder_path"
    exit 1
fi

echo "Found versions:"
printf '%s\n' "${versions[@]}"

if [[ -n "${STALE_VERSION:-}" ]]; then
  echo "stale version: ${STALE_VERSION}"

  # Remove the STALE_VERSION package for standard and autopilot
  rm -rf ${REPO_ROOT}/operator/autopilot-channels/packages/configconnector/${STALE_VERSION}/cluster
  rm -f ${REPO_ROOT}/operator/autopilot-channels/packages/configconnector/${STALE_VERSION}/crds.yaml
  rm -f ${REPO_ROOT}/operator/autopilot-channels/packages/configconnector/${STALE_VERSION}/namespaced/0-cnrm-system.yaml
  rm -rf ${REPO_ROOT}/operator/channels/packages/configconnector/${STALE_VERSION}/cluster
  rm -f ${REPO_ROOT}/operator/channels/packages/configconnector/${STALE_VERSION}/crds.yaml
  rm -f ${REPO_ROOT}/operator/channels/packages/configconnector/${STALE_VERSION}/namespaced/0-cnrm-system.yaml
fi

# Format
cd ${REPO_ROOT}; make fmt
