#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Update the manifests etc in the repository to reflect a new tagged release.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd ${REPO_ROOT}

BUILD_DIR="${REPO_ROOT}/.build"
mkdir -p "${BUILD_DIR}"

WORKDIR="${BUILD_DIR}/workdir"
rm -rf "${WORKDIR}"
mkdir -p "${WORKDIR}"


BIN_DIR="${BUILD_DIR}/bin"
mkdir -p "${BIN_DIR}"

GOBIN=${BIN_DIR}/ go install sigs.k8s.io/kustomize/kustomize/v5@v5.3.0
export PATH=${BIN_DIR}/:$PATH

if [[ -z "${VERSION:-}" ]]; then
  echo "VERSION must be set"
  exit 1
fi

# Update our version marker file (used for user agent etc)
cat <<EOF > version/VERSION
${VERSION}
EOF

# Update the version label in our kustomization files
sed -i -e "s@cnrm.cloud.google.com/operator-version:.*@cnrm.cloud.google.com/operator-version: \"${VERSION}\"@g" \
  operator/config/autopilot/kustomization.yaml \
  operator/config/default/kustomization.yaml \
  config/installbundle/release-manifests/standard/kustomization.yaml \
  config/installbundle/release-manifests/autopilot/kustomization.yaml

# Update the default version in the "default" operator channel
cat <<EOF > operator/channels/stable
manifests:
 - version: ${VERSION}
EOF

# Update the default version in the "autopilot" operator channel
cat <<EOF > operator/autopilot-channels/stable
manifests:
 - version: ${VERSION}
EOF


# Build the release bundle and generate manifests
dev/tasks/generate-channels

# Update operator RBAC.  
cp ${REPO_ROOT}/config/installbundle/components/clusterroles/cnrm_viewer.yaml ${REPO_ROOT}/operator/config/rbac/cnrm_viewer_patch.yaml


# Generate operator/config/gke-addon/image_configmap.yaml
make -C ${REPO_ROOT}/operator manifests

# Format
GOFLAGS= go run github.com/google/addlicense@04bfe4ee9ca5764577b029acc6a1957fd1997153 -c "Google LLC" -l apache ${REPO_ROOT}/operator/autopilot-channels/packages/configconnector
GOFLAGS= go run github.com/google/addlicense@04bfe4ee9ca5764577b029acc6a1957fd1997153 -c "Google LLC" -l apache ${REPO_ROOT}/operator/channels/packages/configconnector
cd ${REPO_ROOT}; make fmt
