#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

COMPARISON_REF="origin/master"
if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
  COMPARISON_REF="origin/${GITHUB_BASE_REF}"
fi

CHANGED_FILES=$(git diff --name-only ${COMPARISON_REF}...HEAD || git diff --name-only HEAD~1 || true)
echo "Changed files detected:"
echo "${CHANGED_FILES}"

services=()
for file in ${CHANGED_FILES}; do
  if [[ "${file}" == apis/* ]]; then
    dir="${file#apis/}"
    service="${dir%%/*}"
    services+=("${service}")
  elif [[ "${file}" == pkg/controller/direct/* ]]; then
    dir="${file#pkg/controller/direct/}"
    service="${dir%%/*}"
    services+=("${service}")
  elif [[ "${file}" == pkg/test/resourcefixture/testdata/basic/* ]]; then
    dir="${file#pkg/test/resourcefixture/testdata/basic/}"
    service="${dir%%/*}"
    services+=("${service}")
  elif [[ "${file}" == pkg/clients/generated/apis/* ]]; then
    dir="${file#pkg/clients/generated/apis/}"
    service="${dir%%/*}"
    services+=("${service}")
  fi
done

unique_services=($(echo "${services[@]:-}" | tr ' ' '\n' | sort -u | grep -v '^$' || true))

shard_service() {
  local service="$1"
  case "${service}" in
    compute)
      echo "compute-1-of-4"
      echo "compute-2-of-4"
      echo "compute-3-of-4"
      echo "compute-4-of-4"
      ;;
    sql)
      echo "sql-1-of-2"
      echo "sql-2-of-2"
      ;;
    container)
      echo "container-1-of-2"
      echo "container-2-of-2"
      ;;
    bigquery)
      echo "bigquery-1-of-2"
      echo "bigquery-2-of-2"
      ;;
    *)
      echo "${service}"
      ;;
  esac
}

all_fixture_services=()
for group in $(rgrep --no-filename '^[ ]*group:' config/crds | sort | uniq | awk '{print $2}'); do
  if [[ "${group}" != *.cnrm.cloud.google.com ]]; then
    continue
  fi
  short=$(echo ${group} | sed s@.cnrm.cloud.google.com@@g)
  if [[ "${short}" == "blockchainnodeengine" || "${short}" == "videostitcher" ]]; then
    continue
  fi
  all_fixture_services+=("${short}")
done
all_fixture_services+=("reconcileintervalannotations")
all_fixture_services+=("stateabsentinspec")

priority_fixture_targets=()
for service in "${unique_services[@]:-}"; do
  if [[ " ${all_fixture_services[*]:-} " =~ " ${service} " ]]; then
    for target in $(shard_service "${service}"); do
      priority_fixture_targets+=("${target}")
    done
  fi
done

remaining_fixture_targets=()
sharded_fixture_targets=()
standard_fixture_targets=()

for service in "${all_fixture_services[@]}"; do
  if [[ " ${unique_services[*]:-} " =~ " ${service} " ]]; then
    echo "Service ${service} marked for priority upfront verification."
  else
    if [[ "${service}" == "compute" || "${service}" == "sql" || "${service}" == "container" || "${service}" == "bigquery" ]]; then
      for target in $(shard_service "${service}"); do
        sharded_fixture_targets+=("${target}")
      done
    else
      for target in $(shard_service "${service}"); do
        standard_fixture_targets+=("${target}")
      done
    fi
  fi
done

remaining_fixture_targets=("${sharded_fixture_targets[@]:-}" "${standard_fixture_targets[@]:-}")

# Defined sample services supported by E2E samples suite
sample_services=("alloydb" "apigateway" "apigee" "bigquery" "bigqueryconnection" "bigquerydatapolicy" "bigquerydatatransfer" "cloudbuild" "cloudidentity" "compute" "dataflow" "dataproc" "gkehub" "iam" "kms" "orgpolicy" "redis" "secretmanager" "spanner" "sql" "storage" "unclassified" "workstations")

# Scenario suites supported by E2E scenarios suite
scenario_suites=("acquisition" "gkehubfeaturemembership" "powertool" "unclassified")

unit_tests_shards=("1-of-4" "2-of-4" "3-of-4" "4-of-4")
fuzz_roundtrippers_shards=("1-of-4" "2-of-4" "3-of-4" "4-of-4")

HAS_PRIORITY="false"
if [[ ${#priority_fixture_targets[@]} -gt 0 ]]; then
  HAS_PRIORITY="true"
  PRIORITY_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${priority_fixture_targets[@]}")
else
  # Pass a dummy element so fromJSON() evaluation in GHA doesn't error out on empty arrays when condition is false
  PRIORITY_JSON='["none"]'
fi

REMAINING_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${remaining_fixture_targets[@]}")
SAMPLES_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${sample_services[@]}")
SCENARIOS_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${scenario_suites[@]}")
UNIT_TESTS_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${unit_tests_shards[@]}")
FUZZ_ROUNDTRIPPERS_JSON=$(python3 -c 'import json, sys; print(json.dumps(sys.argv[1:]))' "${fuzz_roundtrippers_shards[@]}")

echo "has_priority_tests=${HAS_PRIORITY}"
echo "priority_fixtures_json=${PRIORITY_JSON}"
echo "remaining_fixtures_json=${REMAINING_JSON}"
echo "samples_json=${SAMPLES_JSON}"
echo "scenarios_json=${SCENARIOS_JSON}"
echo "unit_tests_json=${UNIT_TESTS_JSON}"
echo "fuzz_roundtrippers_json=${FUZZ_ROUNDTRIPPERS_JSON}"

if [[ -n "${GITHUB_OUTPUT:-}" && -f "${GITHUB_OUTPUT}" ]]; then
  echo "has_priority_tests=${HAS_PRIORITY}" >> "${GITHUB_OUTPUT}"
  echo "priority_fixtures_json=${PRIORITY_JSON}" >> "${GITHUB_OUTPUT}"
  echo "remaining_fixtures_json=${REMAINING_JSON}" >> "${GITHUB_OUTPUT}"
  echo "samples_json=${SAMPLES_JSON}" >> "${GITHUB_OUTPUT}"
  echo "scenarios_json=${SCENARIOS_JSON}" >> "${GITHUB_OUTPUT}"
  echo "unit_tests_json=${UNIT_TESTS_JSON}" >> "${GITHUB_OUTPUT}"
  echo "fuzz_roundtrippers_json=${FUZZ_ROUNDTRIPPERS_JSON}" >> "${GITHUB_OUTPUT}"
fi
