#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

dev/tasks/list-tests | xargs -I {} mkdir -p "testlogs/{}"

echo "Downloading envtest assets..."
export KUBEBUILDER_ASSETS=$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use -p path)

echo "Prebuilding e2e tests"
export PREBUILT_TEST_BINARY=${REPO_ROOT}/.build/tests-e2e
go test -c -o ${PREBUILT_TEST_BINARY} ./tests/e2e 

echo "Running tests"
EXIT_CODE=0
if [[ $(uname) == "Darwin" ]]; then
  (dev/tasks/list-tests | sort | uniq | xargs -P 40 -S 1024 -I {} /bin/bash -c "echo {}; RUN_TESTS={} dev/tasks/run-e2e > testlogs/{}/log 2>&1") || EXIT_CODE=$?
else
  (dev/tasks/list-tests | sort | uniq | xargs -P 40 -I {} /bin/bash -c "echo {}; RUN_TESTS={} dev/tasks/run-e2e > testlogs/{}/log 2>&1") || EXIT_CODE=$?
fi

if [[ ${EXIT_CODE} -ne 0 ]]; then
  echo "Some tests failed!"
  rgrep FAIL testlogs/
fi

exit ${EXIT_CODE}