//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/clients/generated/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateManagerDNSAuthorization) DeepCopyInto(out *CertificateManagerDNSAuthorization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateManagerDNSAuthorization.
func (in *CertificateManagerDNSAuthorization) DeepCopy() *CertificateManagerDNSAuthorization {
	if in == nil {
		return nil
	}
	out := new(CertificateManagerDNSAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateManagerDNSAuthorization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateManagerDNSAuthorizationList) DeepCopyInto(out *CertificateManagerDNSAuthorizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateManagerDNSAuthorization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateManagerDNSAuthorizationList.
func (in *CertificateManagerDNSAuthorizationList) DeepCopy() *CertificateManagerDNSAuthorizationList {
	if in == nil {
		return nil
	}
	out := new(CertificateManagerDNSAuthorizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateManagerDNSAuthorizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateManagerDNSAuthorizationSpec) DeepCopyInto(out *CertificateManagerDNSAuthorizationSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	out.ProjectRef = in.ProjectRef
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateManagerDNSAuthorizationSpec.
func (in *CertificateManagerDNSAuthorizationSpec) DeepCopy() *CertificateManagerDNSAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateManagerDNSAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateManagerDNSAuthorizationStatus) DeepCopyInto(out *CertificateManagerDNSAuthorizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.DNSResourceRecord != nil {
		in, out := &in.DNSResourceRecord, &out.DNSResourceRecord
		*out = make([]*DNSAuthorization_DNSResourceRecordObservedState, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DNSAuthorization_DNSResourceRecordObservedState)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateManagerDNSAuthorizationStatus.
func (in *CertificateManagerDNSAuthorizationStatus) DeepCopy() *CertificateManagerDNSAuthorizationStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateManagerDNSAuthorizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAuthorization_DNSResourceRecord) DeepCopyInto(out *DNSAuthorization_DNSResourceRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAuthorization_DNSResourceRecord.
func (in *DNSAuthorization_DNSResourceRecord) DeepCopy() *DNSAuthorization_DNSResourceRecord {
	if in == nil {
		return nil
	}
	out := new(DNSAuthorization_DNSResourceRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAuthorization_DNSResourceRecordObservedState) DeepCopyInto(out *DNSAuthorization_DNSResourceRecordObservedState) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAuthorization_DNSResourceRecordObservedState.
func (in *DNSAuthorization_DNSResourceRecordObservedState) DeepCopy() *DNSAuthorization_DNSResourceRecordObservedState {
	if in == nil {
		return nil
	}
	out := new(DNSAuthorization_DNSResourceRecordObservedState)
	in.DeepCopyInto(out)
	return out
}
