//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	billingv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/billing/v1alpha1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	k8sv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOffer) DeepCopyInto(out *CommerceProducerPrivateOffer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOffer.
func (in *CommerceProducerPrivateOffer) DeepCopy() *CommerceProducerPrivateOffer {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOffer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommerceProducerPrivateOffer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOfferList) DeepCopyInto(out *CommerceProducerPrivateOfferList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommerceProducerPrivateOffer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOfferList.
func (in *CommerceProducerPrivateOfferList) DeepCopy() *CommerceProducerPrivateOfferList {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOfferList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommerceProducerPrivateOfferList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOfferObservedState) DeepCopyInto(out *CommerceProducerPrivateOfferObservedState) {
	*out = *in
	if in.SingleProductOffer != nil {
		in, out := &in.SingleProductOffer, &out.SingleProductOffer
		*out = new(PrivateOffer_SingleProductOfferObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.PublishRequirementGoogleReview != nil {
		in, out := &in.PublishRequirementGoogleReview, &out.PublishRequirementGoogleReview
		*out = new(PrivateOffer_PublishRequirementGoogleReviewObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.PublishTime != nil {
		in, out := &in.PublishTime, &out.PublishTime
		*out = new(string)
		**out = **in
	}
	if in.AcceptTime != nil {
		in, out := &in.AcceptTime, &out.AcceptTime
		*out = new(string)
		**out = **in
	}
	if in.CancelTime != nil {
		in, out := &in.CancelTime, &out.CancelTime
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
	if in.CancellationNote != nil {
		in, out := &in.CancellationNote, &out.CancellationNote
		*out = new(string)
		**out = **in
	}
	if in.ResellerContact != nil {
		in, out := &in.ResellerContact, &out.ResellerContact
		*out = new(PrivateOffer_ResellerContactObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(PrivateOffer_CustomerObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.Term != nil {
		in, out := &in.Term, &out.Term
		*out = new(PrivateOffer_TermObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOfferObservedState.
func (in *CommerceProducerPrivateOfferObservedState) DeepCopy() *CommerceProducerPrivateOfferObservedState {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOfferObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOfferRef) DeepCopyInto(out *CommerceProducerPrivateOfferRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOfferRef.
func (in *CommerceProducerPrivateOfferRef) DeepCopy() *CommerceProducerPrivateOfferRef {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOfferRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOfferSpec) DeepCopyInto(out *CommerceProducerPrivateOfferSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.SingleProductOffer != nil {
		in, out := &in.SingleProductOffer, &out.SingleProductOffer
		*out = new(PrivateOffer_SingleProductOffer)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalNote != nil {
		in, out := &in.InternalNote, &out.InternalNote
		*out = new(string)
		**out = **in
	}
	if in.OfferDealType != nil {
		in, out := &in.OfferDealType, &out.OfferDealType
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.CustomerNote != nil {
		in, out := &in.CustomerNote, &out.CustomerNote
		*out = new(string)
		**out = **in
	}
	if in.PartnerContact != nil {
		in, out := &in.PartnerContact, &out.PartnerContact
		*out = new(PrivateOffer_PartnerContact)
		(*in).DeepCopyInto(*out)
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(PrivateOffer_Customer)
		(*in).DeepCopyInto(*out)
	}
	if in.AcceptDeadlineTime != nil {
		in, out := &in.AcceptDeadlineTime, &out.AcceptDeadlineTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
	if in.Term != nil {
		in, out := &in.Term, &out.Term
		*out = new(PrivateOffer_Term)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOfferSpec.
func (in *CommerceProducerPrivateOfferSpec) DeepCopy() *CommerceProducerPrivateOfferSpec {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOfferSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerPrivateOfferStatus) DeepCopyInto(out *CommerceProducerPrivateOfferStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(CommerceProducerPrivateOfferObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerPrivateOfferStatus.
func (in *CommerceProducerPrivateOfferStatus) DeepCopy() *CommerceProducerPrivateOfferStatus {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerPrivateOfferStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerSkuRef) DeepCopyInto(out *CommerceProducerSkuRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerSkuRef.
func (in *CommerceProducerSkuRef) DeepCopy() *CommerceProducerSkuRef {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerSkuRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommerceProducerStandardOfferRef) DeepCopyInto(out *CommerceProducerStandardOfferRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommerceProducerStandardOfferRef.
func (in *CommerceProducerStandardOfferRef) DeepCopy() *CommerceProducerStandardOfferRef {
	if in == nil {
		return nil
	}
	out := new(CommerceProducerStandardOfferRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DateTime) DeepCopyInto(out *DateTime) {
	*out = *in
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(int32)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(int32)
		**out = **in
	}
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(int32)
		**out = **in
	}
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = new(int32)
		**out = **in
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(int32)
		**out = **in
	}
	if in.Seconds != nil {
		in, out := &in.Seconds, &out.Seconds
		*out = new(int32)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(int32)
		**out = **in
	}
	if in.UtcOffset != nil {
		in, out := &in.UtcOffset, &out.UtcOffset
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(TimeZone)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateTime.
func (in *DateTime) DeepCopy() *DateTime {
	if in == nil {
		return nil
	}
	out := new(DateTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decimal) DeepCopyInto(out *Decimal) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decimal.
func (in *Decimal) DeepCopy() *Decimal {
	if in == nil {
		return nil
	}
	out := new(Decimal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Money) DeepCopyInto(out *Money) {
	*out = *in
	if in.CurrencyCode != nil {
		in, out := &in.CurrencyCode, &out.CurrencyCode
		*out = new(string)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(int64)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Money.
func (in *Money) DeepCopy() *Money {
	if in == nil {
		return nil
	}
	out := new(Money)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_Customer) DeepCopyInto(out *PrivateOffer_Customer) {
	*out = *in
	if in.EntityTitle != nil {
		in, out := &in.EntityTitle, &out.EntityTitle
		*out = new(string)
		**out = **in
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.TargetBillingAccountRef != nil {
		in, out := &in.TargetBillingAccountRef, &out.TargetBillingAccountRef
		*out = new(billingv1alpha1.BillingAccountRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_Customer.
func (in *PrivateOffer_Customer) DeepCopy() *PrivateOffer_Customer {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_Customer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_CustomerObservedState) DeepCopyInto(out *PrivateOffer_CustomerObservedState) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_CustomerObservedState.
func (in *PrivateOffer_CustomerObservedState) DeepCopy() *PrivateOffer_CustomerObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_CustomerObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_PartnerContact) DeepCopyInto(out *PrivateOffer_PartnerContact) {
	*out = *in
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_PartnerContact.
func (in *PrivateOffer_PartnerContact) DeepCopy() *PrivateOffer_PartnerContact {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_PartnerContact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_PublishRequirementGoogleReviewObservedState) DeepCopyInto(out *PrivateOffer_PublishRequirementGoogleReviewObservedState) {
	*out = *in
	if in.ReviewApproveTime != nil {
		in, out := &in.ReviewApproveTime, &out.ReviewApproveTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_PublishRequirementGoogleReviewObservedState.
func (in *PrivateOffer_PublishRequirementGoogleReviewObservedState) DeepCopy() *PrivateOffer_PublishRequirementGoogleReviewObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_PublishRequirementGoogleReviewObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_ResellerContactObservedState) DeepCopyInto(out *PrivateOffer_ResellerContactObservedState) {
	*out = *in
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_ResellerContactObservedState.
func (in *PrivateOffer_ResellerContactObservedState) DeepCopy() *PrivateOffer_ResellerContactObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_ResellerContactObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer) DeepCopyInto(out *PrivateOffer_SingleProductOffer) {
	*out = *in
	if in.AmendedPrivateOfferRef != nil {
		in, out := &in.AmendedPrivateOfferRef, &out.AmendedPrivateOfferRef
		*out = new(CommerceProducerPrivateOfferRef)
		**out = **in
	}
	if in.AmendedStandardOfferRef != nil {
		in, out := &in.AmendedStandardOfferRef, &out.AmendedStandardOfferRef
		*out = new(CommerceProducerStandardOfferRef)
		**out = **in
	}
	if in.StandardIntervalPrice != nil {
		in, out := &in.StandardIntervalPrice, &out.StandardIntervalPrice
		*out = new(PrivateOffer_SingleProductOffer_StandardIntervalPrice)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomIntervalPrice != nil {
		in, out := &in.CustomIntervalPrice, &out.CustomIntervalPrice
		*out = new(PrivateOffer_SingleProductOffer_CustomIntervalPrice)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseStandardOfferRef != nil {
		in, out := &in.BaseStandardOfferRef, &out.BaseStandardOfferRef
		*out = new(CommerceProducerStandardOfferRef)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]PrivateOffer_SingleProductOffer_Feature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalContractValue != nil {
		in, out := &in.AdditionalContractValue, &out.AdditionalContractValue
		*out = new(PrivateOffer_SingleProductOffer_AdditionalContractValue)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer.
func (in *PrivateOffer_SingleProductOffer) DeepCopy() *PrivateOffer_SingleProductOffer {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOfferObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOfferObservedState) {
	*out = *in
	if in.ServiceLevel != nil {
		in, out := &in.ServiceLevel, &out.ServiceLevel
		*out = new(string)
		**out = **in
	}
	if in.ResellerPrivateOfferPlanID != nil {
		in, out := &in.ResellerPrivateOfferPlanID, &out.ResellerPrivateOfferPlanID
		*out = new(string)
		**out = **in
	}
	if in.EffectiveInstallmentTimeline != nil {
		in, out := &in.EffectiveInstallmentTimeline, &out.EffectiveInstallmentTimeline
		*out = make([]PrivateOffer_SingleProductOffer_InstallmentObservedState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContractValue != nil {
		in, out := &in.ContractValue, &out.ContractValue
		*out = new(PrivateOffer_SingleProductOffer_ContractValueObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.RevenueShare != nil {
		in, out := &in.RevenueShare, &out.RevenueShare
		*out = new(PrivateOffer_SingleProductOffer_RevenueShareObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOfferObservedState.
func (in *PrivateOffer_SingleProductOfferObservedState) DeepCopy() *PrivateOffer_SingleProductOfferObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOfferObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_AdditionalContractValue) DeepCopyInto(out *PrivateOffer_SingleProductOffer_AdditionalContractValue) {
	*out = *in
	if in.ContractValue != nil {
		in, out := &in.ContractValue, &out.ContractValue
		*out = new(Money)
		(*in).DeepCopyInto(*out)
	}
	if in.EligibleSkuRefs != nil {
		in, out := &in.EligibleSkuRefs, &out.EligibleSkuRefs
		*out = make([]CommerceProducerSkuRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_AdditionalContractValue.
func (in *PrivateOffer_SingleProductOffer_AdditionalContractValue) DeepCopy() *PrivateOffer_SingleProductOffer_AdditionalContractValue {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_AdditionalContractValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_ContractValueObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_ContractValueObservedState) {
	*out = *in
	if in.TotalContractValue != nil {
		in, out := &in.TotalContractValue, &out.TotalContractValue
		*out = new(Money)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_ContractValueObservedState.
func (in *PrivateOffer_SingleProductOffer_ContractValueObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_ContractValueObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_ContractValueObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_CustomIntervalPrice) DeepCopyInto(out *PrivateOffer_SingleProductOffer_CustomIntervalPrice) {
	*out = *in
	if in.Installments != nil {
		in, out := &in.Installments, &out.Installments
		*out = make([]PrivateOffer_SingleProductOffer_Installment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_CustomIntervalPrice.
func (in *PrivateOffer_SingleProductOffer_CustomIntervalPrice) DeepCopy() *PrivateOffer_SingleProductOffer_CustomIntervalPrice {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_CustomIntervalPrice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_Feature) DeepCopyInto(out *PrivateOffer_SingleProductOffer_Feature) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_Feature.
func (in *PrivateOffer_SingleProductOffer_Feature) DeepCopy() *PrivateOffer_SingleProductOffer_Feature {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_Feature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_Installment) DeepCopyInto(out *PrivateOffer_SingleProductOffer_Installment) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
	if in.PriceModel != nil {
		in, out := &in.PriceModel, &out.PriceModel
		*out = new(PrivateOffer_SingleProductOffer_PriceModel)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_Installment.
func (in *PrivateOffer_SingleProductOffer_Installment) DeepCopy() *PrivateOffer_SingleProductOffer_Installment {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_Installment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_InstallmentObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_InstallmentObservedState) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
	if in.PriceModel != nil {
		in, out := &in.PriceModel, &out.PriceModel
		*out = new(PrivateOffer_SingleProductOffer_PriceModelObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_InstallmentObservedState.
func (in *PrivateOffer_SingleProductOffer_InstallmentObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_InstallmentObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_InstallmentObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel) {
	*out = *in
	if in.FlatFee != nil {
		in, out := &in.FlatFee, &out.FlatFee
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_FlatFee)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_Usage)
		(*in).DeepCopyInto(*out)
	}
	if in.Commitment != nil {
		in, out := &in.Commitment, &out.Commitment
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_Commitment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel.
func (in *PrivateOffer_SingleProductOffer_PriceModel) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModelObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModelObservedState) {
	*out = *in
	if in.FlatFee != nil {
		in, out := &in.FlatFee, &out.FlatFee
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_FlatFee)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.Commitment != nil {
		in, out := &in.Commitment, &out.Commitment
		*out = new(PrivateOffer_SingleProductOffer_PriceModel_Commitment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModelObservedState.
func (in *PrivateOffer_SingleProductOffer_PriceModelObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModelObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModelObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_Commitment) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_Commitment) {
	*out = *in
	if in.CommitmentAmount != nil {
		in, out := &in.CommitmentAmount, &out.CommitmentAmount
		*out = new(Money)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscountPercent != nil {
		in, out := &in.DiscountPercent, &out.DiscountPercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalCredit != nil {
		in, out := &in.AdditionalCredit, &out.AdditionalCredit
		*out = new(Money)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscardPreviousCreditBalance != nil {
		in, out := &in.DiscardPreviousCreditBalance, &out.DiscardPreviousCreditBalance
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_Commitment.
func (in *PrivateOffer_SingleProductOffer_PriceModel_Commitment) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_Commitment {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_Commitment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_FlatFee) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_FlatFee) {
	*out = *in
	if in.FlatFeeOverride != nil {
		in, out := &in.FlatFeeOverride, &out.FlatFeeOverride
		*out = new(Money)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_FlatFee.
func (in *PrivateOffer_SingleProductOffer_PriceModel_FlatFee) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_FlatFee {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_FlatFee)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount) {
	*out = *in
	if in.SkuRef != nil {
		in, out := &in.SkuRef, &out.SkuRef
		*out = new(CommerceProducerSkuRef)
		**out = **in
	}
	if in.CloudBillingSku != nil {
		in, out := &in.CloudBillingSku, &out.CloudBillingSku
		*out = new(string)
		**out = **in
	}
	if in.DiscountPercent != nil {
		in, out := &in.DiscountPercent, &out.DiscountPercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount.
func (in *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState) {
	*out = *in
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = new(string)
		**out = **in
	}
	if in.CloudBillingSku != nil {
		in, out := &in.CloudBillingSku, &out.CloudBillingSku
		*out = new(string)
		**out = **in
	}
	if in.DiscountPercent != nil {
		in, out := &in.DiscountPercent, &out.DiscountPercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState.
func (in *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_Usage) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_Usage) {
	*out = *in
	if in.DefaultDiscountPercent != nil {
		in, out := &in.DefaultDiscountPercent, &out.DefaultDiscountPercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
	if in.SkuDiscounts != nil {
		in, out := &in.SkuDiscounts, &out.SkuDiscounts
		*out = make([]PrivateOffer_SingleProductOffer_PriceModel_SkuDiscount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_Usage.
func (in *PrivateOffer_SingleProductOffer_PriceModel_Usage) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_Usage {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_Usage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState) {
	*out = *in
	if in.DefaultDiscountPercent != nil {
		in, out := &in.DefaultDiscountPercent, &out.DefaultDiscountPercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
	if in.SkuDiscounts != nil {
		in, out := &in.SkuDiscounts, &out.SkuDiscounts
		*out = make([]PrivateOffer_SingleProductOffer_PriceModel_SkuDiscountObservedState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState.
func (in *PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_PriceModel_UsageObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_RevenueShareObservedState) DeepCopyInto(out *PrivateOffer_SingleProductOffer_RevenueShareObservedState) {
	*out = *in
	if in.CurrentTermVendorNetRevenuePercent != nil {
		in, out := &in.CurrentTermVendorNetRevenuePercent, &out.CurrentTermVendorNetRevenuePercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
	if in.RenewalTermVendorNetRevenuePercent != nil {
		in, out := &in.RenewalTermVendorNetRevenuePercent, &out.RenewalTermVendorNetRevenuePercent
		*out = new(Decimal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_RevenueShareObservedState.
func (in *PrivateOffer_SingleProductOffer_RevenueShareObservedState) DeepCopy() *PrivateOffer_SingleProductOffer_RevenueShareObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_RevenueShareObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_SingleProductOffer_StandardIntervalPrice) DeepCopyInto(out *PrivateOffer_SingleProductOffer_StandardIntervalPrice) {
	*out = *in
	if in.StandardInterval != nil {
		in, out := &in.StandardInterval, &out.StandardInterval
		*out = new(string)
		**out = **in
	}
	if in.PriceModel != nil {
		in, out := &in.PriceModel, &out.PriceModel
		*out = new(PrivateOffer_SingleProductOffer_PriceModel)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_SingleProductOffer_StandardIntervalPrice.
func (in *PrivateOffer_SingleProductOffer_StandardIntervalPrice) DeepCopy() *PrivateOffer_SingleProductOffer_StandardIntervalPrice {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_SingleProductOffer_StandardIntervalPrice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_Term) DeepCopyInto(out *PrivateOffer_Term) {
	*out = *in
	if in.DurationMonths != nil {
		in, out := &in.DurationMonths, &out.DurationMonths
		*out = new(int32)
		**out = **in
	}
	if in.ScheduledEndTime != nil {
		in, out := &in.ScheduledEndTime, &out.ScheduledEndTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxRenewalCount != nil {
		in, out := &in.MaxRenewalCount, &out.MaxRenewalCount
		*out = new(int32)
		**out = **in
	}
	if in.StartPolicy != nil {
		in, out := &in.StartPolicy, &out.StartPolicy
		*out = new(string)
		**out = **in
	}
	if in.ScheduledStartTime != nil {
		in, out := &in.ScheduledStartTime, &out.ScheduledStartTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
	if in.EndPolicy != nil {
		in, out := &in.EndPolicy, &out.EndPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_Term.
func (in *PrivateOffer_Term) DeepCopy() *PrivateOffer_Term {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_Term)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateOffer_TermObservedState) DeepCopyInto(out *PrivateOffer_TermObservedState) {
	*out = *in
	if in.UnlimitedRenewal != nil {
		in, out := &in.UnlimitedRenewal, &out.UnlimitedRenewal
		*out = new(bool)
		**out = **in
	}
	if in.EffectiveTermEndTime != nil {
		in, out := &in.EffectiveTermEndTime, &out.EffectiveTermEndTime
		*out = new(DateTime)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateOffer_TermObservedState.
func (in *PrivateOffer_TermObservedState) DeepCopy() *PrivateOffer_TermObservedState {
	if in == nil {
		return nil
	}
	out := new(PrivateOffer_TermObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeZone) DeepCopyInto(out *TimeZone) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeZone.
func (in *TimeZone) DeepCopy() *TimeZone {
	if in == nil {
		return nil
	}
	out := new(TimeZone)
	in.DeepCopyInto(out)
	return out
}
