#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

# Run the tests specified on the command line
export RUN_TESTS=TestAllInSeries/$1

# Clear existing artifacts
rm -rf $(pwd)/artifactz/realgcp

# Run e2e tests against real gcp
WRITE_GOLDEN_OUTPUT="" ARTIFACTS=$(pwd)/artifactz/realgcp E2E_GCP_TARGET=real dev/tasks/run-e2e
