#!/bin/bash

set -e
set -x

export KUBEBUILDER_ASSETS=$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use -p path)

rm -rf $(pwd)/artifactz/realgcp

RUN_TESTS=TestAllInSeries/$1

if [[ -z "${GCP_PROJECT_ID:-}" ]]; then
  GCP_PROJECT_ID=$(gcloud config get-value project)
fi
echo "Using project: ${GCP_PROJECT_ID}"

TEST_FOLDER_ID=$(gcloud projects describe ${GCP_PROJECT_ID} --format='value(parent.id)')
export TEST_FOLDER_ID

# Run e2e tests against real gcp, capturing output
ARTIFACTS=$(pwd)/artifactz/realgcp \
E2E_KUBE_TARGET=envtest \
E2E_GCP_TARGET=real \
GOLDEN_REQUEST_CHECKS=1 \
GOLDEN_OBJECT_CHECKS=1 \
WRITE_GOLDEN_OUTPUT=1 \
RUN_E2E=1 \
 go test ./tests/e2e -timeout 3600s -v -run $RUN_TESTS