// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tools/openapi-to-krm. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper

package dns

import (
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/dns/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
	api "google.golang.org/api/dns/v1"
)

/* found existing non-generated mapping function "DNSManagedZoneSpec_FromAPI", skipping
func DNSManagedZoneSpec_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZone) *krm.DNSManagedZoneSpec {
	if in == nil {
		return nil
	}
	out := &krm.DNSManagedZoneSpec{}
	out.CloudLoggingConfig = ManagedZoneCloudLoggingConfig_FromAPI(mapCtx, in.CloudLoggingConfig)
	out.Description = direct.LazyPtr(in.Description)
	out.DnsName = in.DnsName
	out.DnssecConfig = ManagedZoneDnsSecConfig_FromAPI(mapCtx, in.DnssecConfig)
	out.ForwardingConfig = ManagedZoneForwardingConfig_FromAPI(mapCtx, in.ForwardingConfig)
	out.PeeringConfig = ManagedZonePeeringConfig_FromAPI(mapCtx, in.PeeringConfig)
	out.PrivateVisibilityConfig = ManagedZonePrivateVisibilityConfig_FromAPI(mapCtx, in.PrivateVisibilityConfig)
	out.ServiceDirectoryConfig = ManagedZoneServiceDirectoryConfig_FromAPI(mapCtx, in.ServiceDirectoryConfig)
	out.Visibility = direct.LazyPtr(in.Visibility)
	out.ResourceID = direct.LazyPtr(in.Name)
	// MISSING: ReverseLookup
	return out
}
*/

/* found existing non-generated mapping function "DNSManagedZoneSpec_ToAPI", skipping
func DNSManagedZoneSpec_ToAPI(mapCtx *direct.MapContext, in *krm.DNSManagedZoneSpec) *api.ManagedZone {
	if in == nil {
		return nil
	}
	out := &api.ManagedZone{}
	out.CloudLoggingConfig = ManagedZoneCloudLoggingConfig_ToAPI(mapCtx, in.CloudLoggingConfig)
	out.Description = direct.ValueOf(in.Description)
	out.DnsName = in.DnsName
	out.DnssecConfig = ManagedZoneDnsSecConfig_ToAPI(mapCtx, in.DnssecConfig)
	out.ForwardingConfig = ManagedZoneForwardingConfig_ToAPI(mapCtx, in.ForwardingConfig)
	out.PeeringConfig = ManagedZonePeeringConfig_ToAPI(mapCtx, in.PeeringConfig)
	out.PrivateVisibilityConfig = ManagedZonePrivateVisibilityConfig_ToAPI(mapCtx, in.PrivateVisibilityConfig)
	out.ServiceDirectoryConfig = ManagedZoneServiceDirectoryConfig_ToAPI(mapCtx, in.ServiceDirectoryConfig)
	out.Visibility = direct.ValueOf(in.Visibility)
	// MISSING: CreationTime
	// MISSING: Id
	// MISSING: Labels
	out.Name = direct.ValueOf(in.ResourceID)
	// MISSING: NameServerSet
	// MISSING: NameServers
	// MISSING: ReverseLookupConfig
	// MISSING: HTTPStatusCode
	// MISSING: Header
	return out
}
*/

/* found existing non-generated mapping function "DNSManagedZoneStatus_FromAPI", skipping
func DNSManagedZoneStatus_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZone) *krm.DNSManagedZoneStatus {
	if in == nil {
		return nil
	}
	out := &krm.DNSManagedZoneStatus{}
	out.CreationTime = direct.LazyPtr(in.CreationTime)
	out.NameServers = in.NameServers
	// MISSING: Conditions
	// MISSING: ManagedZoneId
	// MISSING: ObservedGeneration
	return out
}
*/

/* found existing non-generated mapping function "DNSManagedZoneStatus_ToAPI", skipping
func DNSManagedZoneStatus_ToAPI(mapCtx *direct.MapContext, in *krm.DNSManagedZoneStatus) *api.ManagedZone {
	if in == nil {
		return nil
	}
	out := &api.ManagedZone{}
	out.CreationTime = direct.ValueOf(in.CreationTime)
	out.NameServers = in.NameServers
	// MISSING: CloudLoggingConfig
	// MISSING: Description
	// MISSING: DnsName
	// MISSING: DnssecConfig
	// MISSING: ForwardingConfig
	// MISSING: Id
	// MISSING: Labels
	// MISSING: Name
	// MISSING: NameServerSet
	// MISSING: PeeringConfig
	// MISSING: PrivateVisibilityConfig
	// MISSING: ReverseLookupConfig
	// MISSING: ServiceDirectoryConfig
	// MISSING: Visibility
	// MISSING: HTTPStatusCode
	// MISSING: Header
	return out
}
*/

func ManagedZoneCloudLoggingConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneCloudLoggingConfig) *krm.ManagedZoneCloudLoggingConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneCloudLoggingConfig{}
	out.EnableLogging = direct.LazyPtr(in.EnableLogging)
	return out
}

func ManagedZoneCloudLoggingConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneCloudLoggingConfig) *api.ManagedZoneCloudLoggingConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneCloudLoggingConfig{}
	out.EnableLogging = direct.ValueOf(in.EnableLogging)
	return out
}

func ManagedZoneDnsSecConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneDnsSecConfig) *krm.ManagedZoneDnsSecConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneDnsSecConfig{}
	out.DefaultKeySpecs = direct.Slice_FromProto(mapCtx, in.DefaultKeySpecs, DnsKeySpec_FromAPI)
	out.Kind = direct.LazyPtr(in.Kind)
	out.NonExistence = direct.LazyPtr(in.NonExistence)
	out.State = direct.LazyPtr(in.State)
	return out
}

func ManagedZoneDnsSecConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneDnsSecConfig) *api.ManagedZoneDnsSecConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneDnsSecConfig{}
	out.DefaultKeySpecs = direct.Slice_ToProto(mapCtx, in.DefaultKeySpecs, DnsKeySpec_ToAPI)
	out.Kind = direct.ValueOf(in.Kind)
	out.NonExistence = direct.ValueOf(in.NonExistence)
	out.State = direct.ValueOf(in.State)
	return out
}

func ManagedZoneForwardingConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneForwardingConfig) *krm.ManagedZoneForwardingConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneForwardingConfig{}
	out.TargetNameServers = direct.Slice_FromProto(mapCtx, in.TargetNameServers, ManagedZoneForwardingConfigNameServerTarget_FromAPI)
	return out
}

func ManagedZoneForwardingConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneForwardingConfig) *api.ManagedZoneForwardingConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneForwardingConfig{}
	out.TargetNameServers = direct.Slice_ToProto(mapCtx, in.TargetNameServers, ManagedZoneForwardingConfigNameServerTarget_ToAPI)
	return out
}

func ManagedZonePeeringConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZonePeeringConfig) *krm.ManagedZonePeeringConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZonePeeringConfig{}
	out.TargetNetwork = ManagedZonePeeringConfigTargetNetwork_FromAPI(mapCtx, in.TargetNetwork)
	return out
}

func ManagedZonePeeringConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZonePeeringConfig) *api.ManagedZonePeeringConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZonePeeringConfig{}
	out.TargetNetwork = ManagedZonePeeringConfigTargetNetwork_ToAPI(mapCtx, in.TargetNetwork)
	return out
}

func ManagedZonePrivateVisibilityConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZonePrivateVisibilityConfig) *krm.ManagedZonePrivateVisibilityConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZonePrivateVisibilityConfig{}
	out.GKEClusters = direct.Slice_FromProto(mapCtx, in.GkeClusters, ManagedZonePrivateVisibilityConfigGKECluster_FromAPI)
	out.Networks = direct.Slice_FromProto(mapCtx, in.Networks, ManagedZonePrivateVisibilityConfigNetwork_FromAPI)
	return out
}

func ManagedZonePrivateVisibilityConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZonePrivateVisibilityConfig) *api.ManagedZonePrivateVisibilityConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZonePrivateVisibilityConfig{}
	out.GkeClusters = direct.Slice_ToProto(mapCtx, in.GKEClusters, ManagedZonePrivateVisibilityConfigGKECluster_ToAPI)
	out.Networks = direct.Slice_ToProto(mapCtx, in.Networks, ManagedZonePrivateVisibilityConfigNetwork_ToAPI)
	return out
}

func ManagedZoneServiceDirectoryConfig_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneServiceDirectoryConfig) *krm.ManagedZoneServiceDirectoryConfig {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneServiceDirectoryConfig{}
	out.Namespace = ManagedZoneServiceDirectoryConfigNamespace_FromAPI(mapCtx, in.Namespace)
	return out
}

func ManagedZoneServiceDirectoryConfig_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneServiceDirectoryConfig) *api.ManagedZoneServiceDirectoryConfig {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneServiceDirectoryConfig{}
	out.Namespace = ManagedZoneServiceDirectoryConfigNamespace_ToAPI(mapCtx, in.Namespace)
	return out
}

func DnsKeySpec_FromAPI(mapCtx *direct.MapContext, in *api.DnsKeySpec) *krm.DnsKeySpec {
	if in == nil {
		return nil
	}
	out := &krm.DnsKeySpec{}
	out.Algorithm = direct.LazyPtr(in.Algorithm)
	out.KeyLength = direct.LazyPtr(in.KeyLength)
	out.KeyType = direct.LazyPtr(in.KeyType)
	out.Kind = direct.LazyPtr(in.Kind)
	return out
}

func DnsKeySpec_ToAPI(mapCtx *direct.MapContext, in *krm.DnsKeySpec) *api.DnsKeySpec {
	if in == nil {
		return nil
	}
	out := &api.DnsKeySpec{}
	out.Algorithm = direct.ValueOf(in.Algorithm)
	out.KeyLength = direct.ValueOf(in.KeyLength)
	out.KeyType = direct.ValueOf(in.KeyType)
	out.Kind = direct.ValueOf(in.Kind)
	return out
}

func ManagedZoneForwardingConfigNameServerTarget_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneForwardingConfigNameServerTarget) *krm.ManagedZoneForwardingConfigNameServerTarget {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneForwardingConfigNameServerTarget{}
	out.ForwardingPath = direct.LazyPtr(in.ForwardingPath)
	out.Ipv4Address = in.Ipv4Address
	return out
}

func ManagedZoneForwardingConfigNameServerTarget_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneForwardingConfigNameServerTarget) *api.ManagedZoneForwardingConfigNameServerTarget {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneForwardingConfigNameServerTarget{}
	out.ForwardingPath = direct.ValueOf(in.ForwardingPath)
	out.Ipv4Address = in.Ipv4Address
	// MISSING: DomainName
	// MISSING: Ipv6Address
	return out
}

func ManagedZonePeeringConfigTargetNetwork_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZonePeeringConfigTargetNetwork) *krm.ManagedZonePeeringConfigTargetNetwork {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZonePeeringConfigTargetNetwork{}
	out.NetworkRef.External = in.NetworkUrl
	return out
}

func ManagedZonePeeringConfigTargetNetwork_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZonePeeringConfigTargetNetwork) *api.ManagedZonePeeringConfigTargetNetwork {
	if in == nil {
		return nil
	}
	out := &api.ManagedZonePeeringConfigTargetNetwork{}
	out.NetworkUrl = in.NetworkRef.External
	// MISSING: DeactivateTime
	return out
}

func ManagedZonePrivateVisibilityConfigGKECluster_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZonePrivateVisibilityConfigGKECluster) *krm.ManagedZonePrivateVisibilityConfigGKECluster {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZonePrivateVisibilityConfigGKECluster{}
	out.GkeClusterNameRef.External = in.GkeClusterName
	return out
}

func ManagedZonePrivateVisibilityConfigGKECluster_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZonePrivateVisibilityConfigGKECluster) *api.ManagedZonePrivateVisibilityConfigGKECluster {
	if in == nil {
		return nil
	}
	out := &api.ManagedZonePrivateVisibilityConfigGKECluster{}
	out.GkeClusterName = in.GkeClusterNameRef.External
	return out
}

func ManagedZonePrivateVisibilityConfigNetwork_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZonePrivateVisibilityConfigNetwork) *krm.ManagedZonePrivateVisibilityConfigNetwork {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZonePrivateVisibilityConfigNetwork{}
	out.NetworkRef.External = in.NetworkUrl
	return out
}

func ManagedZonePrivateVisibilityConfigNetwork_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZonePrivateVisibilityConfigNetwork) *api.ManagedZonePrivateVisibilityConfigNetwork {
	if in == nil {
		return nil
	}
	out := &api.ManagedZonePrivateVisibilityConfigNetwork{}
	out.NetworkUrl = in.NetworkRef.External
	return out
}

func ManagedZoneServiceDirectoryConfigNamespace_FromAPI(mapCtx *direct.MapContext, in *api.ManagedZoneServiceDirectoryConfigNamespace) *krm.ManagedZoneServiceDirectoryConfigNamespace {
	if in == nil {
		return nil
	}
	out := &krm.ManagedZoneServiceDirectoryConfigNamespace{}
	out.NamespaceUrl = in.NamespaceUrl
	return out
}

func ManagedZoneServiceDirectoryConfigNamespace_ToAPI(mapCtx *direct.MapContext, in *krm.ManagedZoneServiceDirectoryConfigNamespace) *api.ManagedZoneServiceDirectoryConfigNamespace {
	if in == nil {
		return nil
	}
	out := &api.ManagedZoneServiceDirectoryConfigNamespace{}
	out.NamespaceUrl = in.NamespaceUrl
	// MISSING: DeletionTime
	return out
}
