apiVersion: dataform.cnrm.cloud.google.com/v1beta1
kind: DataformRepositoryWorkflowConfig
metadata:
  name: dataformrepositoryworkflowconfig-sample
spec:
  repositoryRef:
    name: dataformrepository-sample
  releaseConfigRef:
    name: dataformrepositoryreleaseconfig-sample
  cronSchedule: "0 1 * * *"
  timeZone: "UTC"
  invocationConfig:
    includedTags:
      - tag1
    transitiveDependenciesIncluded: true
