#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

cd ${REPO_ROOT}/

echo "Downloading envtest assets..."
export KUBEBUILDER_ASSETS=$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use -p path)

echo "Running fixtures in tests/e2e..."

# The env var 'KCC_ENG_GROUP_EMAIL' needs to be set to unblock sample
# 'folder-level-entitlement'.
MOCK_GROUP_EMAIL="test@group.com"

RUN_E2E=1 \
E2E_KUBE_TARGET=envtest \
E2E_GCP_TARGET=mock \
KCC_USE_DIRECT_RECONCILERS="ComputeForwardingRule,SpannerInstance" \
KCC_ENG_GROUP_EMAIL="${MOCK_GROUP_EMAIL}" \
  go test -test.count=1 -timeout 1h30m -v ./tests/e2e -run TestAllInSeries/samples
