#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/

SKIP_TEST_APIGROUPS=(
    "apigee.cnrm.cloud.google.com"
    "backupdr.cnrm.cloud.google.com"
    "bigquery.cnrm.cloud.google.com"
    "bigqueryanalyticshub.cnrm.cloud.google.com"
    "bigqueryconnection.cnrm.cloud.google.com"
    "bigquerydatatransfer.cnrm.cloud.google.com"
    "bigqueryreservation.cnrm.cloud.google.com"
    "compute.cnrm.cloud.google.com"
    "gkehub.cnrm.cloud.google.com"
    "monitoring.cnrm.cloud.google.com"
    "secretmanager.cnrm.cloud.google.com"
    "sql.cnrm.cloud.google.com"
    "vertexai.cnrm.cloud.google.com"
    "vmwareengine.cnrm.cloud.google.com"
)

export SKIP_TEST_APIGROUP=$(IFS=, ; echo "${SKIP_TEST_APIGROUPS[*]}")
${REPO_ROOT}/dev/tasks/run-e2e
