//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/common"
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	k8sv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetImageAsset) DeepCopyInto(out *AssetImageAsset) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetImageAsset.
func (in *AssetImageAsset) DeepCopy() *AssetImageAsset {
	if in == nil {
		return nil
	}
	out := new(AssetImageAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetVideoAsset) DeepCopyInto(out *AssetVideoAsset) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetVideoAsset.
func (in *AssetVideoAsset) DeepCopy() *AssetVideoAsset {
	if in == nil {
		return nil
	}
	out := new(AssetVideoAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioFormat) DeepCopyInto(out *AudioFormat) {
	*out = *in
	if in.Codec != nil {
		in, out := &in.Codec, &out.Codec
		*out = new(string)
		**out = **in
	}
	if in.ChannelCount != nil {
		in, out := &in.ChannelCount, &out.ChannelCount
		*out = new(int32)
		**out = **in
	}
	if in.ChannelLayout != nil {
		in, out := &in.ChannelLayout, &out.ChannelLayout
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioFormat.
func (in *AudioFormat) DeepCopy() *AudioFormat {
	if in == nil {
		return nil
	}
	out := new(AudioFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioStream) DeepCopyInto(out *AudioStream) {
	*out = *in
	if in.Transmux != nil {
		in, out := &in.Transmux, &out.Transmux
		*out = new(bool)
		**out = **in
	}
	if in.Codec != nil {
		in, out := &in.Codec, &out.Codec
		*out = new(string)
		**out = **in
	}
	if in.BitrateBps != nil {
		in, out := &in.BitrateBps, &out.BitrateBps
		*out = new(int32)
		**out = **in
	}
	if in.ChannelCount != nil {
		in, out := &in.ChannelCount, &out.ChannelCount
		*out = new(int32)
		**out = **in
	}
	if in.ChannelLayout != nil {
		in, out := &in.ChannelLayout, &out.ChannelLayout
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]AudioStream_AudioMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SampleRateHertz != nil {
		in, out := &in.SampleRateHertz, &out.SampleRateHertz
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioStream.
func (in *AudioStream) DeepCopy() *AudioStream {
	if in == nil {
		return nil
	}
	out := new(AudioStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioStreamProperty) DeepCopyInto(out *AudioStreamProperty) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(int32)
		**out = **in
	}
	if in.AudioFormat != nil {
		in, out := &in.AudioFormat, &out.AudioFormat
		*out = new(AudioFormat)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioStreamProperty.
func (in *AudioStreamProperty) DeepCopy() *AudioStreamProperty {
	if in == nil {
		return nil
	}
	out := new(AudioStreamProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioStream_AudioMapping) DeepCopyInto(out *AudioStream_AudioMapping) {
	*out = *in
	if in.InputKey != nil {
		in, out := &in.InputKey, &out.InputKey
		*out = new(string)
		**out = **in
	}
	if in.InputTrack != nil {
		in, out := &in.InputTrack, &out.InputTrack
		*out = new(int32)
		**out = **in
	}
	if in.InputChannel != nil {
		in, out := &in.InputChannel, &out.InputChannel
		*out = new(int32)
		**out = **in
	}
	if in.OutputChannel != nil {
		in, out := &in.OutputChannel, &out.OutputChannel
		*out = new(int32)
		**out = **in
	}
	if in.GainDb != nil {
		in, out := &in.GainDb, &out.GainDb
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioStream_AudioMapping.
func (in *AudioStream_AudioMapping) DeepCopy() *AudioStream_AudioMapping {
	if in == nil {
		return nil
	}
	out := new(AudioStream_AudioMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Channel_Output) DeepCopyInto(out *Channel_Output) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Channel_Output.
func (in *Channel_Output) DeepCopy() *Channel_Output {
	if in == nil {
		return nil
	}
	out := new(Channel_Output)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvrSession_DvrManifest) DeepCopyInto(out *DvrSession_DvrManifest) {
	*out = *in
	if in.ManifestKey != nil {
		in, out := &in.ManifestKey, &out.ManifestKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvrSession_DvrManifest.
func (in *DvrSession_DvrManifest) DeepCopy() *DvrSession_DvrManifest {
	if in == nil {
		return nil
	}
	out := new(DvrSession_DvrManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvrSession_DvrManifestObservedState) DeepCopyInto(out *DvrSession_DvrManifestObservedState) {
	*out = *in
	if in.OutputURI != nil {
		in, out := &in.OutputURI, &out.OutputURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvrSession_DvrManifestObservedState.
func (in *DvrSession_DvrManifestObservedState) DeepCopy() *DvrSession_DvrManifestObservedState {
	if in == nil {
		return nil
	}
	out := new(DvrSession_DvrManifestObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DvrSession_DvrWindow) DeepCopyInto(out *DvrSession_DvrWindow) {
	*out = *in
	if in.TimeInterval != nil {
		in, out := &in.TimeInterval, &out.TimeInterval
		*out = new(TimeInterval)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DvrSession_DvrWindow.
func (in *DvrSession_DvrWindow) DeepCopy() *DvrSession_DvrWindow {
	if in == nil {
		return nil
	}
	out := new(DvrSession_DvrWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElementaryStream) DeepCopyInto(out *ElementaryStream) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.VideoStream != nil {
		in, out := &in.VideoStream, &out.VideoStream
		*out = new(VideoStream)
		(*in).DeepCopyInto(*out)
	}
	if in.AudioStream != nil {
		in, out := &in.AudioStream, &out.AudioStream
		*out = new(AudioStream)
		(*in).DeepCopyInto(*out)
	}
	if in.TextStream != nil {
		in, out := &in.TextStream, &out.TextStream
		*out = new(TextStream)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElementaryStream.
func (in *ElementaryStream) DeepCopy() *ElementaryStream {
	if in == nil {
		return nil
	}
	out := new(ElementaryStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption) DeepCopyInto(out *Encryption) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.SecretManagerKeySource != nil {
		in, out := &in.SecretManagerKeySource, &out.SecretManagerKeySource
		*out = new(Encryption_SecretManagerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.DrmSystems != nil {
		in, out := &in.DrmSystems, &out.DrmSystems
		*out = new(Encryption_DrmSystems)
		(*in).DeepCopyInto(*out)
	}
	if in.Aes128 != nil {
		in, out := &in.Aes128, &out.Aes128
		*out = new(Encryption_Aes128Encryption)
		**out = **in
	}
	if in.SampleAes != nil {
		in, out := &in.SampleAes, &out.SampleAes
		*out = new(Encryption_SampleAesEncryption)
		**out = **in
	}
	if in.MpegCenc != nil {
		in, out := &in.MpegCenc, &out.MpegCenc
		*out = new(Encryption_MpegCommonEncryption)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption.
func (in *Encryption) DeepCopy() *Encryption {
	if in == nil {
		return nil
	}
	out := new(Encryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_Aes128Encryption) DeepCopyInto(out *Encryption_Aes128Encryption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_Aes128Encryption.
func (in *Encryption_Aes128Encryption) DeepCopy() *Encryption_Aes128Encryption {
	if in == nil {
		return nil
	}
	out := new(Encryption_Aes128Encryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_Clearkey) DeepCopyInto(out *Encryption_Clearkey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_Clearkey.
func (in *Encryption_Clearkey) DeepCopy() *Encryption_Clearkey {
	if in == nil {
		return nil
	}
	out := new(Encryption_Clearkey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_DrmSystems) DeepCopyInto(out *Encryption_DrmSystems) {
	*out = *in
	if in.Widevine != nil {
		in, out := &in.Widevine, &out.Widevine
		*out = new(Encryption_Widevine)
		**out = **in
	}
	if in.Fairplay != nil {
		in, out := &in.Fairplay, &out.Fairplay
		*out = new(Encryption_Fairplay)
		**out = **in
	}
	if in.Playready != nil {
		in, out := &in.Playready, &out.Playready
		*out = new(Encryption_Playready)
		**out = **in
	}
	if in.Clearkey != nil {
		in, out := &in.Clearkey, &out.Clearkey
		*out = new(Encryption_Clearkey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_DrmSystems.
func (in *Encryption_DrmSystems) DeepCopy() *Encryption_DrmSystems {
	if in == nil {
		return nil
	}
	out := new(Encryption_DrmSystems)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_Fairplay) DeepCopyInto(out *Encryption_Fairplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_Fairplay.
func (in *Encryption_Fairplay) DeepCopy() *Encryption_Fairplay {
	if in == nil {
		return nil
	}
	out := new(Encryption_Fairplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_MpegCommonEncryption) DeepCopyInto(out *Encryption_MpegCommonEncryption) {
	*out = *in
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_MpegCommonEncryption.
func (in *Encryption_MpegCommonEncryption) DeepCopy() *Encryption_MpegCommonEncryption {
	if in == nil {
		return nil
	}
	out := new(Encryption_MpegCommonEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_Playready) DeepCopyInto(out *Encryption_Playready) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_Playready.
func (in *Encryption_Playready) DeepCopy() *Encryption_Playready {
	if in == nil {
		return nil
	}
	out := new(Encryption_Playready)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_SampleAesEncryption) DeepCopyInto(out *Encryption_SampleAesEncryption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_SampleAesEncryption.
func (in *Encryption_SampleAesEncryption) DeepCopy() *Encryption_SampleAesEncryption {
	if in == nil {
		return nil
	}
	out := new(Encryption_SampleAesEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_SecretManagerSource) DeepCopyInto(out *Encryption_SecretManagerSource) {
	*out = *in
	if in.SecretVersionRef != nil {
		in, out := &in.SecretVersionRef, &out.SecretVersionRef
		*out = new(v1beta1.SecretManagerSecretVersionRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_SecretManagerSource.
func (in *Encryption_SecretManagerSource) DeepCopy() *Encryption_SecretManagerSource {
	if in == nil {
		return nil
	}
	out := new(Encryption_SecretManagerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption_Widevine) DeepCopyInto(out *Encryption_Widevine) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption_Widevine.
func (in *Encryption_Widevine) DeepCopy() *Encryption_Widevine {
	if in == nil {
		return nil
	}
	out := new(Encryption_Widevine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputAttachment) DeepCopyInto(out *InputAttachment) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.InputRef != nil {
		in, out := &in.InputRef, &out.InputRef
		*out = new(LiveStreamInputRef)
		**out = **in
	}
	if in.AutomaticFailover != nil {
		in, out := &in.AutomaticFailover, &out.AutomaticFailover
		*out = new(InputAttachment_AutomaticFailover)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputAttachment.
func (in *InputAttachment) DeepCopy() *InputAttachment {
	if in == nil {
		return nil
	}
	out := new(InputAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputAttachment_AutomaticFailover) DeepCopyInto(out *InputAttachment_AutomaticFailover) {
	*out = *in
	if in.InputKeys != nil {
		in, out := &in.InputKeys, &out.InputKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputAttachment_AutomaticFailover.
func (in *InputAttachment_AutomaticFailover) DeepCopy() *InputAttachment_AutomaticFailover {
	if in == nil {
		return nil
	}
	out := new(InputAttachment_AutomaticFailover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputConfig) DeepCopyInto(out *InputConfig) {
	*out = *in
	if in.InputSwitchMode != nil {
		in, out := &in.InputSwitchMode, &out.InputSwitchMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputConfig.
func (in *InputConfig) DeepCopy() *InputConfig {
	if in == nil {
		return nil
	}
	out := new(InputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputSecurityRule) DeepCopyInto(out *InputSecurityRule) {
	*out = *in
	if in.IPRanges != nil {
		in, out := &in.IPRanges, &out.IPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputSecurityRule.
func (in *InputSecurityRule) DeepCopy() *InputSecurityRule {
	if in == nil {
		return nil
	}
	out := new(InputSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputStreamProperty) DeepCopyInto(out *InputStreamProperty) {
	*out = *in
	if in.LastEstablishTime != nil {
		in, out := &in.LastEstablishTime, &out.LastEstablishTime
		*out = new(string)
		**out = **in
	}
	if in.VideoStreams != nil {
		in, out := &in.VideoStreams, &out.VideoStreams
		*out = make([]VideoStreamProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AudioStreams != nil {
		in, out := &in.AudioStreams, &out.AudioStreams
		*out = make([]AudioStreamProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputStreamProperty.
func (in *InputStreamProperty) DeepCopy() *InputStreamProperty {
	if in == nil {
		return nil
	}
	out := new(InputStreamProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAsset) DeepCopyInto(out *LiveStreamAsset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAsset.
func (in *LiveStreamAsset) DeepCopy() *LiveStreamAsset {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamAsset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAssetList) DeepCopyInto(out *LiveStreamAssetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiveStreamAsset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAssetList.
func (in *LiveStreamAssetList) DeepCopy() *LiveStreamAssetList {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAssetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamAssetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAssetObservedState) DeepCopyInto(out *LiveStreamAssetObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(common.Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAssetObservedState.
func (in *LiveStreamAssetObservedState) DeepCopy() *LiveStreamAssetObservedState {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAssetObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAssetRef) DeepCopyInto(out *LiveStreamAssetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAssetRef.
func (in *LiveStreamAssetRef) DeepCopy() *LiveStreamAssetRef {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAssetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAssetSpec) DeepCopyInto(out *LiveStreamAssetSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Video != nil {
		in, out := &in.Video, &out.Video
		*out = new(AssetVideoAsset)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(AssetImageAsset)
		(*in).DeepCopyInto(*out)
	}
	if in.Crc32c != nil {
		in, out := &in.Crc32c, &out.Crc32c
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAssetSpec.
func (in *LiveStreamAssetSpec) DeepCopy() *LiveStreamAssetSpec {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAssetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamAssetStatus) DeepCopyInto(out *LiveStreamAssetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(LiveStreamAssetObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamAssetStatus.
func (in *LiveStreamAssetStatus) DeepCopy() *LiveStreamAssetStatus {
	if in == nil {
		return nil
	}
	out := new(LiveStreamAssetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannel) DeepCopyInto(out *LiveStreamChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannel.
func (in *LiveStreamChannel) DeepCopy() *LiveStreamChannel {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannelList) DeepCopyInto(out *LiveStreamChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiveStreamChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannelList.
func (in *LiveStreamChannelList) DeepCopy() *LiveStreamChannelList {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannelObservedState) DeepCopyInto(out *LiveStreamChannelObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.ActiveInput != nil {
		in, out := &in.ActiveInput, &out.ActiveInput
		*out = new(string)
		**out = **in
	}
	if in.StreamingState != nil {
		in, out := &in.StreamingState, &out.StreamingState
		*out = new(string)
		**out = **in
	}
	if in.StreamingError != nil {
		in, out := &in.StreamingError, &out.StreamingError
		*out = new(common.Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannelObservedState.
func (in *LiveStreamChannelObservedState) DeepCopy() *LiveStreamChannelObservedState {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannelObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannelRef) DeepCopyInto(out *LiveStreamChannelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannelRef.
func (in *LiveStreamChannelRef) DeepCopy() *LiveStreamChannelRef {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannelSpec) DeepCopyInto(out *LiveStreamChannelSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InputAttachments != nil {
		in, out := &in.InputAttachments, &out.InputAttachments
		*out = make([]InputAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(Channel_Output)
		(*in).DeepCopyInto(*out)
	}
	if in.ElementaryStreams != nil {
		in, out := &in.ElementaryStreams, &out.ElementaryStreams
		*out = make([]ElementaryStream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MuxStreams != nil {
		in, out := &in.MuxStreams, &out.MuxStreams
		*out = make([]MuxStream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]Manifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpriteSheets != nil {
		in, out := &in.SpriteSheets, &out.SpriteSheets
		*out = make([]SpriteSheet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogConfig != nil {
		in, out := &in.LogConfig, &out.LogConfig
		*out = new(LogConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TimecodeConfig != nil {
		in, out := &in.TimecodeConfig, &out.TimecodeConfig
		*out = new(TimecodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryptions != nil {
		in, out := &in.Encryptions, &out.Encryptions
		*out = make([]Encryption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InputConfig != nil {
		in, out := &in.InputConfig, &out.InputConfig
		*out = new(InputConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionConfig != nil {
		in, out := &in.RetentionConfig, &out.RetentionConfig
		*out = new(RetentionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticOverlays != nil {
		in, out := &in.StaticOverlays, &out.StaticOverlays
		*out = make([]StaticOverlay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannelSpec.
func (in *LiveStreamChannelSpec) DeepCopy() *LiveStreamChannelSpec {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamChannelStatus) DeepCopyInto(out *LiveStreamChannelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(LiveStreamChannelObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamChannelStatus.
func (in *LiveStreamChannelStatus) DeepCopy() *LiveStreamChannelStatus {
	if in == nil {
		return nil
	}
	out := new(LiveStreamChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSession) DeepCopyInto(out *LiveStreamDVRSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSession.
func (in *LiveStreamDVRSession) DeepCopy() *LiveStreamDVRSession {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamDVRSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSessionList) DeepCopyInto(out *LiveStreamDVRSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiveStreamDVRSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSessionList.
func (in *LiveStreamDVRSessionList) DeepCopy() *LiveStreamDVRSessionList {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamDVRSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSessionObservedState) DeepCopyInto(out *LiveStreamDVRSessionObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(common.Status)
		(*in).DeepCopyInto(*out)
	}
	if in.DvrManifests != nil {
		in, out := &in.DvrManifests, &out.DvrManifests
		*out = make([]DvrSession_DvrManifestObservedState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSessionObservedState.
func (in *LiveStreamDVRSessionObservedState) DeepCopy() *LiveStreamDVRSessionObservedState {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSessionObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSessionRef) DeepCopyInto(out *LiveStreamDVRSessionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSessionRef.
func (in *LiveStreamDVRSessionRef) DeepCopy() *LiveStreamDVRSessionRef {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSessionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSessionSpec) DeepCopyInto(out *LiveStreamDVRSessionSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DvrManifests != nil {
		in, out := &in.DvrManifests, &out.DvrManifests
		*out = make([]DvrSession_DvrManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DvrWindows != nil {
		in, out := &in.DvrWindows, &out.DvrWindows
		*out = make([]DvrSession_DvrWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSessionSpec.
func (in *LiveStreamDVRSessionSpec) DeepCopy() *LiveStreamDVRSessionSpec {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamDVRSessionStatus) DeepCopyInto(out *LiveStreamDVRSessionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(LiveStreamDVRSessionObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamDVRSessionStatus.
func (in *LiveStreamDVRSessionStatus) DeepCopy() *LiveStreamDVRSessionStatus {
	if in == nil {
		return nil
	}
	out := new(LiveStreamDVRSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInput) DeepCopyInto(out *LiveStreamInput) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInput.
func (in *LiveStreamInput) DeepCopy() *LiveStreamInput {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamInput) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInputList) DeepCopyInto(out *LiveStreamInputList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiveStreamInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInputList.
func (in *LiveStreamInputList) DeepCopy() *LiveStreamInputList {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInputList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiveStreamInputList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInputObservedState) DeepCopyInto(out *LiveStreamInputObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
	if in.InputStreamProperty != nil {
		in, out := &in.InputStreamProperty, &out.InputStreamProperty
		*out = new(InputStreamProperty)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInputObservedState.
func (in *LiveStreamInputObservedState) DeepCopy() *LiveStreamInputObservedState {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInputObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInputRef) DeepCopyInto(out *LiveStreamInputRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInputRef.
func (in *LiveStreamInputRef) DeepCopy() *LiveStreamInputRef {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInputRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInputSpec) DeepCopyInto(out *LiveStreamInputSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.PreprocessingConfig != nil {
		in, out := &in.PreprocessingConfig, &out.PreprocessingConfig
		*out = new(PreprocessingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityRules != nil {
		in, out := &in.SecurityRules, &out.SecurityRules
		*out = new(InputSecurityRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInputSpec.
func (in *LiveStreamInputSpec) DeepCopy() *LiveStreamInputSpec {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveStreamInputStatus) DeepCopyInto(out *LiveStreamInputStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(LiveStreamInputObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveStreamInputStatus.
func (in *LiveStreamInputStatus) DeepCopy() *LiveStreamInputStatus {
	if in == nil {
		return nil
	}
	out := new(LiveStreamInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
	if in.LogSeverity != nil {
		in, out := &in.LogSeverity, &out.LogSeverity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Manifest) DeepCopyInto(out *Manifest) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.MuxStreams != nil {
		in, out := &in.MuxStreams, &out.MuxStreams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxSegmentCount != nil {
		in, out := &in.MaxSegmentCount, &out.MaxSegmentCount
		*out = new(int32)
		**out = **in
	}
	if in.SegmentKeepDuration != nil {
		in, out := &in.SegmentKeepDuration, &out.SegmentKeepDuration
		*out = new(string)
		**out = **in
	}
	if in.UseTimecodeAsTimeline != nil {
		in, out := &in.UseTimecodeAsTimeline, &out.UseTimecodeAsTimeline
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manifest.
func (in *Manifest) DeepCopy() *Manifest {
	if in == nil {
		return nil
	}
	out := new(Manifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MuxStream) DeepCopyInto(out *MuxStream) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.ElementaryStreams != nil {
		in, out := &in.ElementaryStreams, &out.ElementaryStreams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SegmentSettings != nil {
		in, out := &in.SegmentSettings, &out.SegmentSettings
		*out = new(SegmentSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionID != nil {
		in, out := &in.EncryptionID, &out.EncryptionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MuxStream.
func (in *MuxStream) DeepCopy() *MuxStream {
	if in == nil {
		return nil
	}
	out := new(MuxStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedCoordinate) DeepCopyInto(out *NormalizedCoordinate) {
	*out = *in
	if in.X != nil {
		in, out := &in.X, &out.X
		*out = new(float64)
		**out = **in
	}
	if in.Y != nil {
		in, out := &in.Y, &out.Y
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedCoordinate.
func (in *NormalizedCoordinate) DeepCopy() *NormalizedCoordinate {
	if in == nil {
		return nil
	}
	out := new(NormalizedCoordinate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedResolution) DeepCopyInto(out *NormalizedResolution) {
	*out = *in
	if in.W != nil {
		in, out := &in.W, &out.W
		*out = new(float64)
		**out = **in
	}
	if in.H != nil {
		in, out := &in.H, &out.H
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedResolution.
func (in *NormalizedResolution) DeepCopy() *NormalizedResolution {
	if in == nil {
		return nil
	}
	out := new(NormalizedResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreprocessingConfig) DeepCopyInto(out *PreprocessingConfig) {
	*out = *in
	if in.Audio != nil {
		in, out := &in.Audio, &out.Audio
		*out = new(PreprocessingConfigAudio)
		(*in).DeepCopyInto(*out)
	}
	if in.Crop != nil {
		in, out := &in.Crop, &out.Crop
		*out = new(PreprocessingConfigCrop)
		(*in).DeepCopyInto(*out)
	}
	if in.Pad != nil {
		in, out := &in.Pad, &out.Pad
		*out = new(PreprocessingConfigPad)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreprocessingConfig.
func (in *PreprocessingConfig) DeepCopy() *PreprocessingConfig {
	if in == nil {
		return nil
	}
	out := new(PreprocessingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreprocessingConfigAudio) DeepCopyInto(out *PreprocessingConfigAudio) {
	*out = *in
	if in.Lufs != nil {
		in, out := &in.Lufs, &out.Lufs
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreprocessingConfigAudio.
func (in *PreprocessingConfigAudio) DeepCopy() *PreprocessingConfigAudio {
	if in == nil {
		return nil
	}
	out := new(PreprocessingConfigAudio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreprocessingConfigCrop) DeepCopyInto(out *PreprocessingConfigCrop) {
	*out = *in
	if in.TopPixels != nil {
		in, out := &in.TopPixels, &out.TopPixels
		*out = new(int32)
		**out = **in
	}
	if in.BottomPixels != nil {
		in, out := &in.BottomPixels, &out.BottomPixels
		*out = new(int32)
		**out = **in
	}
	if in.LeftPixels != nil {
		in, out := &in.LeftPixels, &out.LeftPixels
		*out = new(int32)
		**out = **in
	}
	if in.RightPixels != nil {
		in, out := &in.RightPixels, &out.RightPixels
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreprocessingConfigCrop.
func (in *PreprocessingConfigCrop) DeepCopy() *PreprocessingConfigCrop {
	if in == nil {
		return nil
	}
	out := new(PreprocessingConfigCrop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreprocessingConfigPad) DeepCopyInto(out *PreprocessingConfigPad) {
	*out = *in
	if in.TopPixels != nil {
		in, out := &in.TopPixels, &out.TopPixels
		*out = new(int32)
		**out = **in
	}
	if in.BottomPixels != nil {
		in, out := &in.BottomPixels, &out.BottomPixels
		*out = new(int32)
		**out = **in
	}
	if in.LeftPixels != nil {
		in, out := &in.LeftPixels, &out.LeftPixels
		*out = new(int32)
		**out = **in
	}
	if in.RightPixels != nil {
		in, out := &in.RightPixels, &out.RightPixels
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreprocessingConfigPad.
func (in *PreprocessingConfigPad) DeepCopy() *PreprocessingConfigPad {
	if in == nil {
		return nil
	}
	out := new(PreprocessingConfigPad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionConfig) DeepCopyInto(out *RetentionConfig) {
	*out = *in
	if in.RetentionWindowDuration != nil {
		in, out := &in.RetentionWindowDuration, &out.RetentionWindowDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionConfig.
func (in *RetentionConfig) DeepCopy() *RetentionConfig {
	if in == nil {
		return nil
	}
	out := new(RetentionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SegmentSettings) DeepCopyInto(out *SegmentSettings) {
	*out = *in
	if in.SegmentDuration != nil {
		in, out := &in.SegmentDuration, &out.SegmentDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SegmentSettings.
func (in *SegmentSettings) DeepCopy() *SegmentSettings {
	if in == nil {
		return nil
	}
	out := new(SegmentSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpriteSheet) DeepCopyInto(out *SpriteSheet) {
	*out = *in
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.FilePrefix != nil {
		in, out := &in.FilePrefix, &out.FilePrefix
		*out = new(string)
		**out = **in
	}
	if in.SpriteWidthPixels != nil {
		in, out := &in.SpriteWidthPixels, &out.SpriteWidthPixels
		*out = new(int32)
		**out = **in
	}
	if in.SpriteHeightPixels != nil {
		in, out := &in.SpriteHeightPixels, &out.SpriteHeightPixels
		*out = new(int32)
		**out = **in
	}
	if in.ColumnCount != nil {
		in, out := &in.ColumnCount, &out.ColumnCount
		*out = new(int32)
		**out = **in
	}
	if in.RowCount != nil {
		in, out := &in.RowCount, &out.RowCount
		*out = new(int32)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpriteSheet.
func (in *SpriteSheet) DeepCopy() *SpriteSheet {
	if in == nil {
		return nil
	}
	out := new(SpriteSheet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticOverlay) DeepCopyInto(out *StaticOverlay) {
	*out = *in
	if in.AssetRef != nil {
		in, out := &in.AssetRef, &out.AssetRef
		*out = new(LiveStreamAssetRef)
		**out = **in
	}
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(NormalizedResolution)
		(*in).DeepCopyInto(*out)
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(NormalizedCoordinate)
		(*in).DeepCopyInto(*out)
	}
	if in.Opacity != nil {
		in, out := &in.Opacity, &out.Opacity
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticOverlay.
func (in *StaticOverlay) DeepCopy() *StaticOverlay {
	if in == nil {
		return nil
	}
	out := new(StaticOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextStream) DeepCopyInto(out *TextStream) {
	*out = *in
	if in.Codec != nil {
		in, out := &in.Codec, &out.Codec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextStream.
func (in *TextStream) DeepCopy() *TextStream {
	if in == nil {
		return nil
	}
	out := new(TextStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeInterval) DeepCopyInto(out *TimeInterval) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeInterval.
func (in *TimeInterval) DeepCopy() *TimeInterval {
	if in == nil {
		return nil
	}
	out := new(TimeInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeZone) DeepCopyInto(out *TimeZone) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeZone.
func (in *TimeZone) DeepCopy() *TimeZone {
	if in == nil {
		return nil
	}
	out := new(TimeZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimecodeConfig) DeepCopyInto(out *TimecodeConfig) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.UtcOffset != nil {
		in, out := &in.UtcOffset, &out.UtcOffset
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(TimeZone)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimecodeConfig.
func (in *TimecodeConfig) DeepCopy() *TimecodeConfig {
	if in == nil {
		return nil
	}
	out := new(TimecodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoFormat) DeepCopyInto(out *VideoFormat) {
	*out = *in
	if in.Codec != nil {
		in, out := &in.Codec, &out.Codec
		*out = new(string)
		**out = **in
	}
	if in.WidthPixels != nil {
		in, out := &in.WidthPixels, &out.WidthPixels
		*out = new(int32)
		**out = **in
	}
	if in.HeightPixels != nil {
		in, out := &in.HeightPixels, &out.HeightPixels
		*out = new(int32)
		**out = **in
	}
	if in.FrameRate != nil {
		in, out := &in.FrameRate, &out.FrameRate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoFormat.
func (in *VideoFormat) DeepCopy() *VideoFormat {
	if in == nil {
		return nil
	}
	out := new(VideoFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoStream) DeepCopyInto(out *VideoStream) {
	*out = *in
	if in.H264 != nil {
		in, out := &in.H264, &out.H264
		*out = new(VideoStream_H264CodecSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoStream.
func (in *VideoStream) DeepCopy() *VideoStream {
	if in == nil {
		return nil
	}
	out := new(VideoStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoStreamProperty) DeepCopyInto(out *VideoStreamProperty) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(int32)
		**out = **in
	}
	if in.VideoFormat != nil {
		in, out := &in.VideoFormat, &out.VideoFormat
		*out = new(VideoFormat)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoStreamProperty.
func (in *VideoStreamProperty) DeepCopy() *VideoStreamProperty {
	if in == nil {
		return nil
	}
	out := new(VideoStreamProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoStream_H264CodecSettings) DeepCopyInto(out *VideoStream_H264CodecSettings) {
	*out = *in
	if in.WidthPixels != nil {
		in, out := &in.WidthPixels, &out.WidthPixels
		*out = new(int32)
		**out = **in
	}
	if in.HeightPixels != nil {
		in, out := &in.HeightPixels, &out.HeightPixels
		*out = new(int32)
		**out = **in
	}
	if in.FrameRate != nil {
		in, out := &in.FrameRate, &out.FrameRate
		*out = new(float64)
		**out = **in
	}
	if in.BitrateBps != nil {
		in, out := &in.BitrateBps, &out.BitrateBps
		*out = new(int32)
		**out = **in
	}
	if in.AllowOpenGop != nil {
		in, out := &in.AllowOpenGop, &out.AllowOpenGop
		*out = new(bool)
		**out = **in
	}
	if in.GopFrameCount != nil {
		in, out := &in.GopFrameCount, &out.GopFrameCount
		*out = new(int32)
		**out = **in
	}
	if in.GopDuration != nil {
		in, out := &in.GopDuration, &out.GopDuration
		*out = new(string)
		**out = **in
	}
	if in.VbvSizeBits != nil {
		in, out := &in.VbvSizeBits, &out.VbvSizeBits
		*out = new(int32)
		**out = **in
	}
	if in.VbvFullnessBits != nil {
		in, out := &in.VbvFullnessBits, &out.VbvFullnessBits
		*out = new(int32)
		**out = **in
	}
	if in.EntropyCoder != nil {
		in, out := &in.EntropyCoder, &out.EntropyCoder
		*out = new(string)
		**out = **in
	}
	if in.BPyramid != nil {
		in, out := &in.BPyramid, &out.BPyramid
		*out = new(bool)
		**out = **in
	}
	if in.BFrameCount != nil {
		in, out := &in.BFrameCount, &out.BFrameCount
		*out = new(int32)
		**out = **in
	}
	if in.AqStrength != nil {
		in, out := &in.AqStrength, &out.AqStrength
		*out = new(float64)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.Tune != nil {
		in, out := &in.Tune, &out.Tune
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoStream_H264CodecSettings.
func (in *VideoStream_H264CodecSettings) DeepCopy() *VideoStream_H264CodecSettings {
	if in == nil {
		return nil
	}
	out := new(VideoStream_H264CodecSettings)
	in.DeepCopyInto(out)
	return out
}
