# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kcc-metrics
  namespace: cnrm-system
spec:
  selector:
    matchLabels:
      cnrm.cloud.google.com/system: "true"
  endpoints:
  - port: 8888
    interval: 30s
    metricRelabeling:
    - action: replace
      sourceLabels: [namespace]
      targetLabel: exported_namespace
  - port: 48797
    interval: 30s
    metricRelabeling:
    - action: replace
      sourceLabels: [namespace]
      targetLabel: exported_namespace
