//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	computev1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/compute/v1beta1"
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Any) DeepCopyInto(out *Any) {
	*out = *in
	if in.TypeURL != nil {
		in, out := &in.TypeURL, &out.TypeURL
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Any.
func (in *Any) DeepCopy() *Any {
	if in == nil {
		return nil
	}
	out := new(Any)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSettings) DeepCopyInto(out *AutoscalingSettings) {
	*out = *in
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(string)
		**out = **in
	}
	if in.MaxNumWorkers != nil {
		in, out := &in.MaxNumWorkers, &out.MaxNumWorkers
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSettings.
func (in *AutoscalingSettings) DeepCopy() *AutoscalingSettings {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryIoDetails) DeepCopyInto(out *BigQueryIoDetails) {
	*out = *in
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryIoDetails.
func (in *BigQueryIoDetails) DeepCopy() *BigQueryIoDetails {
	if in == nil {
		return nil
	}
	out := new(BigQueryIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigTableIoDetails) DeepCopyInto(out *BigTableIoDetails) {
	*out = *in
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigTableIoDetails.
func (in *BigTableIoDetails) DeepCopy() *BigTableIoDetails {
	if in == nil {
		return nil
	}
	out := new(BigTableIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSamplingConfig) DeepCopyInto(out *DataSamplingConfig) {
	*out = *in
	if in.Behaviors != nil {
		in, out := &in.Behaviors, &out.Behaviors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSamplingConfig.
func (in *DataSamplingConfig) DeepCopy() *DataSamplingConfig {
	if in == nil {
		return nil
	}
	out := new(DataSamplingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowFlexTemplateJob) DeepCopyInto(out *DataflowFlexTemplateJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowFlexTemplateJob.
func (in *DataflowFlexTemplateJob) DeepCopy() *DataflowFlexTemplateJob {
	if in == nil {
		return nil
	}
	out := new(DataflowFlexTemplateJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowFlexTemplateJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowFlexTemplateJobList) DeepCopyInto(out *DataflowFlexTemplateJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataflowFlexTemplateJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowFlexTemplateJobList.
func (in *DataflowFlexTemplateJobList) DeepCopy() *DataflowFlexTemplateJobList {
	if in == nil {
		return nil
	}
	out := new(DataflowFlexTemplateJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowFlexTemplateJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowFlexTemplateJobObservedState) DeepCopyInto(out *DataflowFlexTemplateJobObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowFlexTemplateJobObservedState.
func (in *DataflowFlexTemplateJobObservedState) DeepCopy() *DataflowFlexTemplateJobObservedState {
	if in == nil {
		return nil
	}
	out := new(DataflowFlexTemplateJobObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowFlexTemplateJobSpec) DeepCopyInto(out *DataflowFlexTemplateJobSpec) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ContainerSpecGcsPath != nil {
		in, out := &in.ContainerSpecGcsPath, &out.ContainerSpecGcsPath
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.TransformNameMapping != nil {
		in, out := &in.TransformNameMapping, &out.TransformNameMapping
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.NumWorkers != nil {
		in, out := &in.NumWorkers, &out.NumWorkers
		*out = new(int32)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int32)
		**out = **in
	}
	if in.ServiceAccountEmailRef != nil {
		in, out := &in.ServiceAccountEmailRef, &out.ServiceAccountEmailRef
		*out = new(refsv1beta1.IAMServiceAccountRef)
		**out = **in
	}
	if in.TempLocation != nil {
		in, out := &in.TempLocation, &out.TempLocation
		*out = new(string)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.AdditionalExperiments != nil {
		in, out := &in.AdditionalExperiments, &out.AdditionalExperiments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(computev1beta1.ComputeNetworkRef)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(refsv1beta1.ComputeSubnetworkRef)
		**out = **in
	}
	if in.KMSKeyNameRef != nil {
		in, out := &in.KMSKeyNameRef, &out.KMSKeyNameRef
		*out = new(refsv1beta1.KMSCryptoKeyRef)
		**out = **in
	}
	if in.IPConfiguration != nil {
		in, out := &in.IPConfiguration, &out.IPConfiguration
		*out = new(string)
		**out = **in
	}
	if in.EnableStreamingEngine != nil {
		in, out := &in.EnableStreamingEngine, &out.EnableStreamingEngine
		*out = new(bool)
		**out = **in
	}
	if in.StagingLocation != nil {
		in, out := &in.StagingLocation, &out.StagingLocation
		*out = new(string)
		**out = **in
	}
	if in.SdkContainerImage != nil {
		in, out := &in.SdkContainerImage, &out.SdkContainerImage
		*out = new(string)
		**out = **in
	}
	if in.AutoscalingAlgorithm != nil {
		in, out := &in.AutoscalingAlgorithm, &out.AutoscalingAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.LauncherMachineType != nil {
		in, out := &in.LauncherMachineType, &out.LauncherMachineType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowFlexTemplateJobSpec.
func (in *DataflowFlexTemplateJobSpec) DeepCopy() *DataflowFlexTemplateJobSpec {
	if in == nil {
		return nil
	}
	out := new(DataflowFlexTemplateJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowFlexTemplateJobStatus) DeepCopyInto(out *DataflowFlexTemplateJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.CurrentState != nil {
		in, out := &in.CurrentState, &out.CurrentState
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowFlexTemplateJobStatus.
func (in *DataflowFlexTemplateJobStatus) DeepCopy() *DataflowFlexTemplateJobStatus {
	if in == nil {
		return nil
	}
	out := new(DataflowFlexTemplateJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowJob) DeepCopyInto(out *DataflowJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowJob.
func (in *DataflowJob) DeepCopy() *DataflowJob {
	if in == nil {
		return nil
	}
	out := new(DataflowJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowJobList) DeepCopyInto(out *DataflowJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataflowJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowJobList.
func (in *DataflowJobList) DeepCopy() *DataflowJobList {
	if in == nil {
		return nil
	}
	out := new(DataflowJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowJobSpec) DeepCopyInto(out *DataflowJobSpec) {
	*out = *in
	if in.AdditionalExperiments != nil {
		in, out := &in.AdditionalExperiments, &out.AdditionalExperiments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableStreamingEngine != nil {
		in, out := &in.EnableStreamingEngine, &out.EnableStreamingEngine
		*out = new(bool)
		**out = **in
	}
	if in.IPConfiguration != nil {
		in, out := &in.IPConfiguration, &out.IPConfiguration
		*out = new(string)
		**out = **in
	}
	if in.KmsKeyRef != nil {
		in, out := &in.KmsKeyRef, &out.KmsKeyRef
		*out = new(refsv1beta1.KMSCryptoKeyRef)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int32)
		**out = **in
	}
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(computev1beta1.ComputeNetworkRef)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(refsv1beta1.IAMServiceAccountRef)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(refsv1beta1.ComputeSubnetworkRef)
		**out = **in
	}
	if in.TransformNameMapping != nil {
		in, out := &in.TransformNameMapping, &out.TransformNameMapping
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowJobSpec.
func (in *DataflowJobSpec) DeepCopy() *DataflowJobSpec {
	if in == nil {
		return nil
	}
	out := new(DataflowJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowJobStatus) DeepCopyInto(out *DataflowJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.JobID != nil {
		in, out := &in.JobID, &out.JobID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowJobStatus.
func (in *DataflowJobStatus) DeepCopy() *DataflowJobStatus {
	if in == nil {
		return nil
	}
	out := new(DataflowJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatastoreIoDetails) DeepCopyInto(out *DatastoreIoDetails) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatastoreIoDetails.
func (in *DatastoreIoDetails) DeepCopy() *DatastoreIoDetails {
	if in == nil {
		return nil
	}
	out := new(DatastoreIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugOptions) DeepCopyInto(out *DebugOptions) {
	*out = *in
	if in.EnableHotKeyLogging != nil {
		in, out := &in.EnableHotKeyLogging, &out.EnableHotKeyLogging
		*out = new(bool)
		**out = **in
	}
	if in.DataSampling != nil {
		in, out := &in.DataSampling, &out.DataSampling
		*out = new(DataSamplingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugOptions.
func (in *DebugOptions) DeepCopy() *DebugOptions {
	if in == nil {
		return nil
	}
	out := new(DebugOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Disk) DeepCopyInto(out *Disk) {
	*out = *in
	if in.SizeGB != nil {
		in, out := &in.SizeGB, &out.SizeGB
		*out = new(int32)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.MountPoint != nil {
		in, out := &in.MountPoint, &out.MountPoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Disk.
func (in *Disk) DeepCopy() *Disk {
	if in == nil {
		return nil
	}
	out := new(Disk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisplayData) DeepCopyInto(out *DisplayData) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.StrValue != nil {
		in, out := &in.StrValue, &out.StrValue
		*out = new(string)
		**out = **in
	}
	if in.Int64Value != nil {
		in, out := &in.Int64Value, &out.Int64Value
		*out = new(int64)
		**out = **in
	}
	if in.FloatValue != nil {
		in, out := &in.FloatValue, &out.FloatValue
		*out = new(float32)
		**out = **in
	}
	if in.JavaClassValue != nil {
		in, out := &in.JavaClassValue, &out.JavaClassValue
		*out = new(string)
		**out = **in
	}
	if in.TimestampValue != nil {
		in, out := &in.TimestampValue, &out.TimestampValue
		*out = new(string)
		**out = **in
	}
	if in.DurationValue != nil {
		in, out := &in.DurationValue, &out.DurationValue
		*out = new(string)
		**out = **in
	}
	if in.BoolValue != nil {
		in, out := &in.BoolValue, &out.BoolValue
		*out = new(bool)
		**out = **in
	}
	if in.ShortStrValue != nil {
		in, out := &in.ShortStrValue, &out.ShortStrValue
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisplayData.
func (in *DisplayData) DeepCopy() *DisplayData {
	if in == nil {
		return nil
	}
	out := new(DisplayData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment) DeepCopyInto(out *Environment) {
	*out = *in
	if in.TempStoragePrefix != nil {
		in, out := &in.TempStoragePrefix, &out.TempStoragePrefix
		*out = new(string)
		**out = **in
	}
	if in.ClusterManagerAPIService != nil {
		in, out := &in.ClusterManagerAPIService, &out.ClusterManagerAPIService
		*out = new(string)
		**out = **in
	}
	if in.Experiments != nil {
		in, out := &in.Experiments, &out.Experiments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceOptions != nil {
		in, out := &in.ServiceOptions, &out.ServiceOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceKMSKeyName != nil {
		in, out := &in.ServiceKMSKeyName, &out.ServiceKMSKeyName
		*out = new(string)
		**out = **in
	}
	if in.WorkerPools != nil {
		in, out := &in.WorkerPools, &out.WorkerPools
		*out = make([]WorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.UserAgent.DeepCopyInto(&out.UserAgent)
	in.Version.DeepCopyInto(&out.Version)
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	in.SdkPipelineOptions.DeepCopyInto(&out.SdkPipelineOptions)
	if in.InternalExperiments != nil {
		in, out := &in.InternalExperiments, &out.InternalExperiments
		*out = new(Any)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountEmail != nil {
		in, out := &in.ServiceAccountEmail, &out.ServiceAccountEmail
		*out = new(string)
		**out = **in
	}
	if in.FlexResourceSchedulingGoal != nil {
		in, out := &in.FlexResourceSchedulingGoal, &out.FlexResourceSchedulingGoal
		*out = new(string)
		**out = **in
	}
	if in.WorkerRegion != nil {
		in, out := &in.WorkerRegion, &out.WorkerRegion
		*out = new(string)
		**out = **in
	}
	if in.WorkerZone != nil {
		in, out := &in.WorkerZone, &out.WorkerZone
		*out = new(string)
		**out = **in
	}
	if in.DebugOptions != nil {
		in, out := &in.DebugOptions, &out.DebugOptions
		*out = new(DebugOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.StreamingMode != nil {
		in, out := &in.StreamingMode, &out.StreamingMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment.
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentObservedState) DeepCopyInto(out *EnvironmentObservedState) {
	*out = *in
	if in.ShuffleMode != nil {
		in, out := &in.ShuffleMode, &out.ShuffleMode
		*out = new(string)
		**out = **in
	}
	if in.UseStreamingEngineResourceBasedBilling != nil {
		in, out := &in.UseStreamingEngineResourceBasedBilling, &out.UseStreamingEngineResourceBasedBilling
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentObservedState.
func (in *EnvironmentObservedState) DeepCopy() *EnvironmentObservedState {
	if in == nil {
		return nil
	}
	out := new(EnvironmentObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStageState) DeepCopyInto(out *ExecutionStageState) {
	*out = *in
	if in.ExecutionStageName != nil {
		in, out := &in.ExecutionStageName, &out.ExecutionStageName
		*out = new(string)
		**out = **in
	}
	if in.ExecutionStageState != nil {
		in, out := &in.ExecutionStageState, &out.ExecutionStageState
		*out = new(string)
		**out = **in
	}
	if in.CurrentStateTime != nil {
		in, out := &in.CurrentStateTime, &out.CurrentStateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStageState.
func (in *ExecutionStageState) DeepCopy() *ExecutionStageState {
	if in == nil {
		return nil
	}
	out := new(ExecutionStageState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStageSummary) DeepCopyInto(out *ExecutionStageSummary) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.InputSource != nil {
		in, out := &in.InputSource, &out.InputSource
		*out = make([]ExecutionStageSummary_StageSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OutputSource != nil {
		in, out := &in.OutputSource, &out.OutputSource
		*out = make([]ExecutionStageSummary_StageSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrerequisiteStage != nil {
		in, out := &in.PrerequisiteStage, &out.PrerequisiteStage
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComponentTransform != nil {
		in, out := &in.ComponentTransform, &out.ComponentTransform
		*out = make([]ExecutionStageSummary_ComponentTransform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentSource != nil {
		in, out := &in.ComponentSource, &out.ComponentSource
		*out = make([]ExecutionStageSummary_ComponentSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStageSummary.
func (in *ExecutionStageSummary) DeepCopy() *ExecutionStageSummary {
	if in == nil {
		return nil
	}
	out := new(ExecutionStageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStageSummary_ComponentSource) DeepCopyInto(out *ExecutionStageSummary_ComponentSource) {
	*out = *in
	if in.UserName != nil {
		in, out := &in.UserName, &out.UserName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalTransformOrCollection != nil {
		in, out := &in.OriginalTransformOrCollection, &out.OriginalTransformOrCollection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStageSummary_ComponentSource.
func (in *ExecutionStageSummary_ComponentSource) DeepCopy() *ExecutionStageSummary_ComponentSource {
	if in == nil {
		return nil
	}
	out := new(ExecutionStageSummary_ComponentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStageSummary_ComponentTransform) DeepCopyInto(out *ExecutionStageSummary_ComponentTransform) {
	*out = *in
	if in.UserName != nil {
		in, out := &in.UserName, &out.UserName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalTransform != nil {
		in, out := &in.OriginalTransform, &out.OriginalTransform
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStageSummary_ComponentTransform.
func (in *ExecutionStageSummary_ComponentTransform) DeepCopy() *ExecutionStageSummary_ComponentTransform {
	if in == nil {
		return nil
	}
	out := new(ExecutionStageSummary_ComponentTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStageSummary_StageSource) DeepCopyInto(out *ExecutionStageSummary_StageSource) {
	*out = *in
	if in.UserName != nil {
		in, out := &in.UserName, &out.UserName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalTransformOrCollection != nil {
		in, out := &in.OriginalTransformOrCollection, &out.OriginalTransformOrCollection
		*out = new(string)
		**out = **in
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStageSummary_StageSource.
func (in *ExecutionStageSummary_StageSource) DeepCopy() *ExecutionStageSummary_StageSource {
	if in == nil {
		return nil
	}
	out := new(ExecutionStageSummary_StageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileIoDetails) DeepCopyInto(out *FileIoDetails) {
	*out = *in
	if in.FilePattern != nil {
		in, out := &in.FilePattern, &out.FilePattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileIoDetails.
func (in *FileIoDetails) DeepCopy() *FileIoDetails {
	if in == nil {
		return nil
	}
	out := new(FileIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobExecutionInfo) DeepCopyInto(out *JobExecutionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobExecutionInfo.
func (in *JobExecutionInfo) DeepCopy() *JobExecutionInfo {
	if in == nil {
		return nil
	}
	out := new(JobExecutionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobExecutionStageInfo) DeepCopyInto(out *JobExecutionStageInfo) {
	*out = *in
	if in.StepName != nil {
		in, out := &in.StepName, &out.StepName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobExecutionStageInfo.
func (in *JobExecutionStageInfo) DeepCopy() *JobExecutionStageInfo {
	if in == nil {
		return nil
	}
	out := new(JobExecutionStageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobMetadata) DeepCopyInto(out *JobMetadata) {
	*out = *in
	if in.SdkVersion != nil {
		in, out := &in.SdkVersion, &out.SdkVersion
		*out = new(SdkVersion)
		(*in).DeepCopyInto(*out)
	}
	if in.SpannerDetails != nil {
		in, out := &in.SpannerDetails, &out.SpannerDetails
		*out = make([]SpannerIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BigqueryDetails != nil {
		in, out := &in.BigqueryDetails, &out.BigqueryDetails
		*out = make([]BigQueryIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BigTableDetails != nil {
		in, out := &in.BigTableDetails, &out.BigTableDetails
		*out = make([]BigTableIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PubsubDetails != nil {
		in, out := &in.PubsubDetails, &out.PubsubDetails
		*out = make([]PubSubIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileDetails != nil {
		in, out := &in.FileDetails, &out.FileDetails
		*out = make([]FileIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DatastoreDetails != nil {
		in, out := &in.DatastoreDetails, &out.DatastoreDetails
		*out = make([]DatastoreIoDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserDisplayProperties != nil {
		in, out := &in.UserDisplayProperties, &out.UserDisplayProperties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobMetadata.
func (in *JobMetadata) DeepCopy() *JobMetadata {
	if in == nil {
		return nil
	}
	out := new(JobMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobMetadataObservedState) DeepCopyInto(out *JobMetadataObservedState) {
	*out = *in
	if in.SdkVersion != nil {
		in, out := &in.SdkVersion, &out.SdkVersion
		*out = new(SdkVersionObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobMetadataObservedState.
func (in *JobMetadataObservedState) DeepCopy() *JobMetadataObservedState {
	if in == nil {
		return nil
	}
	out := new(JobMetadataObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Package) DeepCopyInto(out *Package) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Package.
func (in *Package) DeepCopy() *Package {
	if in == nil {
		return nil
	}
	out := new(Package)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDescription) DeepCopyInto(out *PipelineDescription) {
	*out = *in
	if in.OriginalPipelineTransform != nil {
		in, out := &in.OriginalPipelineTransform, &out.OriginalPipelineTransform
		*out = make([]TransformSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExecutionPipelineStage != nil {
		in, out := &in.ExecutionPipelineStage, &out.ExecutionPipelineStage
		*out = make([]ExecutionStageSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayData != nil {
		in, out := &in.DisplayData, &out.DisplayData
		*out = make([]DisplayData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepNamesHash != nil {
		in, out := &in.StepNamesHash, &out.StepNamesHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDescription.
func (in *PipelineDescription) DeepCopy() *PipelineDescription {
	if in == nil {
		return nil
	}
	out := new(PipelineDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubSubIoDetails) DeepCopyInto(out *PubSubIoDetails) {
	*out = *in
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
	if in.Subscription != nil {
		in, out := &in.Subscription, &out.Subscription
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubSubIoDetails.
func (in *PubSubIoDetails) DeepCopy() *PubSubIoDetails {
	if in == nil {
		return nil
	}
	out := new(PubSubIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeUpdatableParams) DeepCopyInto(out *RuntimeUpdatableParams) {
	*out = *in
	if in.MaxNumWorkers != nil {
		in, out := &in.MaxNumWorkers, &out.MaxNumWorkers
		*out = new(int32)
		**out = **in
	}
	if in.MinNumWorkers != nil {
		in, out := &in.MinNumWorkers, &out.MinNumWorkers
		*out = new(int32)
		**out = **in
	}
	if in.WorkerUtilizationHint != nil {
		in, out := &in.WorkerUtilizationHint, &out.WorkerUtilizationHint
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeUpdatableParams.
func (in *RuntimeUpdatableParams) DeepCopy() *RuntimeUpdatableParams {
	if in == nil {
		return nil
	}
	out := new(RuntimeUpdatableParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkBug) DeepCopyInto(out *SdkBug) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkBug.
func (in *SdkBug) DeepCopy() *SdkBug {
	if in == nil {
		return nil
	}
	out := new(SdkBug)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkBugObservedState) DeepCopyInto(out *SdkBugObservedState) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(string)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkBugObservedState.
func (in *SdkBugObservedState) DeepCopy() *SdkBugObservedState {
	if in == nil {
		return nil
	}
	out := new(SdkBugObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkHarnessContainerImage) DeepCopyInto(out *SdkHarnessContainerImage) {
	*out = *in
	if in.ContainerImage != nil {
		in, out := &in.ContainerImage, &out.ContainerImage
		*out = new(string)
		**out = **in
	}
	if in.UseSingleCorePerContainer != nil {
		in, out := &in.UseSingleCorePerContainer, &out.UseSingleCorePerContainer
		*out = new(bool)
		**out = **in
	}
	if in.EnvironmentID != nil {
		in, out := &in.EnvironmentID, &out.EnvironmentID
		*out = new(string)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkHarnessContainerImage.
func (in *SdkHarnessContainerImage) DeepCopy() *SdkHarnessContainerImage {
	if in == nil {
		return nil
	}
	out := new(SdkHarnessContainerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkVersion) DeepCopyInto(out *SdkVersion) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VersionDisplayName != nil {
		in, out := &in.VersionDisplayName, &out.VersionDisplayName
		*out = new(string)
		**out = **in
	}
	if in.SdkSupportStatus != nil {
		in, out := &in.SdkSupportStatus, &out.SdkSupportStatus
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkVersion.
func (in *SdkVersion) DeepCopy() *SdkVersion {
	if in == nil {
		return nil
	}
	out := new(SdkVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdkVersionObservedState) DeepCopyInto(out *SdkVersionObservedState) {
	*out = *in
	if in.Bugs != nil {
		in, out := &in.Bugs, &out.Bugs
		*out = make([]SdkBug, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdkVersionObservedState.
func (in *SdkVersionObservedState) DeepCopy() *SdkVersionObservedState {
	if in == nil {
		return nil
	}
	out := new(SdkVersionObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceResources) DeepCopyInto(out *ServiceResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceResources.
func (in *ServiceResources) DeepCopy() *ServiceResources {
	if in == nil {
		return nil
	}
	out := new(ServiceResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceResourcesObservedState) DeepCopyInto(out *ServiceResourcesObservedState) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceResourcesObservedState.
func (in *ServiceResourcesObservedState) DeepCopy() *ServiceResourcesObservedState {
	if in == nil {
		return nil
	}
	out := new(ServiceResourcesObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpannerIoDetails) DeepCopyInto(out *SpannerIoDetails) {
	*out = *in
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.DatabaseID != nil {
		in, out := &in.DatabaseID, &out.DatabaseID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpannerIoDetails.
func (in *SpannerIoDetails) DeepCopy() *SpannerIoDetails {
	if in == nil {
		return nil
	}
	out := new(SpannerIoDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.Properties.DeepCopyInto(&out.Properties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRunnerSettings) DeepCopyInto(out *TaskRunnerSettings) {
	*out = *in
	if in.TaskUser != nil {
		in, out := &in.TaskUser, &out.TaskUser
		*out = new(string)
		**out = **in
	}
	if in.TaskGroup != nil {
		in, out := &in.TaskGroup, &out.TaskGroup
		*out = new(string)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.DataflowAPIVersion != nil {
		in, out := &in.DataflowAPIVersion, &out.DataflowAPIVersion
		*out = new(string)
		**out = **in
	}
	if in.ParallelWorkerSettings != nil {
		in, out := &in.ParallelWorkerSettings, &out.ParallelWorkerSettings
		*out = new(WorkerSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseTaskDir != nil {
		in, out := &in.BaseTaskDir, &out.BaseTaskDir
		*out = new(string)
		**out = **in
	}
	if in.ContinueOnException != nil {
		in, out := &in.ContinueOnException, &out.ContinueOnException
		*out = new(bool)
		**out = **in
	}
	if in.LogToSerialconsole != nil {
		in, out := &in.LogToSerialconsole, &out.LogToSerialconsole
		*out = new(bool)
		**out = **in
	}
	if in.Alsologtostderr != nil {
		in, out := &in.Alsologtostderr, &out.Alsologtostderr
		*out = new(bool)
		**out = **in
	}
	if in.LogUploadLocation != nil {
		in, out := &in.LogUploadLocation, &out.LogUploadLocation
		*out = new(string)
		**out = **in
	}
	if in.LogDir != nil {
		in, out := &in.LogDir, &out.LogDir
		*out = new(string)
		**out = **in
	}
	if in.TempStoragePrefix != nil {
		in, out := &in.TempStoragePrefix, &out.TempStoragePrefix
		*out = new(string)
		**out = **in
	}
	if in.HarnessCommand != nil {
		in, out := &in.HarnessCommand, &out.HarnessCommand
		*out = new(string)
		**out = **in
	}
	if in.WorkflowFileName != nil {
		in, out := &in.WorkflowFileName, &out.WorkflowFileName
		*out = new(string)
		**out = **in
	}
	if in.CommandlinesFileName != nil {
		in, out := &in.CommandlinesFileName, &out.CommandlinesFileName
		*out = new(string)
		**out = **in
	}
	if in.VMID != nil {
		in, out := &in.VMID, &out.VMID
		*out = new(string)
		**out = **in
	}
	if in.LanguageHint != nil {
		in, out := &in.LanguageHint, &out.LanguageHint
		*out = new(string)
		**out = **in
	}
	if in.StreamingWorkerMainClass != nil {
		in, out := &in.StreamingWorkerMainClass, &out.StreamingWorkerMainClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRunnerSettings.
func (in *TaskRunnerSettings) DeepCopy() *TaskRunnerSettings {
	if in == nil {
		return nil
	}
	out := new(TaskRunnerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformSummary) DeepCopyInto(out *TransformSummary) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.DisplayData != nil {
		in, out := &in.DisplayData, &out.DisplayData
		*out = make([]DisplayData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OutputCollectionName != nil {
		in, out := &in.OutputCollectionName, &out.OutputCollectionName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputCollectionName != nil {
		in, out := &in.InputCollectionName, &out.InputCollectionName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformSummary.
func (in *TransformSummary) DeepCopy() *TransformSummary {
	if in == nil {
		return nil
	}
	out := new(TransformSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPool) DeepCopyInto(out *WorkerPool) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.NumWorkers != nil {
		in, out := &in.NumWorkers, &out.NumWorkers
		*out = new(int32)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]Package, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultPackageSet != nil {
		in, out := &in.DefaultPackageSet, &out.DefaultPackageSet
		*out = new(string)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.TeardownPolicy != nil {
		in, out := &in.TeardownPolicy, &out.TeardownPolicy
		*out = new(string)
		**out = **in
	}
	if in.DiskSizeGB != nil {
		in, out := &in.DiskSizeGB, &out.DiskSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.DiskSourceImage != nil {
		in, out := &in.DiskSourceImage, &out.DiskSourceImage
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
	if in.TaskrunnerSettings != nil {
		in, out := &in.TaskrunnerSettings, &out.TaskrunnerSettings
		*out = new(TaskRunnerSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.OnHostMaintenance != nil {
		in, out := &in.OnHostMaintenance, &out.OnHostMaintenance
		*out = new(string)
		**out = **in
	}
	if in.DataDisks != nil {
		in, out := &in.DataDisks, &out.DataDisks
		*out = make([]Disk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AutoscalingSettings != nil {
		in, out := &in.AutoscalingSettings, &out.AutoscalingSettings
		*out = new(AutoscalingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.PoolArgs != nil {
		in, out := &in.PoolArgs, &out.PoolArgs
		*out = new(Any)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
	if in.WorkerHarnessContainerImage != nil {
		in, out := &in.WorkerHarnessContainerImage, &out.WorkerHarnessContainerImage
		*out = new(string)
		**out = **in
	}
	if in.NumThreadsPerWorker != nil {
		in, out := &in.NumThreadsPerWorker, &out.NumThreadsPerWorker
		*out = new(int32)
		**out = **in
	}
	if in.IPConfiguration != nil {
		in, out := &in.IPConfiguration, &out.IPConfiguration
		*out = new(string)
		**out = **in
	}
	if in.SdkHarnessContainerImages != nil {
		in, out := &in.SdkHarnessContainerImages, &out.SdkHarnessContainerImages
		*out = make([]SdkHarnessContainerImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPool.
func (in *WorkerPool) DeepCopy() *WorkerPool {
	if in == nil {
		return nil
	}
	out := new(WorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSettings) DeepCopyInto(out *WorkerSettings) {
	*out = *in
	if in.BaseURL != nil {
		in, out := &in.BaseURL, &out.BaseURL
		*out = new(string)
		**out = **in
	}
	if in.ReportingEnabled != nil {
		in, out := &in.ReportingEnabled, &out.ReportingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServicePath != nil {
		in, out := &in.ServicePath, &out.ServicePath
		*out = new(string)
		**out = **in
	}
	if in.ShuffleServicePath != nil {
		in, out := &in.ShuffleServicePath, &out.ShuffleServicePath
		*out = new(string)
		**out = **in
	}
	if in.WorkerID != nil {
		in, out := &in.WorkerID, &out.WorkerID
		*out = new(string)
		**out = **in
	}
	if in.TempStoragePrefix != nil {
		in, out := &in.TempStoragePrefix, &out.TempStoragePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSettings.
func (in *WorkerSettings) DeepCopy() *WorkerSettings {
	if in == nil {
		return nil
	}
	out := new(WorkerSettings)
	in.DeepCopyInto(out)
	return out
}
