// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: clouddeploy.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.deploy.v1

package clouddeploy

import (
	pb "cloud.google.com/go/deploy/apiv1/deploypb"
	krmcloudbuildv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/cloudbuild/v1beta1"
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/clouddeploy/v1alpha1"
	krmclouddeployv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/clouddeploy/v1beta1"
	krmgkehubv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/gkehub/v1beta1"
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
	dayofweekpb "google.golang.org/genproto/googleapis/type/dayofweek"
)

func AdvanceRolloutRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.AdvanceRolloutRuleObservedState) *pb.AdvanceRolloutRule {
	if in == nil {
		return nil
	}
	out := &pb.AdvanceRolloutRule{}
	// MISSING: ID
	// MISSING: SourcePhases
	// MISSING: Wait
	out.Condition = AutomationRuleCondition_v1alpha1_ToProto(mapCtx, in.Condition)
	return out
}
func AnthosCluster_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.AnthosCluster) *krm.AnthosCluster {
	if in == nil {
		return nil
	}
	out := &krm.AnthosCluster{}
	if in.GetMembership() != "" {
		out.MembershipRef = &krmgkehubv1beta1.GKEHubMembershipRef{External: in.GetMembership()}
	}
	return out
}
func AnthosCluster_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.AnthosCluster) *pb.AnthosCluster {
	if in == nil {
		return nil
	}
	out := &pb.AnthosCluster{}
	if in.MembershipRef != nil {
		out.Membership = in.MembershipRef.External
	}
	return out
}
func AutomationRuleCondition_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.AutomationRuleCondition) *pb.AutomationRuleCondition {
	if in == nil {
		return nil
	}
	out := &pb.AutomationRuleCondition{}
	out.TargetsPresentCondition = TargetsPresentCondition_v1alpha1_ToProto(mapCtx, in.TargetsPresentCondition)
	if oneof := TimedPromoteReleaseCondition_v1alpha1_ToProto(mapCtx, in.TimedPromoteReleaseCondition); oneof != nil {
		out.RuleTypeCondition = &pb.AutomationRuleCondition_TimedPromoteReleaseCondition{TimedPromoteReleaseCondition: oneof}
	}
	return out
}
func AutomationRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.AutomationRuleObservedState) *pb.AutomationRule {
	if in == nil {
		return nil
	}
	out := &pb.AutomationRule{}
	if oneof := PromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx, in.PromoteReleaseRule); oneof != nil {
		out.Rule = &pb.AutomationRule_PromoteReleaseRule{PromoteReleaseRule: oneof}
	}
	if oneof := AdvanceRolloutRuleObservedState_v1alpha1_ToProto(mapCtx, in.AdvanceRolloutRule); oneof != nil {
		out.Rule = &pb.AutomationRule_AdvanceRolloutRule{AdvanceRolloutRule: oneof}
	}
	if oneof := RepairRolloutRuleObservedState_v1alpha1_ToProto(mapCtx, in.RepairRolloutRule); oneof != nil {
		out.Rule = &pb.AutomationRule_RepairRolloutRule{RepairRolloutRule: oneof}
	}
	if oneof := TimedPromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx, in.TimedPromoteReleaseRule); oneof != nil {
		out.Rule = &pb.AutomationRule_TimedPromoteReleaseRule{TimedPromoteReleaseRule: oneof}
	}
	return out
}
func Canary_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Canary) *krmclouddeployv1beta1.Canary {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Canary{}
	out.RuntimeConfig = RuntimeConfig_v1beta1_FromProto(mapCtx, in.GetRuntimeConfig())
	out.CanaryDeployment = CanaryDeployment_v1beta1_FromProto(mapCtx, in.GetCanaryDeployment())
	out.CustomCanaryDeployment = CustomCanaryDeployment_v1beta1_FromProto(mapCtx, in.GetCustomCanaryDeployment())
	return out
}
func Canary_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Canary) *pb.Canary {
	if in == nil {
		return nil
	}
	out := &pb.Canary{}
	out.RuntimeConfig = RuntimeConfig_v1beta1_ToProto(mapCtx, in.RuntimeConfig)
	if oneof := CanaryDeployment_v1beta1_ToProto(mapCtx, in.CanaryDeployment); oneof != nil {
		out.Mode = &pb.Canary_CanaryDeployment{CanaryDeployment: oneof}
	}
	if oneof := CustomCanaryDeployment_v1beta1_ToProto(mapCtx, in.CustomCanaryDeployment); oneof != nil {
		out.Mode = &pb.Canary_CustomCanaryDeployment{CustomCanaryDeployment: oneof}
	}
	return out
}
func CanaryDeployment_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CanaryDeployment) *krmclouddeployv1beta1.CanaryDeployment {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CanaryDeployment{}
	out.Percentages = in.Percentages
	out.Verify = direct.LazyPtr(in.GetVerify())
	out.Predeploy = Predeploy_v1beta1_FromProto(mapCtx, in.GetPredeploy())
	out.Postdeploy = Postdeploy_v1beta1_FromProto(mapCtx, in.GetPostdeploy())
	return out
}
func CanaryDeployment_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CanaryDeployment) *pb.CanaryDeployment {
	if in == nil {
		return nil
	}
	out := &pb.CanaryDeployment{}
	out.Percentages = in.Percentages
	out.Verify = direct.ValueOf(in.Verify)
	out.Predeploy = Predeploy_v1beta1_ToProto(mapCtx, in.Predeploy)
	out.Postdeploy = Postdeploy_v1beta1_ToProto(mapCtx, in.Postdeploy)
	return out
}
func CloudRunConfig_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CloudRunConfig) *krmclouddeployv1beta1.CloudRunConfig {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CloudRunConfig{}
	out.AutomaticTrafficControl = direct.LazyPtr(in.GetAutomaticTrafficControl())
	out.CanaryRevisionTags = in.CanaryRevisionTags
	out.PriorRevisionTags = in.PriorRevisionTags
	out.StableRevisionTags = in.StableRevisionTags
	return out
}
func CloudRunConfig_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CloudRunConfig) *pb.CloudRunConfig {
	if in == nil {
		return nil
	}
	out := &pb.CloudRunConfig{}
	out.AutomaticTrafficControl = direct.ValueOf(in.AutomaticTrafficControl)
	out.CanaryRevisionTags = in.CanaryRevisionTags
	out.PriorRevisionTags = in.PriorRevisionTags
	out.StableRevisionTags = in.StableRevisionTags
	return out
}
func CloudRunLocation_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CloudRunLocation) *krm.CloudRunLocation {
	if in == nil {
		return nil
	}
	out := &krm.CloudRunLocation{}
	out.Location = direct.LazyPtr(in.GetLocation())
	return out
}
func CloudRunLocation_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.CloudRunLocation) *pb.CloudRunLocation {
	if in == nil {
		return nil
	}
	out := &pb.CloudRunLocation{}
	out.Location = direct.ValueOf(in.Location)
	return out
}
func CustomCanaryDeployment_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CustomCanaryDeployment) *krmclouddeployv1beta1.CustomCanaryDeployment {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CustomCanaryDeployment{}
	out.PhaseConfigs = direct.Slice_FromProto(mapCtx, in.PhaseConfigs, CustomCanaryDeployment_PhaseConfig_v1beta1_FromProto)
	return out
}
func CustomCanaryDeployment_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CustomCanaryDeployment) *pb.CustomCanaryDeployment {
	if in == nil {
		return nil
	}
	out := &pb.CustomCanaryDeployment{}
	out.PhaseConfigs = direct.Slice_ToProto(mapCtx, in.PhaseConfigs, CustomCanaryDeployment_PhaseConfig_v1beta1_ToProto)
	return out
}
func CustomCanaryDeployment_PhaseConfig_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CustomCanaryDeployment_PhaseConfig) *krmclouddeployv1beta1.CustomCanaryDeployment_PhaseConfig {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CustomCanaryDeployment_PhaseConfig{}
	out.PhaseID = direct.LazyPtr(in.GetPhaseId())
	out.Percentage = direct.LazyPtr(in.GetPercentage())
	out.Profiles = in.Profiles
	out.Verify = direct.LazyPtr(in.GetVerify())
	out.Predeploy = Predeploy_v1beta1_FromProto(mapCtx, in.GetPredeploy())
	out.Postdeploy = Postdeploy_v1beta1_FromProto(mapCtx, in.GetPostdeploy())
	return out
}
func CustomCanaryDeployment_PhaseConfig_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CustomCanaryDeployment_PhaseConfig) *pb.CustomCanaryDeployment_PhaseConfig {
	if in == nil {
		return nil
	}
	out := &pb.CustomCanaryDeployment_PhaseConfig{}
	out.PhaseId = direct.ValueOf(in.PhaseID)
	out.Percentage = direct.ValueOf(in.Percentage)
	out.Profiles = in.Profiles
	out.Verify = direct.ValueOf(in.Verify)
	out.Predeploy = Predeploy_v1beta1_ToProto(mapCtx, in.Predeploy)
	out.Postdeploy = Postdeploy_v1beta1_ToProto(mapCtx, in.Postdeploy)
	return out
}
func CustomTarget_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTarget) *krm.CustomTarget {
	if in == nil {
		return nil
	}
	out := &krm.CustomTarget{}
	if in.GetCustomTargetType() != "" {
		out.CustomTargetTypeRef = &krm.CustomTargetTypeRef{External: in.GetCustomTargetType()}
	}
	return out
}
func CustomTarget_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.CustomTarget) *pb.CustomTarget {
	if in == nil {
		return nil
	}
	out := &pb.CustomTarget{}
	if in.CustomTargetTypeRef != nil {
		out.CustomTargetType = in.CustomTargetTypeRef.External
	}
	return out
}
func CustomTargetSkaffoldActions_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetSkaffoldActions) *krm.CustomTargetSkaffoldActions {
	if in == nil {
		return nil
	}
	out := &krm.CustomTargetSkaffoldActions{}
	out.RenderAction = direct.LazyPtr(in.GetRenderAction())
	out.DeployAction = direct.LazyPtr(in.GetDeployAction())
	out.IncludeSkaffoldModules = direct.Slice_FromProto(mapCtx, in.IncludeSkaffoldModules, SkaffoldModules_v1alpha1_FromProto)
	return out
}
func CustomTargetSkaffoldActions_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.CustomTargetSkaffoldActions) *pb.CustomTargetSkaffoldActions {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetSkaffoldActions{}
	out.RenderAction = direct.ValueOf(in.RenderAction)
	out.DeployAction = direct.ValueOf(in.DeployAction)
	out.IncludeSkaffoldModules = direct.Slice_ToProto(mapCtx, in.IncludeSkaffoldModules, SkaffoldModules_v1alpha1_ToProto)
	return out
}
func CustomTargetTypeObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetType) *krm.CustomTargetTypeObservedState {
	if in == nil {
		return nil
	}
	out := &krm.CustomTargetTypeObservedState{}
	// MISSING: Name
	out.CustomTargetTypeID = direct.LazyPtr(in.GetCustomTargetTypeId())
	out.Uid = direct.LazyPtr(in.GetUid())
	// MISSING: Annotations
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Etag
	return out
}
func CustomTargetTypeObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.CustomTargetTypeObservedState) *pb.CustomTargetType {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetType{}
	// MISSING: Name
	out.CustomTargetTypeId = direct.ValueOf(in.CustomTargetTypeID)
	out.Uid = direct.ValueOf(in.Uid)
	// MISSING: Annotations
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Etag
	return out
}
func CustomTargetTypeSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetType) *krm.CustomTargetTypeSpec {
	if in == nil {
		return nil
	}
	out := &krm.CustomTargetTypeSpec{}
	// MISSING: Name
	out.Description = direct.LazyPtr(in.GetDescription())
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: Etag
	out.CustomActions = CustomTargetSkaffoldActions_v1alpha1_FromProto(mapCtx, in.GetCustomActions())
	return out
}
func CustomTargetTypeSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.CustomTargetTypeSpec) *pb.CustomTargetType {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetType{}
	// MISSING: Name
	out.Description = direct.ValueOf(in.Description)
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: Etag
	if oneof := CustomTargetSkaffoldActions_v1alpha1_ToProto(mapCtx, in.CustomActions); oneof != nil {
		out.Definition = &pb.CustomTargetType_CustomActions{CustomActions: oneof}
	}
	return out
}
func DefaultPool_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DefaultPool) *krm.DefaultPool {
	if in == nil {
		return nil
	}
	out := &krm.DefaultPool{}
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	return out
}
func DefaultPool_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.DefaultPool) *pb.DefaultPool {
	if in == nil {
		return nil
	}
	out := &pb.DefaultPool{}
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	return out
}
func DeliveryPipelineAttribute_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipelineAttribute) *krm.DeliveryPipelineAttribute {
	if in == nil {
		return nil
	}
	out := &krm.DeliveryPipelineAttribute{}
	out.ID = direct.LazyPtr(in.GetId())
	out.Labels = in.Labels
	return out
}
func DeliveryPipelineAttribute_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.DeliveryPipelineAttribute) *pb.DeliveryPipelineAttribute {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipelineAttribute{}
	out.Id = direct.ValueOf(in.ID)
	out.Labels = in.Labels
	return out
}
func DeliveryPipelineObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipeline) *krmclouddeployv1beta1.DeliveryPipelineObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.DeliveryPipelineObservedState{}
	// MISSING: Name
	out.Uid = direct.LazyPtr(in.GetUid())
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.Condition = PipelineCondition_v1beta1_FromProto(mapCtx, in.GetCondition())
	// MISSING: Etag
	return out
}
func DeliveryPipelineObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.DeliveryPipelineObservedState) *pb.DeliveryPipeline {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipeline{}
	// MISSING: Name
	out.Uid = direct.ValueOf(in.Uid)
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.Condition = PipelineCondition_v1beta1_ToProto(mapCtx, in.Condition)
	// MISSING: Etag
	return out
}
func DeliveryPipelineSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipeline) *krmclouddeployv1beta1.DeliveryPipelineSpec {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.DeliveryPipelineSpec{}
	// MISSING: Name
	out.Description = direct.LazyPtr(in.GetDescription())
	out.Annotations = in.Annotations
	// MISSING: Labels
	out.SerialPipeline = SerialPipeline_v1beta1_FromProto(mapCtx, in.GetSerialPipeline())
	// MISSING: Etag
	out.Suspended = direct.LazyPtr(in.GetSuspended())
	return out
}
func DeliveryPipelineSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.DeliveryPipelineSpec) *pb.DeliveryPipeline {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipeline{}
	// MISSING: Name
	out.Description = direct.ValueOf(in.Description)
	out.Annotations = in.Annotations
	// MISSING: Labels
	if oneof := SerialPipeline_v1beta1_ToProto(mapCtx, in.SerialPipeline); oneof != nil {
		out.Pipeline = &pb.DeliveryPipeline_SerialPipeline{SerialPipeline: oneof}
	}
	// MISSING: Etag
	out.Suspended = direct.ValueOf(in.Suspended)
	return out
}
func DeployParameters_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.DeployParameters) *krmclouddeployv1beta1.DeployParameters {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.DeployParameters{}
	out.Values = in.Values
	out.MatchTargetLabels = in.MatchTargetLabels
	return out
}
func DeployParameters_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.DeployParameters) *pb.DeployParameters {
	if in == nil {
		return nil
	}
	out := &pb.DeployParameters{}
	out.Values = in.Values
	out.MatchTargetLabels = in.MatchTargetLabels
	return out
}
func DeployPolicyObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicy) *krm.DeployPolicyObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DeployPolicyObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.Uid = direct.LazyPtr(in.GetUid())
	// MISSING: Annotations
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Etag
	return out
}
func DeployPolicyObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.DeployPolicyObservedState) *pb.DeployPolicy {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicy{}
	out.Name = direct.ValueOf(in.Name)
	out.Uid = direct.ValueOf(in.Uid)
	// MISSING: Annotations
	// MISSING: Labels
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Etag
	return out
}
func DeployPolicyResourceSelector_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicyResourceSelector) *krm.DeployPolicyResourceSelector {
	if in == nil {
		return nil
	}
	out := &krm.DeployPolicyResourceSelector{}
	out.DeliveryPipeline = DeliveryPipelineAttribute_v1alpha1_FromProto(mapCtx, in.GetDeliveryPipeline())
	out.Target = TargetAttribute_v1alpha1_FromProto(mapCtx, in.GetTarget())
	return out
}
func DeployPolicyResourceSelector_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.DeployPolicyResourceSelector) *pb.DeployPolicyResourceSelector {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicyResourceSelector{}
	out.DeliveryPipeline = DeliveryPipelineAttribute_v1alpha1_ToProto(mapCtx, in.DeliveryPipeline)
	out.Target = TargetAttribute_v1alpha1_ToProto(mapCtx, in.Target)
	return out
}
func DeployPolicySpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicy) *krm.DeployPolicySpec {
	if in == nil {
		return nil
	}
	out := &krm.DeployPolicySpec{}
	out.Description = direct.LazyPtr(in.GetDescription())
	// MISSING: Annotations
	// MISSING: Labels
	out.Suspended = direct.LazyPtr(in.GetSuspended())
	out.Selectors = direct.Slice_FromProto(mapCtx, in.Selectors, DeployPolicyResourceSelector_v1alpha1_FromProto)
	out.Rules = direct.Slice_FromProto(mapCtx, in.Rules, PolicyRule_v1alpha1_FromProto)
	// MISSING: Etag
	return out
}
func DeployPolicySpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.DeployPolicySpec) *pb.DeployPolicy {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicy{}
	out.Description = direct.ValueOf(in.Description)
	// MISSING: Annotations
	// MISSING: Labels
	out.Suspended = direct.ValueOf(in.Suspended)
	out.Selectors = direct.Slice_ToProto(mapCtx, in.Selectors, DeployPolicyResourceSelector_v1alpha1_ToProto)
	out.Rules = direct.Slice_ToProto(mapCtx, in.Rules, PolicyRule_v1alpha1_ToProto)
	// MISSING: Etag
	return out
}
func ExecutionConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExecutionConfig) *krm.ExecutionConfig {
	if in == nil {
		return nil
	}
	out := &krm.ExecutionConfig{}
	out.Usages = direct.EnumSlice_FromProto(mapCtx, in.Usages)
	out.DefaultPool = DefaultPool_v1alpha1_FromProto(mapCtx, in.GetDefaultPool())
	out.PrivatePool = PrivatePool_v1alpha1_FromProto(mapCtx, in.GetPrivatePool())
	if in.GetWorkerPool() != "" {
		out.WorkerPoolRef = &krmcloudbuildv1beta1.CloudBuildWorkerPoolRef{External: in.GetWorkerPool()}
	}
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	out.ExecutionTimeout = direct.StringDuration_FromProto(mapCtx, in.GetExecutionTimeout())
	out.Verbose = direct.LazyPtr(in.GetVerbose())
	return out
}
func ExecutionConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.ExecutionConfig) *pb.ExecutionConfig {
	if in == nil {
		return nil
	}
	out := &pb.ExecutionConfig{}
	out.Usages = direct.EnumSlice_ToProto[pb.ExecutionConfig_ExecutionEnvironmentUsage](mapCtx, in.Usages)
	if oneof := DefaultPool_v1alpha1_ToProto(mapCtx, in.DefaultPool); oneof != nil {
		out.ExecutionEnvironment = &pb.ExecutionConfig_DefaultPool{DefaultPool: oneof}
	}
	if oneof := PrivatePool_v1alpha1_ToProto(mapCtx, in.PrivatePool); oneof != nil {
		out.ExecutionEnvironment = &pb.ExecutionConfig_PrivatePool{PrivatePool: oneof}
	}
	if in.WorkerPoolRef != nil {
		out.WorkerPool = in.WorkerPoolRef.External
	}
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	out.ExecutionTimeout = direct.StringDuration_ToProto(mapCtx, in.ExecutionTimeout)
	out.Verbose = direct.ValueOf(in.Verbose)
	return out
}
func KubernetesConfig_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KubernetesConfig) *krmclouddeployv1beta1.KubernetesConfig {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.KubernetesConfig{}
	out.GatewayServiceMesh = KubernetesConfig_GatewayServiceMesh_v1beta1_FromProto(mapCtx, in.GetGatewayServiceMesh())
	out.ServiceNetworking = KubernetesConfig_ServiceNetworking_v1beta1_FromProto(mapCtx, in.GetServiceNetworking())
	return out
}
func KubernetesConfig_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.KubernetesConfig) *pb.KubernetesConfig {
	if in == nil {
		return nil
	}
	out := &pb.KubernetesConfig{}
	if oneof := KubernetesConfig_GatewayServiceMesh_v1beta1_ToProto(mapCtx, in.GatewayServiceMesh); oneof != nil {
		out.ServiceDefinition = &pb.KubernetesConfig_GatewayServiceMesh_{GatewayServiceMesh: oneof}
	}
	if oneof := KubernetesConfig_ServiceNetworking_v1beta1_ToProto(mapCtx, in.ServiceNetworking); oneof != nil {
		out.ServiceDefinition = &pb.KubernetesConfig_ServiceNetworking_{ServiceNetworking: oneof}
	}
	return out
}
func KubernetesConfig_GatewayServiceMesh_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KubernetesConfig_GatewayServiceMesh) *krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh{}
	out.HTTPRoute = direct.LazyPtr(in.GetHttpRoute())
	out.Service = direct.LazyPtr(in.GetService())
	out.Deployment = direct.LazyPtr(in.GetDeployment())
	out.RouteUpdateWaitTime = direct.StringDuration_FromProto(mapCtx, in.GetRouteUpdateWaitTime())
	out.StableCutbackDuration = direct.StringDuration_FromProto(mapCtx, in.GetStableCutbackDuration())
	out.PodSelectorLabel = direct.LazyPtr(in.GetPodSelectorLabel())
	out.RouteDestinations = KubernetesConfig_GatewayServiceMesh_RouteDestinations_v1beta1_FromProto(mapCtx, in.GetRouteDestinations())
	return out
}
func KubernetesConfig_GatewayServiceMesh_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh) *pb.KubernetesConfig_GatewayServiceMesh {
	if in == nil {
		return nil
	}
	out := &pb.KubernetesConfig_GatewayServiceMesh{}
	out.HttpRoute = direct.ValueOf(in.HTTPRoute)
	out.Service = direct.ValueOf(in.Service)
	out.Deployment = direct.ValueOf(in.Deployment)
	out.RouteUpdateWaitTime = direct.StringDuration_ToProto(mapCtx, in.RouteUpdateWaitTime)
	out.StableCutbackDuration = direct.StringDuration_ToProto(mapCtx, in.StableCutbackDuration)
	out.PodSelectorLabel = direct.ValueOf(in.PodSelectorLabel)
	out.RouteDestinations = KubernetesConfig_GatewayServiceMesh_RouteDestinations_v1beta1_ToProto(mapCtx, in.RouteDestinations)
	return out
}
func KubernetesConfig_GatewayServiceMesh_RouteDestinations_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KubernetesConfig_GatewayServiceMesh_RouteDestinations) *krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh_RouteDestinations {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh_RouteDestinations{}
	// MISSING: DestinationIds
	// (near miss): "DestinationIds" vs "DestinationIDs"
	out.PropagateService = direct.LazyPtr(in.GetPropagateService())
	return out
}
func KubernetesConfig_GatewayServiceMesh_RouteDestinations_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.KubernetesConfig_GatewayServiceMesh_RouteDestinations) *pb.KubernetesConfig_GatewayServiceMesh_RouteDestinations {
	if in == nil {
		return nil
	}
	out := &pb.KubernetesConfig_GatewayServiceMesh_RouteDestinations{}
	// MISSING: DestinationIds
	// (near miss): "DestinationIds" vs "DestinationIDs"
	out.PropagateService = direct.ValueOf(in.PropagateService)
	return out
}
func KubernetesConfig_ServiceNetworking_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KubernetesConfig_ServiceNetworking) *krmclouddeployv1beta1.KubernetesConfig_ServiceNetworking {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.KubernetesConfig_ServiceNetworking{}
	out.Service = direct.LazyPtr(in.GetService())
	out.Deployment = direct.LazyPtr(in.GetDeployment())
	out.DisablePodOverprovisioning = direct.LazyPtr(in.GetDisablePodOverprovisioning())
	out.PodSelectorLabel = direct.LazyPtr(in.GetPodSelectorLabel())
	return out
}
func KubernetesConfig_ServiceNetworking_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.KubernetesConfig_ServiceNetworking) *pb.KubernetesConfig_ServiceNetworking {
	if in == nil {
		return nil
	}
	out := &pb.KubernetesConfig_ServiceNetworking{}
	out.Service = direct.ValueOf(in.Service)
	out.Deployment = direct.ValueOf(in.Deployment)
	out.DisablePodOverprovisioning = direct.ValueOf(in.DisablePodOverprovisioning)
	out.PodSelectorLabel = direct.ValueOf(in.PodSelectorLabel)
	return out
}
func OneTimeWindow_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.OneTimeWindow) *krm.OneTimeWindow {
	if in == nil {
		return nil
	}
	out := &krm.OneTimeWindow{}
	out.StartDate = Date_v1alpha1_FromProto(mapCtx, in.GetStartDate())
	out.StartTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetStartTime())
	out.EndDate = Date_v1alpha1_FromProto(mapCtx, in.GetEndDate())
	out.EndTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetEndTime())
	return out
}
func OneTimeWindow_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.OneTimeWindow) *pb.OneTimeWindow {
	if in == nil {
		return nil
	}
	out := &pb.OneTimeWindow{}
	out.StartDate = Date_v1alpha1_ToProto(mapCtx, in.StartDate)
	out.StartTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.StartTime)
	out.EndDate = Date_v1alpha1_ToProto(mapCtx, in.EndDate)
	out.EndTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.EndTime)
	return out
}
func PipelineCondition_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.PipelineCondition) *krmclouddeployv1beta1.PipelineCondition {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.PipelineCondition{}
	out.PipelineReadyCondition = PipelineReadyCondition_v1beta1_FromProto(mapCtx, in.GetPipelineReadyCondition())
	out.TargetsPresentCondition = TargetsPresentCondition_v1beta1_FromProto(mapCtx, in.GetTargetsPresentCondition())
	out.TargetsTypeCondition = TargetsTypeCondition_v1beta1_FromProto(mapCtx, in.GetTargetsTypeCondition())
	return out
}
func PipelineCondition_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.PipelineCondition) *pb.PipelineCondition {
	if in == nil {
		return nil
	}
	out := &pb.PipelineCondition{}
	out.PipelineReadyCondition = PipelineReadyCondition_v1beta1_ToProto(mapCtx, in.PipelineReadyCondition)
	out.TargetsPresentCondition = TargetsPresentCondition_v1beta1_ToProto(mapCtx, in.TargetsPresentCondition)
	out.TargetsTypeCondition = TargetsTypeCondition_v1beta1_ToProto(mapCtx, in.TargetsTypeCondition)
	return out
}
func PipelineReadyCondition_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.PipelineReadyCondition) *krmclouddeployv1beta1.PipelineReadyCondition {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.PipelineReadyCondition{}
	out.Status = direct.LazyPtr(in.GetStatus())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	return out
}
func PipelineReadyCondition_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.PipelineReadyCondition) *pb.PipelineReadyCondition {
	if in == nil {
		return nil
	}
	out := &pb.PipelineReadyCondition{}
	out.Status = direct.ValueOf(in.Status)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func PolicyRule_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PolicyRule) *krm.PolicyRule {
	if in == nil {
		return nil
	}
	out := &krm.PolicyRule{}
	out.RolloutRestriction = RolloutRestriction_v1alpha1_FromProto(mapCtx, in.GetRolloutRestriction())
	return out
}
func PolicyRule_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.PolicyRule) *pb.PolicyRule {
	if in == nil {
		return nil
	}
	out := &pb.PolicyRule{}
	if oneof := RolloutRestriction_v1alpha1_ToProto(mapCtx, in.RolloutRestriction); oneof != nil {
		out.Rule = &pb.PolicyRule_RolloutRestriction{RolloutRestriction: oneof}
	}
	return out
}
func Postdeploy_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Postdeploy) *krmclouddeployv1beta1.Postdeploy {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Postdeploy{}
	out.Actions = in.Actions
	return out
}
func Postdeploy_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Postdeploy) *pb.Postdeploy {
	if in == nil {
		return nil
	}
	out := &pb.Postdeploy{}
	out.Actions = in.Actions
	return out
}
func Predeploy_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Predeploy) *krmclouddeployv1beta1.Predeploy {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Predeploy{}
	out.Actions = in.Actions
	return out
}
func Predeploy_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Predeploy) *pb.Predeploy {
	if in == nil {
		return nil
	}
	out := &pb.Predeploy{}
	out.Actions = in.Actions
	return out
}
func PrivatePool_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PrivatePool) *krm.PrivatePool {
	if in == nil {
		return nil
	}
	out := &krm.PrivatePool{}
	if in.GetWorkerPool() != "" {
		out.WorkerPoolRef = &krmcloudbuildv1beta1.CloudBuildWorkerPoolRef{External: in.GetWorkerPool()}
	}
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	return out
}
func PrivatePool_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.PrivatePool) *pb.PrivatePool {
	if in == nil {
		return nil
	}
	out := &pb.PrivatePool{}
	if in.WorkerPoolRef != nil {
		out.WorkerPool = in.WorkerPoolRef.External
	}
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	return out
}
func PromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.PromoteReleaseRuleObservedState) *pb.PromoteReleaseRule {
	if in == nil {
		return nil
	}
	out := &pb.PromoteReleaseRule{}
	// MISSING: ID
	// MISSING: Wait
	// MISSING: DestinationTargetID
	out.Condition = AutomationRuleCondition_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: DestinationPhase
	return out
}
func RepairRolloutRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.RepairRolloutRuleObservedState) *pb.RepairRolloutRule {
	if in == nil {
		return nil
	}
	out := &pb.RepairRolloutRule{}
	// MISSING: ID
	// MISSING: Phases
	// MISSING: Jobs
	out.Condition = AutomationRuleCondition_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: RepairPhases
	return out
}
func RolloutRestriction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.RolloutRestriction) *krm.RolloutRestriction {
	if in == nil {
		return nil
	}
	out := &krm.RolloutRestriction{}
	out.ID = direct.LazyPtr(in.GetId())
	out.Invokers = direct.EnumSlice_FromProto(mapCtx, in.Invokers)
	out.Actions = direct.EnumSlice_FromProto(mapCtx, in.Actions)
	out.TimeWindows = TimeWindows_v1alpha1_FromProto(mapCtx, in.GetTimeWindows())
	return out
}
func RolloutRestriction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.RolloutRestriction) *pb.RolloutRestriction {
	if in == nil {
		return nil
	}
	out := &pb.RolloutRestriction{}
	out.Id = direct.ValueOf(in.ID)
	out.Invokers = direct.EnumSlice_ToProto[pb.DeployPolicy_Invoker](mapCtx, in.Invokers)
	out.Actions = direct.EnumSlice_ToProto[pb.RolloutRestriction_RolloutActions](mapCtx, in.Actions)
	out.TimeWindows = TimeWindows_v1alpha1_ToProto(mapCtx, in.TimeWindows)
	return out
}
func RuntimeConfig_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.RuntimeConfig) *krmclouddeployv1beta1.RuntimeConfig {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.RuntimeConfig{}
	out.Kubernetes = KubernetesConfig_v1beta1_FromProto(mapCtx, in.GetKubernetes())
	out.CloudRun = CloudRunConfig_v1beta1_FromProto(mapCtx, in.GetCloudRun())
	return out
}
func RuntimeConfig_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.RuntimeConfig) *pb.RuntimeConfig {
	if in == nil {
		return nil
	}
	out := &pb.RuntimeConfig{}
	if oneof := KubernetesConfig_v1beta1_ToProto(mapCtx, in.Kubernetes); oneof != nil {
		out.RuntimeConfig = &pb.RuntimeConfig_Kubernetes{Kubernetes: oneof}
	}
	if oneof := CloudRunConfig_v1beta1_ToProto(mapCtx, in.CloudRun); oneof != nil {
		out.RuntimeConfig = &pb.RuntimeConfig_CloudRun{CloudRun: oneof}
	}
	return out
}
func SerialPipeline_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.SerialPipeline) *krmclouddeployv1beta1.SerialPipeline {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.SerialPipeline{}
	out.Stages = direct.Slice_FromProto(mapCtx, in.Stages, Stage_v1beta1_FromProto)
	return out
}
func SerialPipeline_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.SerialPipeline) *pb.SerialPipeline {
	if in == nil {
		return nil
	}
	out := &pb.SerialPipeline{}
	out.Stages = direct.Slice_ToProto(mapCtx, in.Stages, Stage_v1beta1_ToProto)
	return out
}
func SkaffoldModules_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules) *krm.SkaffoldModules {
	if in == nil {
		return nil
	}
	out := &krm.SkaffoldModules{}
	out.Configs = in.Configs
	out.Git = SkaffoldModules_SkaffoldGitSource_v1alpha1_FromProto(mapCtx, in.GetGit())
	out.GoogleCloudStorage = SkaffoldModules_SkaffoldGCSSource_v1alpha1_FromProto(mapCtx, in.GetGoogleCloudStorage())
	out.GoogleCloudBuildRepo = SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_FromProto(mapCtx, in.GetGoogleCloudBuildRepo())
	return out
}
func SkaffoldModules_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.SkaffoldModules) *pb.SkaffoldModules {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules{}
	out.Configs = in.Configs
	if oneof := SkaffoldModules_SkaffoldGitSource_v1alpha1_ToProto(mapCtx, in.Git); oneof != nil {
		out.Source = &pb.SkaffoldModules_Git{Git: oneof}
	}
	if oneof := SkaffoldModules_SkaffoldGCSSource_v1alpha1_ToProto(mapCtx, in.GoogleCloudStorage); oneof != nil {
		out.Source = &pb.SkaffoldModules_GoogleCloudStorage{GoogleCloudStorage: oneof}
	}
	if oneof := SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_ToProto(mapCtx, in.GoogleCloudBuildRepo); oneof != nil {
		out.Source = &pb.SkaffoldModules_GoogleCloudBuildRepo{GoogleCloudBuildRepo: oneof}
	}
	return out
}
func SkaffoldModules_SkaffoldGCSSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGCSSource) *krm.SkaffoldModules_SkaffoldGCSSource {
	if in == nil {
		return nil
	}
	out := &krm.SkaffoldModules_SkaffoldGCSSource{}
	out.Source = direct.LazyPtr(in.GetSource())
	out.Path = direct.LazyPtr(in.GetPath())
	return out
}
func SkaffoldModules_SkaffoldGCSSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.SkaffoldModules_SkaffoldGCSSource) *pb.SkaffoldModules_SkaffoldGCSSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGCSSource{}
	out.Source = direct.ValueOf(in.Source)
	out.Path = direct.ValueOf(in.Path)
	return out
}
func SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGCBRepoSource) *krm.SkaffoldModules_SkaffoldGcbRepoSource {
	if in == nil {
		return nil
	}
	out := &krm.SkaffoldModules_SkaffoldGcbRepoSource{}
	if in.GetRepository() != "" {
		out.RepositoryRef = &krmcloudbuildv1beta1.RepositoryRef{External: in.GetRepository()}
	}
	out.Path = direct.LazyPtr(in.GetPath())
	out.Ref = direct.LazyPtr(in.GetRef())
	return out
}
func SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.SkaffoldModules_SkaffoldGcbRepoSource) *pb.SkaffoldModules_SkaffoldGCBRepoSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGCBRepoSource{}
	if in.RepositoryRef != nil {
		out.Repository = in.RepositoryRef.External
	}
	out.Path = direct.ValueOf(in.Path)
	out.Ref = direct.ValueOf(in.Ref)
	return out
}
func SkaffoldModules_SkaffoldGitSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGitSource) *krm.SkaffoldModules_SkaffoldGitSource {
	if in == nil {
		return nil
	}
	out := &krm.SkaffoldModules_SkaffoldGitSource{}
	out.Repo = direct.LazyPtr(in.GetRepo())
	out.Path = direct.LazyPtr(in.GetPath())
	out.Ref = direct.LazyPtr(in.GetRef())
	return out
}
func SkaffoldModules_SkaffoldGitSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.SkaffoldModules_SkaffoldGitSource) *pb.SkaffoldModules_SkaffoldGitSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGitSource{}
	out.Repo = direct.ValueOf(in.Repo)
	out.Path = direct.ValueOf(in.Path)
	out.Ref = direct.ValueOf(in.Ref)
	return out
}
func Stage_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Stage) *krmclouddeployv1beta1.Stage {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Stage{}
	out.TargetID = direct.LazyPtr(in.GetTargetId())
	out.Profiles = in.Profiles
	out.Strategy = Strategy_v1beta1_FromProto(mapCtx, in.GetStrategy())
	out.DeployParameters = direct.Slice_FromProto(mapCtx, in.DeployParameters, DeployParameters_v1beta1_FromProto)
	return out
}
func Stage_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Stage) *pb.Stage {
	if in == nil {
		return nil
	}
	out := &pb.Stage{}
	out.TargetId = direct.ValueOf(in.TargetID)
	out.Profiles = in.Profiles
	out.Strategy = Strategy_v1beta1_ToProto(mapCtx, in.Strategy)
	out.DeployParameters = direct.Slice_ToProto(mapCtx, in.DeployParameters, DeployParameters_v1beta1_ToProto)
	return out
}
func Standard_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Standard) *krmclouddeployv1beta1.Standard {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Standard{}
	out.Verify = direct.LazyPtr(in.GetVerify())
	out.Predeploy = Predeploy_v1beta1_FromProto(mapCtx, in.GetPredeploy())
	out.Postdeploy = Postdeploy_v1beta1_FromProto(mapCtx, in.GetPostdeploy())
	return out
}
func Standard_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Standard) *pb.Standard {
	if in == nil {
		return nil
	}
	out := &pb.Standard{}
	out.Verify = direct.ValueOf(in.Verify)
	out.Predeploy = Predeploy_v1beta1_ToProto(mapCtx, in.Predeploy)
	out.Postdeploy = Postdeploy_v1beta1_ToProto(mapCtx, in.Postdeploy)
	return out
}
func Strategy_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Strategy) *krmclouddeployv1beta1.Strategy {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.Strategy{}
	out.Standard = Standard_v1beta1_FromProto(mapCtx, in.GetStandard())
	out.Canary = Canary_v1beta1_FromProto(mapCtx, in.GetCanary())
	return out
}
func Strategy_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.Strategy) *pb.Strategy {
	if in == nil {
		return nil
	}
	out := &pb.Strategy{}
	if oneof := Standard_v1beta1_ToProto(mapCtx, in.Standard); oneof != nil {
		out.DeploymentStrategy = &pb.Strategy_Standard{Standard: oneof}
	}
	if oneof := Canary_v1beta1_ToProto(mapCtx, in.Canary); oneof != nil {
		out.DeploymentStrategy = &pb.Strategy_Canary{Canary: oneof}
	}
	return out
}
func TargetsPresentCondition_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.TargetsPresentCondition) *pb.TargetsPresentCondition {
	if in == nil {
		return nil
	}
	out := &pb.TargetsPresentCondition{}
	out.Status = direct.ValueOf(in.Status)
	out.MissingTargets = in.MissingTargets
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func TargetsPresentCondition_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.TargetsPresentCondition) *krmclouddeployv1beta1.TargetsPresentCondition {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.TargetsPresentCondition{}
	out.Status = direct.LazyPtr(in.GetStatus())
	out.MissingTargets = in.MissingTargets
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	return out
}
func TargetsPresentCondition_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.TargetsPresentCondition) *pb.TargetsPresentCondition {
	if in == nil {
		return nil
	}
	out := &pb.TargetsPresentCondition{}
	out.Status = direct.ValueOf(in.Status)
	out.MissingTargets = in.MissingTargets
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func TargetsTypeCondition_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.TargetsTypeCondition) *krmclouddeployv1beta1.TargetsTypeCondition {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.TargetsTypeCondition{}
	out.Status = direct.LazyPtr(in.GetStatus())
	out.ErrorDetails = direct.LazyPtr(in.GetErrorDetails())
	return out
}
func TargetsTypeCondition_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.TargetsTypeCondition) *pb.TargetsTypeCondition {
	if in == nil {
		return nil
	}
	out := &pb.TargetsTypeCondition{}
	out.Status = direct.ValueOf(in.Status)
	out.ErrorDetails = direct.ValueOf(in.ErrorDetails)
	return out
}
func TimeWindows_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TimeWindows) *krm.TimeWindows {
	if in == nil {
		return nil
	}
	out := &krm.TimeWindows{}
	out.TimeZone = direct.LazyPtr(in.GetTimeZone())
	out.OneTimeWindows = direct.Slice_FromProto(mapCtx, in.OneTimeWindows, OneTimeWindow_v1alpha1_FromProto)
	out.WeeklyWindows = direct.Slice_FromProto(mapCtx, in.WeeklyWindows, WeeklyWindow_v1alpha1_FromProto)
	return out
}
func TimeWindows_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.TimeWindows) *pb.TimeWindows {
	if in == nil {
		return nil
	}
	out := &pb.TimeWindows{}
	out.TimeZone = direct.ValueOf(in.TimeZone)
	out.OneTimeWindows = direct.Slice_ToProto(mapCtx, in.OneTimeWindows, OneTimeWindow_v1alpha1_ToProto)
	out.WeeklyWindows = direct.Slice_ToProto(mapCtx, in.WeeklyWindows, WeeklyWindow_v1alpha1_ToProto)
	return out
}
func TimedPromoteReleaseCondition_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.TimedPromoteReleaseCondition) *pb.TimedPromoteReleaseCondition {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseCondition{}
	out.NextPromotionTime = direct.StringTimestamp_ToProto(mapCtx, in.NextPromotionTime)
	out.TargetsList = direct.Slice_ToProto(mapCtx, in.TargetsList, TimedPromoteReleaseCondition_Targets_v1alpha1_ToProto)
	return out
}
func TimedPromoteReleaseCondition_Targets_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.TimedPromoteReleaseCondition_Targets) *pb.TimedPromoteReleaseCondition_Targets {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseCondition_Targets{}
	out.SourceTargetId = direct.ValueOf(in.SourceTargetID)
	out.DestinationTargetId = direct.ValueOf(in.DestinationTargetID)
	return out
}
func TimedPromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.TimedPromoteReleaseRuleObservedState) *pb.TimedPromoteReleaseRule {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseRule{}
	// MISSING: ID
	// MISSING: DestinationTargetID
	// MISSING: Schedule
	// MISSING: TimeZone
	out.Condition = AutomationRuleCondition_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: DestinationPhase
	return out
}
func WeeklyWindow_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.WeeklyWindow) *krm.WeeklyWindow {
	if in == nil {
		return nil
	}
	out := &krm.WeeklyWindow{}
	out.DaysOfWeek = direct.EnumSlice_FromProto(mapCtx, in.DaysOfWeek)
	out.StartTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetEndTime())
	return out
}
func WeeklyWindow_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krm.WeeklyWindow) *pb.WeeklyWindow {
	if in == nil {
		return nil
	}
	out := &pb.WeeklyWindow{}
	out.DaysOfWeek = direct.EnumSlice_ToProto[dayofweekpb.DayOfWeek](mapCtx, in.DaysOfWeek)
	out.StartTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.StartTime)
	out.EndTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.EndTime)
	return out
}
