// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: aiplatform.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.aiplatform.v1

package vertexaihyperparametertuningjob

import (
	pb "cloud.google.com/go/aiplatform/apiv1beta1/aiplatformpb"
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/aiplatform/v1alpha1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func ContainerSpec_FromProto(mapCtx *direct.MapContext, in *pb.ContainerSpec) *krm.ContainerSpec {
	if in == nil {
		return nil
	}
	out := &krm.ContainerSpec{}
	out.ImageURI = direct.LazyPtr(in.GetImageUri())
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_FromProto(mapCtx, in.Env, EnvVar_FromProto)
	return out
}

func ContainerSpec_ToProto(mapCtx *direct.MapContext, in *krm.ContainerSpec) *pb.ContainerSpec {
	if in == nil {
		return nil
	}
	out := &pb.ContainerSpec{}
	out.ImageUri = direct.ValueOf(in.ImageURI)
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_ToProto(mapCtx, in.Env, EnvVar_ToProto)
	return out
}

func CustomJobSpec_FromProto(mapCtx *direct.MapContext, in *pb.CustomJobSpec) *krm.CustomJobSpec {
	if in == nil {
		return nil
	}
	out := &krm.CustomJobSpec{}
	out.PersistentResourceID = direct.LazyPtr(in.GetPersistentResourceId())
	out.WorkerPoolSpecs = direct.Slice_FromProto(mapCtx, in.WorkerPoolSpecs, WorkerPoolSpec_FromProto)
	out.Scheduling = Scheduling_FromProto(mapCtx, in.GetScheduling())
	out.ServiceAccount = direct.LazyPtr(in.GetServiceAccount())
	out.Network = direct.LazyPtr(in.GetNetwork())
	out.ReservedIPRanges = in.ReservedIpRanges
	out.PSCInterfaceConfig = PSCInterfaceConfig_FromProto(mapCtx, in.GetPscInterfaceConfig())
	out.BaseOutputDirectory = GCSDestination_FromProto(mapCtx, in.GetBaseOutputDirectory())
	out.ProtectedArtifactLocationID = direct.LazyPtr(in.GetProtectedArtifactLocationId())
	out.Tensorboard = direct.LazyPtr(in.GetTensorboard())
	out.EnableWebAccess = direct.LazyPtr(in.GetEnableWebAccess())
	out.EnableDashboardAccess = direct.LazyPtr(in.GetEnableDashboardAccess())
	out.Experiment = direct.LazyPtr(in.GetExperiment())
	out.ExperimentRun = direct.LazyPtr(in.GetExperimentRun())
	out.Models = in.Models
	return out
}

func CustomJobSpec_ToProto(mapCtx *direct.MapContext, in *krm.CustomJobSpec) *pb.CustomJobSpec {
	if in == nil {
		return nil
	}
	out := &pb.CustomJobSpec{}
	out.PersistentResourceId = direct.ValueOf(in.PersistentResourceID)
	out.WorkerPoolSpecs = direct.Slice_ToProto(mapCtx, in.WorkerPoolSpecs, WorkerPoolSpec_ToProto)
	out.Scheduling = Scheduling_ToProto(mapCtx, in.Scheduling)
	out.ServiceAccount = direct.ValueOf(in.ServiceAccount)
	out.Network = direct.ValueOf(in.Network)
	out.ReservedIpRanges = in.ReservedIPRanges
	out.PscInterfaceConfig = PSCInterfaceConfig_ToProto(mapCtx, in.PSCInterfaceConfig)
	out.BaseOutputDirectory = GCSDestination_ToProto(mapCtx, in.BaseOutputDirectory)
	out.ProtectedArtifactLocationId = direct.ValueOf(in.ProtectedArtifactLocationID)
	out.Tensorboard = direct.ValueOf(in.Tensorboard)
	out.EnableWebAccess = direct.ValueOf(in.EnableWebAccess)
	out.EnableDashboardAccess = direct.ValueOf(in.EnableDashboardAccess)
	out.Experiment = direct.ValueOf(in.Experiment)
	out.ExperimentRun = direct.ValueOf(in.ExperimentRun)
	out.Models = in.Models
	return out
}

func DNSPeeringConfig_FromProto(mapCtx *direct.MapContext, in *pb.DnsPeeringConfig) *krm.DNSPeeringConfig {
	if in == nil {
		return nil
	}
	out := &krm.DNSPeeringConfig{}
	out.Domain = direct.LazyPtr(in.GetDomain())
	out.TargetProject = direct.LazyPtr(in.GetTargetProject())
	out.TargetNetwork = direct.LazyPtr(in.GetTargetNetwork())
	return out
}

func DNSPeeringConfig_ToProto(mapCtx *direct.MapContext, in *krm.DNSPeeringConfig) *pb.DnsPeeringConfig {
	if in == nil {
		return nil
	}
	out := &pb.DnsPeeringConfig{}
	out.Domain = direct.ValueOf(in.Domain)
	out.TargetProject = direct.ValueOf(in.TargetProject)
	out.TargetNetwork = direct.ValueOf(in.TargetNetwork)
	return out
}

func DiskSpec_FromProto(mapCtx *direct.MapContext, in *pb.DiskSpec) *krm.DiskSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiskSpec{}
	out.BootDiskType = direct.LazyPtr(in.GetBootDiskType())
	out.BootDiskSizeGB = direct.LazyPtr(in.GetBootDiskSizeGb())
	return out
}

func DiskSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiskSpec) *pb.DiskSpec {
	if in == nil {
		return nil
	}
	out := &pb.DiskSpec{}
	out.BootDiskType = direct.ValueOf(in.BootDiskType)
	out.BootDiskSizeGb = direct.ValueOf(in.BootDiskSizeGB)
	return out
}

func EncryptionSpec_FromProto(mapCtx *direct.MapContext, in *pb.EncryptionSpec) *krm.EncryptionSpec {
	if in == nil {
		return nil
	}
	out := &krm.EncryptionSpec{}
	out.KMSKeyName = direct.LazyPtr(in.GetKmsKeyName())
	return out
}

func EncryptionSpec_ToProto(mapCtx *direct.MapContext, in *krm.EncryptionSpec) *pb.EncryptionSpec {
	if in == nil {
		return nil
	}
	out := &pb.EncryptionSpec{}
	out.KmsKeyName = direct.ValueOf(in.KMSKeyName)
	return out
}

func EnvVar_FromProto(mapCtx *direct.MapContext, in *pb.EnvVar) *krm.EnvVar {
	if in == nil {
		return nil
	}
	out := &krm.EnvVar{}
	out.Name = direct.LazyPtr(in.GetName())
	out.Value = direct.LazyPtr(in.GetValue())
	return out
}

func EnvVar_ToProto(mapCtx *direct.MapContext, in *krm.EnvVar) *pb.EnvVar {
	if in == nil {
		return nil
	}
	out := &pb.EnvVar{}
	out.Name = direct.ValueOf(in.Name)
	out.Value = direct.ValueOf(in.Value)
	return out
}

func GCSDestination_FromProto(mapCtx *direct.MapContext, in *pb.GcsDestination) *krm.GCSDestination {
	if in == nil {
		return nil
	}
	out := &krm.GCSDestination{}
	out.OutputURIPrefix = direct.LazyPtr(in.GetOutputUriPrefix())
	return out
}

func GCSDestination_ToProto(mapCtx *direct.MapContext, in *krm.GCSDestination) *pb.GcsDestination {
	if in == nil {
		return nil
	}
	out := &pb.GcsDestination{}
	out.OutputUriPrefix = direct.ValueOf(in.OutputURIPrefix)
	return out
}

func MachineSpec_FromProto(mapCtx *direct.MapContext, in *pb.MachineSpec) *krm.MachineSpec {
	if in == nil {
		return nil
	}
	out := &krm.MachineSpec{}
	out.MachineType = direct.LazyPtr(in.GetMachineType())
	out.AcceleratorType = direct.Enum_FromProto(mapCtx, in.GetAcceleratorType())
	out.AcceleratorCount = direct.LazyPtr(in.GetAcceleratorCount())
	out.TpuTopology = direct.LazyPtr(in.GetTpuTopology())
	out.ReservationAffinity = ReservationAffinity_FromProto(mapCtx, in.GetReservationAffinity())
	return out
}

func MachineSpec_ToProto(mapCtx *direct.MapContext, in *krm.MachineSpec) *pb.MachineSpec {
	if in == nil {
		return nil
	}
	out := &pb.MachineSpec{}
	out.MachineType = direct.ValueOf(in.MachineType)
	out.AcceleratorType = direct.Enum_ToProto[pb.AcceleratorType](mapCtx, in.AcceleratorType)
	out.AcceleratorCount = direct.ValueOf(in.AcceleratorCount)
	out.TpuTopology = direct.ValueOf(in.TpuTopology)
	out.ReservationAffinity = ReservationAffinity_ToProto(mapCtx, in.ReservationAffinity)
	return out
}

func MeasurementObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Measurement) *krm.MeasurementObservedState {
	if in == nil {
		return nil
	}
	out := &krm.MeasurementObservedState{}
	out.ElapsedDuration = direct.StringDuration_FromProto(mapCtx, in.GetElapsedDuration())
	out.StepCount = direct.LazyPtr(in.GetStepCount())
	out.Metrics = direct.Slice_FromProto(mapCtx, in.Metrics, Measurement_MetricObservedState_FromProto)
	return out
}

func MeasurementObservedState_ToProto(mapCtx *direct.MapContext, in *krm.MeasurementObservedState) *pb.Measurement {
	if in == nil {
		return nil
	}
	out := &pb.Measurement{}
	out.ElapsedDuration = direct.StringDuration_ToProto(mapCtx, in.ElapsedDuration)
	out.StepCount = direct.ValueOf(in.StepCount)
	out.Metrics = direct.Slice_ToProto(mapCtx, in.Metrics, Measurement_MetricObservedState_ToProto)
	return out
}

func Measurement_MetricObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Measurement_Metric) *krm.Measurement_MetricObservedState {
	if in == nil {
		return nil
	}
	out := &krm.Measurement_MetricObservedState{}
	out.MetricID = direct.LazyPtr(in.GetMetricId())
	out.Value = direct.LazyPtr(in.GetValue())
	return out
}

func Measurement_MetricObservedState_ToProto(mapCtx *direct.MapContext, in *krm.Measurement_MetricObservedState) *pb.Measurement_Metric {
	if in == nil {
		return nil
	}
	out := &pb.Measurement_Metric{}
	out.MetricId = direct.ValueOf(in.MetricID)
	out.Value = direct.ValueOf(in.Value)
	return out
}

func NfsMount_FromProto(mapCtx *direct.MapContext, in *pb.NfsMount) *krm.NfsMount {
	if in == nil {
		return nil
	}
	out := &krm.NfsMount{}
	out.Server = direct.LazyPtr(in.GetServer())
	out.Path = direct.LazyPtr(in.GetPath())
	out.MountPoint = direct.LazyPtr(in.GetMountPoint())
	return out
}

func NfsMount_ToProto(mapCtx *direct.MapContext, in *krm.NfsMount) *pb.NfsMount {
	if in == nil {
		return nil
	}
	out := &pb.NfsMount{}
	out.Server = direct.ValueOf(in.Server)
	out.Path = direct.ValueOf(in.Path)
	out.MountPoint = direct.ValueOf(in.MountPoint)
	return out
}

func PSCInterfaceConfig_FromProto(mapCtx *direct.MapContext, in *pb.PscInterfaceConfig) *krm.PSCInterfaceConfig {
	if in == nil {
		return nil
	}
	out := &krm.PSCInterfaceConfig{}
	out.NetworkAttachment = direct.LazyPtr(in.GetNetworkAttachment())
	out.DNSPeeringConfigs = direct.Slice_FromProto(mapCtx, in.DnsPeeringConfigs, DNSPeeringConfig_FromProto)
	return out
}

func PSCInterfaceConfig_ToProto(mapCtx *direct.MapContext, in *krm.PSCInterfaceConfig) *pb.PscInterfaceConfig {
	if in == nil {
		return nil
	}
	out := &pb.PscInterfaceConfig{}
	out.NetworkAttachment = direct.ValueOf(in.NetworkAttachment)
	out.DnsPeeringConfigs = direct.Slice_ToProto(mapCtx, in.DNSPeeringConfigs, DNSPeeringConfig_ToProto)
	return out
}

func PythonPackageSpec_FromProto(mapCtx *direct.MapContext, in *pb.PythonPackageSpec) *krm.PythonPackageSpec {
	if in == nil {
		return nil
	}
	out := &krm.PythonPackageSpec{}
	out.ExecutorImageURI = direct.LazyPtr(in.GetExecutorImageUri())
	out.PackageUris = in.PackageUris
	out.PythonModule = direct.LazyPtr(in.GetPythonModule())
	out.Args = in.Args
	out.Env = direct.Slice_FromProto(mapCtx, in.Env, EnvVar_FromProto)
	return out
}

func PythonPackageSpec_ToProto(mapCtx *direct.MapContext, in *krm.PythonPackageSpec) *pb.PythonPackageSpec {
	if in == nil {
		return nil
	}
	out := &pb.PythonPackageSpec{}
	out.ExecutorImageUri = direct.ValueOf(in.ExecutorImageURI)
	out.PackageUris = in.PackageUris
	out.PythonModule = direct.ValueOf(in.PythonModule)
	out.Args = in.Args
	out.Env = direct.Slice_ToProto(mapCtx, in.Env, EnvVar_ToProto)
	return out
}

func ReservationAffinity_FromProto(mapCtx *direct.MapContext, in *pb.ReservationAffinity) *krm.ReservationAffinity {
	if in == nil {
		return nil
	}
	out := &krm.ReservationAffinity{}
	out.ReservationAffinityType = direct.Enum_FromProto(mapCtx, in.GetReservationAffinityType())
	out.Key = direct.LazyPtr(in.GetKey())
	out.Values = in.Values
	return out
}

func ReservationAffinity_ToProto(mapCtx *direct.MapContext, in *krm.ReservationAffinity) *pb.ReservationAffinity {
	if in == nil {
		return nil
	}
	out := &pb.ReservationAffinity{}
	out.ReservationAffinityType = direct.Enum_ToProto[pb.ReservationAffinity_Type](mapCtx, in.ReservationAffinityType)
	out.Key = direct.ValueOf(in.Key)
	out.Values = in.Values
	return out
}

func Scheduling_FromProto(mapCtx *direct.MapContext, in *pb.Scheduling) *krm.Scheduling {
	if in == nil {
		return nil
	}
	out := &krm.Scheduling{}
	out.Timeout = direct.StringDuration_FromProto(mapCtx, in.GetTimeout())
	out.RestartJobOnWorkerRestart = direct.LazyPtr(in.GetRestartJobOnWorkerRestart())
	out.Strategy = direct.Enum_FromProto(mapCtx, in.GetStrategy())
	out.DisableRetries = direct.LazyPtr(in.GetDisableRetries())
	out.MaxWaitDuration = direct.StringDuration_FromProto(mapCtx, in.GetMaxWaitDuration())
	return out
}

func Scheduling_ToProto(mapCtx *direct.MapContext, in *krm.Scheduling) *pb.Scheduling {
	if in == nil {
		return nil
	}
	out := &pb.Scheduling{}
	out.Timeout = direct.StringDuration_ToProto(mapCtx, in.Timeout)
	out.RestartJobOnWorkerRestart = direct.ValueOf(in.RestartJobOnWorkerRestart)
	out.Strategy = direct.Enum_ToProto[pb.Scheduling_Strategy](mapCtx, in.Strategy)
	out.DisableRetries = direct.ValueOf(in.DisableRetries)
	out.MaxWaitDuration = direct.StringDuration_ToProto(mapCtx, in.MaxWaitDuration)
	return out
}

func StudySpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec) *krm.StudySpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec{}
	out.DecayCurveStoppingSpec = StudySpec_DecayCurveAutomatedStoppingSpec_FromProto(mapCtx, in.GetDecayCurveStoppingSpec())
	out.MedianAutomatedStoppingSpec = StudySpec_MedianAutomatedStoppingSpec_FromProto(mapCtx, in.GetMedianAutomatedStoppingSpec())
	out.ConvexAutomatedStoppingSpec = StudySpec_ConvexAutomatedStoppingSpec_FromProto(mapCtx, in.GetConvexAutomatedStoppingSpec())
	out.Metrics = direct.Slice_FromProto(mapCtx, in.Metrics, StudySpec_MetricSpec_FromProto)
	out.Parameters = direct.Slice_FromProto(mapCtx, in.Parameters, StudySpec_ParameterSpec_FromProto)
	out.Algorithm = direct.Enum_FromProto(mapCtx, in.GetAlgorithm())
	out.ObservationNoise = direct.Enum_FromProto(mapCtx, in.GetObservationNoise())
	out.MeasurementSelectionType = direct.Enum_FromProto(mapCtx, in.GetMeasurementSelectionType())
	out.StudyStoppingConfig = StudySpec_StudyStoppingConfig_FromProto(mapCtx, in.GetStudyStoppingConfig())
	return out
}

func StudySpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec) *pb.StudySpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec{}
	if oneof := StudySpec_DecayCurveAutomatedStoppingSpec_ToProto(mapCtx, in.DecayCurveStoppingSpec); oneof != nil {
		out.AutomatedStoppingSpec = &pb.StudySpec_DecayCurveStoppingSpec{DecayCurveStoppingSpec: oneof}
	}
	if oneof := StudySpec_MedianAutomatedStoppingSpec_ToProto(mapCtx, in.MedianAutomatedStoppingSpec); oneof != nil {
		out.AutomatedStoppingSpec = &pb.StudySpec_MedianAutomatedStoppingSpec_{MedianAutomatedStoppingSpec: oneof}
	}
	if oneof := StudySpec_ConvexAutomatedStoppingSpec_ToProto(mapCtx, in.ConvexAutomatedStoppingSpec); oneof != nil {
		out.AutomatedStoppingSpec = &pb.StudySpec_ConvexAutomatedStoppingSpec_{ConvexAutomatedStoppingSpec: oneof}
	}
	out.Metrics = direct.Slice_ToProto(mapCtx, in.Metrics, StudySpec_MetricSpec_ToProto)
	out.Parameters = direct.Slice_ToProto(mapCtx, in.Parameters, StudySpec_ParameterSpec_ToProto)
	out.Algorithm = direct.Enum_ToProto[pb.StudySpec_Algorithm](mapCtx, in.Algorithm)
	out.ObservationNoise = direct.Enum_ToProto[pb.StudySpec_ObservationNoise](mapCtx, in.ObservationNoise)
	out.MeasurementSelectionType = direct.Enum_ToProto[pb.StudySpec_MeasurementSelectionType](mapCtx, in.MeasurementSelectionType)
	out.StudyStoppingConfig = StudySpec_StudyStoppingConfig_ToProto(mapCtx, in.StudyStoppingConfig)
	return out
}

func StudySpec_ConvexAutomatedStoppingSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ConvexAutomatedStoppingSpec) *krm.StudySpec_ConvexAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ConvexAutomatedStoppingSpec{}
	out.MaxStepCount = direct.LazyPtr(in.GetMaxStepCount())
	out.MinStepCount = direct.LazyPtr(in.GetMinStepCount())
	out.MinMeasurementCount = direct.LazyPtr(in.GetMinMeasurementCount())
	out.LearningRateParameterName = direct.LazyPtr(in.GetLearningRateParameterName())
	out.UseElapsedDuration = direct.LazyPtr(in.GetUseElapsedDuration())
	out.UpdateAllStoppedTrials = in.UpdateAllStoppedTrials
	return out
}

func StudySpec_ConvexAutomatedStoppingSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ConvexAutomatedStoppingSpec) *pb.StudySpec_ConvexAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ConvexAutomatedStoppingSpec{}
	out.MaxStepCount = direct.ValueOf(in.MaxStepCount)
	out.MinStepCount = direct.ValueOf(in.MinStepCount)
	out.MinMeasurementCount = direct.ValueOf(in.MinMeasurementCount)
	out.LearningRateParameterName = direct.ValueOf(in.LearningRateParameterName)
	out.UseElapsedDuration = direct.ValueOf(in.UseElapsedDuration)
	out.UpdateAllStoppedTrials = in.UpdateAllStoppedTrials
	return out
}

func StudySpec_DecayCurveAutomatedStoppingSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_DecayCurveAutomatedStoppingSpec) *krm.StudySpec_DecayCurveAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_DecayCurveAutomatedStoppingSpec{}
	out.UseElapsedDuration = direct.LazyPtr(in.GetUseElapsedDuration())
	return out
}

func StudySpec_DecayCurveAutomatedStoppingSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_DecayCurveAutomatedStoppingSpec) *pb.StudySpec_DecayCurveAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_DecayCurveAutomatedStoppingSpec{}
	out.UseElapsedDuration = direct.ValueOf(in.UseElapsedDuration)
	return out
}

func StudySpec_MedianAutomatedStoppingSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_MedianAutomatedStoppingSpec) *krm.StudySpec_MedianAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_MedianAutomatedStoppingSpec{}
	out.UseElapsedDuration = direct.LazyPtr(in.GetUseElapsedDuration())
	return out
}

func StudySpec_MedianAutomatedStoppingSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_MedianAutomatedStoppingSpec) *pb.StudySpec_MedianAutomatedStoppingSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_MedianAutomatedStoppingSpec{}
	out.UseElapsedDuration = direct.ValueOf(in.UseElapsedDuration)
	return out
}

func StudySpec_MetricSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_MetricSpec) *krm.StudySpec_MetricSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_MetricSpec{}
	out.MetricID = direct.LazyPtr(in.GetMetricId())
	out.Goal = direct.Enum_FromProto(mapCtx, in.GetGoal())
	out.SafetyConfig = StudySpec_MetricSpec_SafetyMetricConfig_FromProto(mapCtx, in.GetSafetyConfig())
	return out
}

func StudySpec_MetricSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_MetricSpec) *pb.StudySpec_MetricSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_MetricSpec{}
	out.MetricId = direct.ValueOf(in.MetricID)
	out.Goal = direct.Enum_ToProto[pb.StudySpec_MetricSpec_GoalType](mapCtx, in.Goal)
	out.SafetyConfig = StudySpec_MetricSpec_SafetyMetricConfig_ToProto(mapCtx, in.SafetyConfig)
	return out
}

func StudySpec_MetricSpec_SafetyMetricConfig_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_MetricSpec_SafetyMetricConfig) *krm.StudySpec_MetricSpec_SafetyMetricConfig {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_MetricSpec_SafetyMetricConfig{}
	out.SafetyThreshold = direct.LazyPtr(in.GetSafetyThreshold())
	out.DesiredMinSafeTrialsFraction = in.DesiredMinSafeTrialsFraction
	return out
}

func StudySpec_MetricSpec_SafetyMetricConfig_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_MetricSpec_SafetyMetricConfig) *pb.StudySpec_MetricSpec_SafetyMetricConfig {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_MetricSpec_SafetyMetricConfig{}
	out.SafetyThreshold = direct.ValueOf(in.SafetyThreshold)
	out.DesiredMinSafeTrialsFraction = in.DesiredMinSafeTrialsFraction
	return out
}

func StudySpec_ParameterSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec) *krm.StudySpec_ParameterSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec{}
	out.DoubleValueSpec = StudySpec_ParameterSpec_DoubleValueSpec_FromProto(mapCtx, in.GetDoubleValueSpec())
	out.IntegerValueSpec = StudySpec_ParameterSpec_IntegerValueSpec_FromProto(mapCtx, in.GetIntegerValueSpec())
	out.CategoricalValueSpec = StudySpec_ParameterSpec_CategoricalValueSpec_FromProto(mapCtx, in.GetCategoricalValueSpec())
	out.DiscreteValueSpec = StudySpec_ParameterSpec_DiscreteValueSpec_FromProto(mapCtx, in.GetDiscreteValueSpec())
	out.ParameterID = direct.LazyPtr(in.GetParameterId())
	out.ScaleType = direct.Enum_FromProto(mapCtx, in.GetScaleType())
	out.ConditionalParameterSpecs = direct.Slice_FromProto(mapCtx, in.ConditionalParameterSpecs, StudySpec_ParameterSpec_ConditionalParameterSpec_FromProto)
	return out
}

func StudySpec_ParameterSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec) *pb.StudySpec_ParameterSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec{}
	if oneof := StudySpec_ParameterSpec_DoubleValueSpec_ToProto(mapCtx, in.DoubleValueSpec); oneof != nil {
		out.ParameterValueSpec = &pb.StudySpec_ParameterSpec_DoubleValueSpec_{DoubleValueSpec: oneof}
	}
	if oneof := StudySpec_ParameterSpec_IntegerValueSpec_ToProto(mapCtx, in.IntegerValueSpec); oneof != nil {
		out.ParameterValueSpec = &pb.StudySpec_ParameterSpec_IntegerValueSpec_{IntegerValueSpec: oneof}
	}
	if oneof := StudySpec_ParameterSpec_CategoricalValueSpec_ToProto(mapCtx, in.CategoricalValueSpec); oneof != nil {
		out.ParameterValueSpec = &pb.StudySpec_ParameterSpec_CategoricalValueSpec_{CategoricalValueSpec: oneof}
	}
	if oneof := StudySpec_ParameterSpec_DiscreteValueSpec_ToProto(mapCtx, in.DiscreteValueSpec); oneof != nil {
		out.ParameterValueSpec = &pb.StudySpec_ParameterSpec_DiscreteValueSpec_{DiscreteValueSpec: oneof}
	}
	out.ParameterId = direct.ValueOf(in.ParameterID)
	out.ScaleType = direct.Enum_ToProto[pb.StudySpec_ParameterSpec_ScaleType](mapCtx, in.ScaleType)
	out.ConditionalParameterSpecs = direct.Slice_ToProto(mapCtx, in.ConditionalParameterSpecs, StudySpec_ParameterSpec_ConditionalParameterSpec_ToProto)
	return out
}

func StudySpec_ParameterSpec_CategoricalValueSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_CategoricalValueSpec) *krm.StudySpec_ParameterSpec_CategoricalValueSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_CategoricalValueSpec{}
	out.Values = in.Values
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_CategoricalValueSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_CategoricalValueSpec) *pb.StudySpec_ParameterSpec_CategoricalValueSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_CategoricalValueSpec{}
	out.Values = in.Values
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_ConditionalParameterSpec) *krm.StudySpec_ParameterSpec_ConditionalParameterSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_ConditionalParameterSpec{}
	out.ParentDiscreteValues = StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition_FromProto(mapCtx, in.GetParentDiscreteValues())
	out.ParentIntValues = StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition_FromProto(mapCtx, in.GetParentIntValues())
	out.ParentCategoricalValues = StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition_FromProto(mapCtx, in.GetParentCategoricalValues())
	// MISSING: ParameterSpec
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_ConditionalParameterSpec) *pb.StudySpec_ParameterSpec_ConditionalParameterSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_ConditionalParameterSpec{}
	if oneof := StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition_ToProto(mapCtx, in.ParentDiscreteValues); oneof != nil {
		out.ParentValueCondition = &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_ParentDiscreteValues{ParentDiscreteValues: oneof}
	}
	if oneof := StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition_ToProto(mapCtx, in.ParentIntValues); oneof != nil {
		out.ParentValueCondition = &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_ParentIntValues{ParentIntValues: oneof}
	}
	if oneof := StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition_ToProto(mapCtx, in.ParentCategoricalValues); oneof != nil {
		out.ParentValueCondition = &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_ParentCategoricalValues{ParentCategoricalValues: oneof}
	}
	// MISSING: ParameterSpec
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition) *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition) *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_CategoricalValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition) *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition) *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_DiscreteValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition) *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition) *pb.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_ConditionalParameterSpec_IntValueCondition{}
	out.Values = in.Values
	return out
}

func StudySpec_ParameterSpec_DiscreteValueSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_DiscreteValueSpec) *krm.StudySpec_ParameterSpec_DiscreteValueSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_DiscreteValueSpec{}
	out.Values = in.Values
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_DiscreteValueSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_DiscreteValueSpec) *pb.StudySpec_ParameterSpec_DiscreteValueSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_DiscreteValueSpec{}
	out.Values = in.Values
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_DoubleValueSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_DoubleValueSpec) *krm.StudySpec_ParameterSpec_DoubleValueSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_DoubleValueSpec{}
	out.MinValue = direct.LazyPtr(in.GetMinValue())
	out.MaxValue = direct.LazyPtr(in.GetMaxValue())
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_DoubleValueSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_DoubleValueSpec) *pb.StudySpec_ParameterSpec_DoubleValueSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_DoubleValueSpec{}
	out.MinValue = direct.ValueOf(in.MinValue)
	out.MaxValue = direct.ValueOf(in.MaxValue)
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_IntegerValueSpec_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_ParameterSpec_IntegerValueSpec) *krm.StudySpec_ParameterSpec_IntegerValueSpec {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_ParameterSpec_IntegerValueSpec{}
	out.MinValue = direct.LazyPtr(in.GetMinValue())
	out.MaxValue = direct.LazyPtr(in.GetMaxValue())
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_ParameterSpec_IntegerValueSpec_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_ParameterSpec_IntegerValueSpec) *pb.StudySpec_ParameterSpec_IntegerValueSpec {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_ParameterSpec_IntegerValueSpec{}
	out.MinValue = direct.ValueOf(in.MinValue)
	out.MaxValue = direct.ValueOf(in.MaxValue)
	out.DefaultValue = in.DefaultValue
	return out
}

func StudySpec_StudyStoppingConfig_FromProto(mapCtx *direct.MapContext, in *pb.StudySpec_StudyStoppingConfig) *krm.StudySpec_StudyStoppingConfig {
	if in == nil {
		return nil
	}
	out := &krm.StudySpec_StudyStoppingConfig{}
	out.ShouldStopAsap = direct.BoolValue_FromProto(mapCtx, in.GetShouldStopAsap())
	out.MinimumRuntimeConstraint = StudyTimeConstraint_FromProto(mapCtx, in.GetMinimumRuntimeConstraint())
	out.MaximumRuntimeConstraint = StudyTimeConstraint_FromProto(mapCtx, in.GetMaximumRuntimeConstraint())
	out.MinNumTrials = Int32Value_FromProto(mapCtx, in.GetMinNumTrials())
	out.MaxNumTrials = Int32Value_FromProto(mapCtx, in.GetMaxNumTrials())
	out.MaxNumTrialsNoProgress = Int32Value_FromProto(mapCtx, in.GetMaxNumTrialsNoProgress())
	out.MaxDurationNoProgress = direct.StringDuration_FromProto(mapCtx, in.GetMaxDurationNoProgress())
	return out
}

func StudySpec_StudyStoppingConfig_ToProto(mapCtx *direct.MapContext, in *krm.StudySpec_StudyStoppingConfig) *pb.StudySpec_StudyStoppingConfig {
	if in == nil {
		return nil
	}
	out := &pb.StudySpec_StudyStoppingConfig{}
	out.ShouldStopAsap = direct.BoolValue_ToProto(mapCtx, in.ShouldStopAsap)
	out.MinimumRuntimeConstraint = StudyTimeConstraint_ToProto(mapCtx, in.MinimumRuntimeConstraint)
	out.MaximumRuntimeConstraint = StudyTimeConstraint_ToProto(mapCtx, in.MaximumRuntimeConstraint)
	out.MinNumTrials = Int32Value_ToProto(mapCtx, in.MinNumTrials)
	out.MaxNumTrials = Int32Value_ToProto(mapCtx, in.MaxNumTrials)
	out.MaxNumTrialsNoProgress = Int32Value_ToProto(mapCtx, in.MaxNumTrialsNoProgress)
	out.MaxDurationNoProgress = direct.StringDuration_ToProto(mapCtx, in.MaxDurationNoProgress)
	return out
}

func StudyTimeConstraint_FromProto(mapCtx *direct.MapContext, in *pb.StudyTimeConstraint) *krm.StudyTimeConstraint {
	if in == nil {
		return nil
	}
	out := &krm.StudyTimeConstraint{}
	out.MaxDuration = direct.StringDuration_FromProto(mapCtx, in.GetMaxDuration())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	return out
}

func StudyTimeConstraint_ToProto(mapCtx *direct.MapContext, in *krm.StudyTimeConstraint) *pb.StudyTimeConstraint {
	if in == nil {
		return nil
	}
	out := &pb.StudyTimeConstraint{}
	if oneof := direct.StringDuration_ToProto(mapCtx, in.MaxDuration); oneof != nil {
		out.Constraint = &pb.StudyTimeConstraint_MaxDuration{MaxDuration: oneof}
	}
	if oneof := direct.StringTimestamp_ToProto(mapCtx, in.EndTime); oneof != nil {
		out.Constraint = &pb.StudyTimeConstraint_EndTime{EndTime: oneof}
	}
	return out
}

func TrialObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Trial) *krm.TrialObservedState {
	if in == nil {
		return nil
	}
	out := &krm.TrialObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.ID = direct.LazyPtr(in.GetId())
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.Parameters = direct.Slice_FromProto(mapCtx, in.Parameters, Trial_ParameterObservedState_FromProto)
	out.FinalMeasurement = MeasurementObservedState_FromProto(mapCtx, in.GetFinalMeasurement())
	out.Measurements = direct.Slice_FromProto(mapCtx, in.Measurements, MeasurementObservedState_FromProto)
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	out.ClientID = direct.LazyPtr(in.GetClientId())
	out.InfeasibleReason = direct.LazyPtr(in.GetInfeasibleReason())
	out.CustomJob = direct.LazyPtr(in.GetCustomJob())
	out.WebAccessUris = in.WebAccessUris
	return out
}

func TrialObservedState_ToProto(mapCtx *direct.MapContext, in *krm.TrialObservedState) *pb.Trial {
	if in == nil {
		return nil
	}
	out := &pb.Trial{}
	out.Name = direct.ValueOf(in.Name)
	out.Id = direct.ValueOf(in.ID)
	out.State = direct.Enum_ToProto[pb.Trial_State](mapCtx, in.State)
	out.Parameters = direct.Slice_ToProto(mapCtx, in.Parameters, Trial_ParameterObservedState_ToProto)
	out.FinalMeasurement = MeasurementObservedState_ToProto(mapCtx, in.FinalMeasurement)
	out.Measurements = direct.Slice_ToProto(mapCtx, in.Measurements, MeasurementObservedState_ToProto)
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	out.ClientId = direct.ValueOf(in.ClientID)
	out.InfeasibleReason = direct.ValueOf(in.InfeasibleReason)
	out.CustomJob = direct.ValueOf(in.CustomJob)
	out.WebAccessUris = in.WebAccessUris
	return out
}

func Trial_ParameterObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Trial_Parameter) *krm.Trial_ParameterObservedState {
	if in == nil {
		return nil
	}
	out := &krm.Trial_ParameterObservedState{}
	out.ParameterID = direct.LazyPtr(in.GetParameterId())
	out.Value = Value_FromProto(mapCtx, in.GetValue())
	return out
}

func Trial_ParameterObservedState_ToProto(mapCtx *direct.MapContext, in *krm.Trial_ParameterObservedState) *pb.Trial_Parameter {
	if in == nil {
		return nil
	}
	out := &pb.Trial_Parameter{}
	out.ParameterId = direct.ValueOf(in.ParameterID)
	out.Value = Value_ToProto(mapCtx, in.Value)
	return out
}

func VertexAIHyperparameterTuningJobObservedState_FromProto(mapCtx *direct.MapContext, in *pb.HyperparameterTuningJob) *krm.VertexAIHyperparameterTuningJobObservedState {
	if in == nil {
		return nil
	}
	out := &krm.VertexAIHyperparameterTuningJobObservedState{}
	// MISSING: Name
	out.Trials = direct.Slice_FromProto(mapCtx, in.Trials, TrialObservedState_FromProto)
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.Error = direct.Status_FromProto(mapCtx, in.GetError())
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}

func VertexAIHyperparameterTuningJobObservedState_ToProto(mapCtx *direct.MapContext, in *krm.VertexAIHyperparameterTuningJobObservedState) *pb.HyperparameterTuningJob {
	if in == nil {
		return nil
	}
	out := &pb.HyperparameterTuningJob{}
	// MISSING: Name
	out.Trials = direct.Slice_ToProto(mapCtx, in.Trials, TrialObservedState_ToProto)
	out.State = direct.Enum_ToProto[pb.JobState](mapCtx, in.State)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.Error = direct.Status_ToProto(mapCtx, in.Error)
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}

func VertexAIHyperparameterTuningJobSpec_FromProto(mapCtx *direct.MapContext, in *pb.HyperparameterTuningJob) *krm.VertexAIHyperparameterTuningJobSpec {
	if in == nil {
		return nil
	}
	out := &krm.VertexAIHyperparameterTuningJobSpec{}
	// MISSING: Name
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.StudySpec = StudySpec_FromProto(mapCtx, in.GetStudySpec())
	out.MaxTrialCount = direct.LazyPtr(in.GetMaxTrialCount())
	out.ParallelTrialCount = direct.LazyPtr(in.GetParallelTrialCount())
	out.MaxFailedTrialCount = direct.LazyPtr(in.GetMaxFailedTrialCount())
	out.TrialJobSpec = CustomJobSpec_FromProto(mapCtx, in.GetTrialJobSpec())
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_FromProto(mapCtx, in.GetEncryptionSpec())
	return out
}

func VertexAIHyperparameterTuningJobSpec_ToProto(mapCtx *direct.MapContext, in *krm.VertexAIHyperparameterTuningJobSpec) *pb.HyperparameterTuningJob {
	if in == nil {
		return nil
	}
	out := &pb.HyperparameterTuningJob{}
	// MISSING: Name
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.StudySpec = StudySpec_ToProto(mapCtx, in.StudySpec)
	out.MaxTrialCount = direct.ValueOf(in.MaxTrialCount)
	out.ParallelTrialCount = direct.ValueOf(in.ParallelTrialCount)
	out.MaxFailedTrialCount = direct.ValueOf(in.MaxFailedTrialCount)
	out.TrialJobSpec = CustomJobSpec_ToProto(mapCtx, in.TrialJobSpec)
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_ToProto(mapCtx, in.EncryptionSpec)
	return out
}

func WorkerPoolSpec_FromProto(mapCtx *direct.MapContext, in *pb.WorkerPoolSpec) *krm.WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := &krm.WorkerPoolSpec{}
	out.ContainerSpec = ContainerSpec_FromProto(mapCtx, in.GetContainerSpec())
	out.PythonPackageSpec = PythonPackageSpec_FromProto(mapCtx, in.GetPythonPackageSpec())
	out.MachineSpec = MachineSpec_FromProto(mapCtx, in.GetMachineSpec())
	out.ReplicaCount = direct.LazyPtr(in.GetReplicaCount())
	out.NfsMounts = direct.Slice_FromProto(mapCtx, in.NfsMounts, NfsMount_FromProto)
	out.DiskSpec = DiskSpec_FromProto(mapCtx, in.GetDiskSpec())
	return out
}

func WorkerPoolSpec_ToProto(mapCtx *direct.MapContext, in *krm.WorkerPoolSpec) *pb.WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := &pb.WorkerPoolSpec{}
	if oneof := ContainerSpec_ToProto(mapCtx, in.ContainerSpec); oneof != nil {
		out.Task = &pb.WorkerPoolSpec_ContainerSpec{ContainerSpec: oneof}
	}
	if oneof := PythonPackageSpec_ToProto(mapCtx, in.PythonPackageSpec); oneof != nil {
		out.Task = &pb.WorkerPoolSpec_PythonPackageSpec{PythonPackageSpec: oneof}
	}
	out.MachineSpec = MachineSpec_ToProto(mapCtx, in.MachineSpec)
	out.ReplicaCount = direct.ValueOf(in.ReplicaCount)
	out.NfsMounts = direct.Slice_ToProto(mapCtx, in.NfsMounts, NfsMount_ToProto)
	out.DiskSpec = DiskSpec_ToProto(mapCtx, in.DiskSpec)
	return out
}
