#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/

if [[ -z "${ARTIFACTS:-}" ]]; then
  ARTIFACTS=$(pwd)/_artifacts/
fi
echo "Using ARTIFACTS=${ARTIFACTS}"
export ARTIFACTS

if [[ -z "${KUBEBUILDER_ASSETS:-}" ]]; then
  echo "Downloading envtest assets..."
  export KUBEBUILDER_ASSETS=$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use -p path)
fi

go test -v ./cmd/recorder -run TestProfileRecorderFootprint

if [[ -n "${GITHUB_ACTIONS:-}" ]]; then
  # Install graphviz for pprof -png output
  sudo apt-get update
  sudo apt-get install -y graphviz
fi

go tool pprof -top ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.prof | tee ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.top.txt
go tool pprof -pdf ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.prof > ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.pdf
go tool pprof -png ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.prof > ${ARTIFACTS}/pprof/TestProfileRecorderFootprint/heap.png
