#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/fuzz-roundtrippers' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

SHARD_SPEC="${1:-${SHARD_SPEC:-}}"

if [[ "${SHARD_SPEC}" =~ ([0-9]+)-of-([0-9]+)$ ]]; then
  SHARD_NUM="${BASH_REMATCH[1]}"
  TOTAL_SHARDS="${BASH_REMATCH[2]}"
  export FUZZ_SHARD_INDEX=$((SHARD_NUM - 1))
  export FUZZ_TOTAL_SHARDS="${TOTAL_SHARDS}"
  echo "Running fuzz-roundtrippers (shard ${SHARD_NUM} of ${TOTAL_SHARDS})..."
else
  echo "Running fuzz-roundtrippers..."
fi

go test -v ./pkg/fuzztesting/fuzztests/ -fuzz=FuzzAllMappers -parallel 2 -fuzztime 600s # fuzz for 10 minutes because we are fuzzing all the registered mappers

# Please do not add more fuzzers here; register them so they are run with FuzzAllMappers (or a similar approach)

