#!/usr/bin/env bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

export GOMEMLIMIT=2GiB # Avoid OOMs, particularly in github actions

go test -v ./pkg/fuzztesting/fuzztests/ -fuzz=FuzzAllMappers -fuzztime 600s # fuzz for 10 minutes because we are fuzzing all the registered mappers

# Please do not add more fuzzers here; register them so they are run with FuzzAllMappers (or a similar approach)
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEndpointAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEndpointAttachmentObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeEnvgroupAttachmentObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/ -fuzz=FuzzApigeeInstanceAttachmentObservedState -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/  -fuzz=FuzzEnvgroupAttachmentSpec -fuzztime 60s
go test -v ./pkg/controller/direct/apigee/  -fuzz=FuzzEnvgroupAttachmentObservedState -fuzztime 60s

go test -v ./pkg/controller/direct/cloudidentity -fuzz=FuzzCloudIdentityGroupSpec -fuzztime 60s
go test -v ./pkg/controller/direct/cloudidentity -fuzz=FuzzCloudIdentityGroupStatus -fuzztime 60s
go test -v ./pkg/controller/direct/cloudidentity -fuzz=FuzzCloudIdentityMembershipSpec -fuzztime 60s
go test -v ./pkg/controller/direct/cloudidentity -fuzz=FuzzCloudIdentityMembershipStatus -fuzztime 60s
