#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/$(basename "$0")' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/

. "${REPO_ROOT}/dev/tasks/setup-envtest"

echo "Prebuilding e2e tests..."
export PREBUILT_TEST_BINARY=${REPO_ROOT}/.build/tests-e2e
mkdir -p ${REPO_ROOT}/.build
if [[ ! -f "${PREBUILT_TEST_BINARY}" ]]; then
  time go test -c -o ${PREBUILT_TEST_BINARY} ./tests/e2e
fi

# Running direct and tracker tests
export KCC_RECONCILE_FLAG_GATE=USE_DEPENDENCY_TRACKER
export ONLY_TEST_APIGROUPS="iam.cnrm.cloud.google.com"

echo "Running sample iam tests with the gcptracker..."
${PREBUILT_TEST_BINARY} -test.run "^TestAllInSeries/samples$" -test.timeout 15m -test.v

echo "Running gcptracker scenarios tests..."
(cd tests/e2e && ${PREBUILT_TEST_BINARY} -test.run "^TestE2EScript/scenarios/tracker/tracker-iampartialpolicy$" -test.timeout 15m -test.v)