#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/$(basename "$0")' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/

# tests-e2e-fixtures is intended as a catch-all for any tests not covered by a tests-e2e-fixtures-* test
SKIP_TEST_APIGROUPS=(
    "accesscontextmanager.cnrm.cloud.google.com"
    "aiplatform.cnrm.cloud.google.com"
    "alloydb.cnrm.cloud.google.com"
    "analytics.cnrm.cloud.google.com"
    "apigateway.cnrm.cloud.google.com"
    "apigee.cnrm.cloud.google.com"
    "apikeys.cnrm.cloud.google.com"
    "appengine.cnrm.cloud.google.com"
    "apphub.cnrm.cloud.google.com"
    "artifactregistry.cnrm.cloud.google.com"
    "asset.cnrm.cloud.google.com"
    "assuredworkloads.cnrm.cloud.google.com"
    "backupdr.cnrm.cloud.google.com"
    "batch.cnrm.cloud.google.com"
    "beyondcorp.cnrm.cloud.google.com"
    "bigquery.cnrm.cloud.google.com"
    "bigqueryanalyticshub.cnrm.cloud.google.com"
    "bigquerybiglake.cnrm.cloud.google.com"
    "bigqueryconnection.cnrm.cloud.google.com"
    "bigquerydatapolicy.cnrm.cloud.google.com"
    "bigquerydatatransfer.cnrm.cloud.google.com"
    "bigqueryreservation.cnrm.cloud.google.com"
    "bigtable.cnrm.cloud.google.com"
    "billing.cnrm.cloud.google.com"
    "billingbudgets.cnrm.cloud.google.com"
    "binaryauthorization.cnrm.cloud.google.com"
    "blockchainnodeengine.cnrm.cloud.google.com"
    "certificatemanager.cnrm.cloud.google.com"
    "cloudasset.cnrm.cloud.google.com"
    "cloudbuild.cnrm.cloud.google.com"
    "clouddeploy.cnrm.cloud.google.com"
    "clouddms.cnrm.cloud.google.com"
    "cloudfunctions.cnrm.cloud.google.com"
    "cloudfunctions2.cnrm.cloud.google.com"
    "cloudidentity.cnrm.cloud.google.com"
    "cloudids.cnrm.cloud.google.com"
    "cloudiot.cnrm.cloud.google.com"
    "cloudquota.cnrm.cloud.google.com"
    "cloudscheduler.cnrm.cloud.google.com"
    "cloudtasks.cnrm.cloud.google.com"
    "colab.cnrm.cloud.google.com"
    "composer.cnrm.cloud.google.com"
    "compute.cnrm.cloud.google.com"
    "configcontroller.cnrm.cloud.google.com"
    "configdelivery.cnrm.cloud.google.com"
    "container.cnrm.cloud.google.com"
    "containeranalysis.cnrm.cloud.google.com"
    "containerattached.cnrm.cloud.google.com"
    "datacatalog.cnrm.cloud.google.com"
    "dataflow.cnrm.cloud.google.com"
    "dataform.cnrm.cloud.google.com"
    "datafusion.cnrm.cloud.google.com"
    "dataplex.cnrm.cloud.google.com"
    "dataproc.cnrm.cloud.google.com"
    "datastore.cnrm.cloud.google.com"
    "datastream.cnrm.cloud.google.com"
    "deploymentmanager.cnrm.cloud.google.com"
    "dialogflow.cnrm.cloud.google.com"
    "dialogflowcx.cnrm.cloud.google.com"
    "discoveryengine.cnrm.cloud.google.com"
    "dlp.cnrm.cloud.google.com"
    "dns.cnrm.cloud.google.com"
    "documentai.cnrm.cloud.google.com"
    "edgecontainer.cnrm.cloud.google.com"
    "edgenetwork.cnrm.cloud.google.com"
    "essentialcontacts.cnrm.cloud.google.com"
    "eventarc.cnrm.cloud.google.com"
    "filestore.cnrm.cloud.google.com"
    "firebase.cnrm.cloud.google.com"
    "firebasedatabase.cnrm.cloud.google.com"
    "firebasehosting.cnrm.cloud.google.com"
    "firebasestorage.cnrm.cloud.google.com"
    "firestore.cnrm.cloud.google.com"
    "gkebackup.cnrm.cloud.google.com"
    "gkehub.cnrm.cloud.google.com"
    "healthcare.cnrm.cloud.google.com"
    "iam.cnrm.cloud.google.com"
    "iap.cnrm.cloud.google.com"
    "identityplatform.cnrm.cloud.google.com"
    "kms.cnrm.cloud.google.com"
    "logging.cnrm.cloud.google.com"
    "managedkafka.cnrm.cloud.google.com"
    "memcache.cnrm.cloud.google.com"
    "memorystore.cnrm.cloud.google.com"
    "metastore.cnrm.cloud.google.com"
    "mlengine.cnrm.cloud.google.com"
    "monitoring.cnrm.cloud.google.com"
    "netapp.cnrm.cloud.google.com"
    "networkconnectivity.cnrm.cloud.google.com"
    "networkmanagement.cnrm.cloud.google.com"
    "networksecurity.cnrm.cloud.google.com"
    "networkservices.cnrm.cloud.google.com"
    "notebooks.cnrm.cloud.google.com"
    "orgpolicy.cnrm.cloud.google.com"
    "osconfig.cnrm.cloud.google.com"
    "oslogin.cnrm.cloud.google.com"
    "parametermanager.cnrm.cloud.google.com"
    "privateca.cnrm.cloud.google.com"
    "privilegedaccessmanager.cnrm.cloud.google.com"
    "pubsub.cnrm.cloud.google.com"
    "pubsublite.cnrm.cloud.google.com"
    "recaptchaenterprise.cnrm.cloud.google.com"
    "redis.cnrm.cloud.google.com"
    "resourcemanager.cnrm.cloud.google.com"
    "run.cnrm.cloud.google.com"
    "secretmanager.cnrm.cloud.google.com"
    "securesourcemanager.cnrm.cloud.google.com"
    "securitycenter.cnrm.cloud.google.com"
    "servicedirectory.cnrm.cloud.google.com"
    "servicenetworking.cnrm.cloud.google.com"
    "serviceusage.cnrm.cloud.google.com"
    "sourcerepo.cnrm.cloud.google.com"
    "spanner.cnrm.cloud.google.com"
    "speech.cnrm.cloud.google.com"
    "sql.cnrm.cloud.google.com"
    "storage.cnrm.cloud.google.com"
    "storagetransfer.cnrm.cloud.google.com"
    "tags.cnrm.cloud.google.com"
    "tpu.cnrm.cloud.google.com"
    "vertexai.cnrm.cloud.google.com"
    "vmwareengine.cnrm.cloud.google.com"
    "vpcaccess.cnrm.cloud.google.com"
    "workflowexecutions.cnrm.cloud.google.com"
    "workflows.cnrm.cloud.google.com"
    "workstations.cnrm.cloud.google.com"
)

export SKIP_TEST_APIGROUP=$(IFS=, ; echo "${SKIP_TEST_APIGROUPS[*]}")
${REPO_ROOT}/dev/tasks/run-e2e