#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/$(basename "$0")' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}/

. ${REPO_ROOT}/dev/tasks/setup-envtest

# Always write golden output
export WRITE_GOLDEN_OUTPUT=1

# Flag gate for gcptracker usage
export KCC_RECONCILE_FLAG_GATE=USE_DEPENDENCY_TRACKER

export USE_FULL_TEST_NAMES=true
export TEST_TIMEOUT=15m

echo "Prebuilding e2e tests..."
export PREBUILT_TEST_BINARY=${REPO_ROOT}/.build/tests-e2e
mkdir -p ${REPO_ROOT}/.build
time go test -c -o ${PREBUILT_TEST_BINARY} ./tests/e2e

echo "Building paralleltestrunner..."
time go build -o ${REPO_ROOT}/.build/paralleltestrunner ${REPO_ROOT}/dev/tools/paralleltestrunner

echo "Running scenario tests for gcptracker..."
GOLDEN_REQUEST_CHECKS=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock RUN_E2E=1 \
  ${PREBUILT_TEST_BINARY} -test.count=1 -test.timeout=600s -test.v -test.run '^TestE2EScript/scenarios/tracker/tracker-iampartialpolicy$'

echo "Running fixture and sample iam tests with the gcptracker in parallel..."
${REPO_ROOT}/.build/paralleltestrunner \
    -list-file="${REPO_ROOT}/tests/e2e/testdata/samples-iam-list.txt" \
    -base-test="TestAllInSeries/samples" \
    -- ${REPO_ROOT}/dev/tasks/run-e2e