#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

cd ${REPO_ROOT}/

echo "Downloading envtest assets..."
export KUBEBUILDER_ASSETS=$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.22 use -p path)

SKIP_TEST_APIGROUPS=(
    "alloydb.cnrm.cloud.google.com"
    "apigateway.cnrm.cloud.google.com"
    "apigee.cnrm.cloud.google.com"
    "bigquery.cnrm.cloud.google.com"
    "bigqueryconnection.cnrm.cloud.google.com"
    "bigquerydatapolicy.cnrm.cloud.google.com"
    "bigquerydatatransfer.cnrm.cloud.google.com"
    "cloudbuild.cnrm.cloud.google.com"
    "cloudidentity.cnrm.cloud.google.com"
    "compute.cnrm.cloud.google.com"
    "dataflow.cnrm.cloud.google.com"
    "dataproc.cnrm.cloud.google.com"
    "gkehub.cnrm.cloud.google.com"
    "iam.cnrm.cloud.google.com"
    "kms.cnrm.cloud.google.com"
    "orgpolicy.cnrm.cloud.google.com"
    "redis.cnrm.cloud.google.com"
    "secretmanager.cnrm.cloud.google.com"
    "spanner.cnrm.cloud.google.com"
    "sql.cnrm.cloud.google.com"
    "storage.cnrm.cloud.google.com"
    "workstations.cnrm.cloud.google.com"
)

export RUN_TESTS=TestAllInSeries/samples
# The env var 'KCC_ENG_GROUP_EMAIL' needs to be set to unblock sample
# 'folder-level-entitlement'.
export MOCK_GROUP_EMAIL="test@group.com"
export SKIP_TEST_APIGROUP=$(IFS=, ; echo "${SKIP_TEST_APIGROUPS[*]}")
export TEST_TIMEOUT=1h30m

echo "Running samples in tests/e2e..."
${REPO_ROOT}/dev/tasks/run-e2e
