#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/$(basename "$0")' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}/"

. "${REPO_ROOT}/dev/tasks/setup-envtest"

export USE_FULL_TEST_NAMES=true
export TEST_TIMEOUT=15m

echo "Prebuilding e2e tests..."
export PREBUILT_TEST_BINARY=${REPO_ROOT}/.build/tests-e2e
mkdir -p ${REPO_ROOT}/.build
if [[ ! -f "${PREBUILT_TEST_BINARY}" ]]; then
  time go test -c -o ${PREBUILT_TEST_BINARY} ./tests/e2e
fi

echo "Running reconcileintervalannotations tests sequentially..."
RUN_E2E=1 GOLDEN_REQUEST_CHECKS=1 E2E_GCP_TARGET=mock ${PREBUILT_TEST_BINARY} -test.run "^TestAllInSeries/reconcileintervalannotations-fixtures$" -test.timeout 15m -test.v
