#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/tests-preview' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

. ${REPO_ROOT}/dev/tasks/install-gcloud
. ${REPO_ROOT}/dev/tasks/setup-envtest

echo "Running preview CLI tests..."
# Configure isolated gcloud configuration directory with dummy project ID to avoid ECP / token refresh errors on GCE workstations
export CLOUDSDK_CONFIG=$(mktemp -d)
mkdir -p "${CLOUDSDK_CONFIG}/configurations"
echo -e "[core]\nproject = foobar" > "${CLOUDSDK_CONFIG}/configurations/config_default"


go test -test.count=1 -v ./pkg/cli/preview/...
