#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'dev/ci/presubmits/unit-tests' to fix.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd ${REPO_ROOT}

. ${REPO_ROOT}/dev/tasks/install-gcloud
. ${REPO_ROOT}/dev/tasks/setup-envtest

echo "Running unit tests..."
# A dummy default project id is required for a few unit test cases
gcloud config set project foobar --quiet

# Env var VALIDATE_URLS needs to be unset to avoid calling URLs in TestReferenceDocConsistency under scripts/generate-google3-docs/.
unset VALIDATE_URLS

# Get all unit test packages excluding the operator, E2E tests, and preview CLI tests
UNIT_TEST_PACKAGES=$(go list ./... | grep -v "/operator" | grep -v "tests/e2e" | grep -v "pkg/cli/preview")

if [ -z ${GITHUB_ACTION+x} ]; then
    go test -timeout 20m -test.count=1 -v ${UNIT_TEST_PACKAGES}
else
    # Output a keep-alive message every minute to prevent GitHub Actions from timing out
    # due to no output during long compilation phases.
    while true; do echo "Still compiling/running tests..."; sleep 60; done >&2 &
    KEEPALIVE_PID=$!
    set +e
    go test -timeout 20m -test.count=1 -v ${UNIT_TEST_PACKAGES}
    TEST_EXIT_CODE=$?
    set -e
    kill $KEEPALIVE_PID || true
    if [ $TEST_EXIT_CODE -ne 0 ]; then
        exit $TEST_EXIT_CODE
    fi
fi
