#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

function on_error() {
  echo "<hint_for_agent>Run 'make manifests' to update CRD manifests.</hint_for_agent>"
}
trap on_error ERR

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

make manifests

changed_files=$(git diff --name-only)
added_files=$(git ls-files --others --exclude-standard config/)
if [[ -n "${changed_files}" || -n "${added_files}" ]]; then
  echo "ERROR: Manifests must be regenerated. Please run 'make manifests' and update your PR."
  git diff
  git ls-files --others --exclude-standard config/
  exit 1
fi
