#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
VERSION=$(cat ${REPO_ROOT}/version/VERSION)

# Determine if we are on a release branch
# GITHUB_REF is set in GitHub Actions
REF=${GITHUB_REF:-$(git rev-parse --abbrev-ref HEAD)}
# GITHUB_BASE_REF is set for pull requests
BASE_REF=${GITHUB_BASE_REF:-}

if [[ "${REF}" == refs/heads/release-* ]] || [[ "${REF}" == release-* ]] || [[ "${BASE_REF}" == release-* ]]; then
  echo "Release branch detected (${REF}). Running release CRD verification for version ${VERSION}..."
  export VERSION=${VERSION}
  ./dev/tasks/verify-release-crds.sh
else
  echo "Not a release branch (REF=${REF}), skipping release CRD verification."
fi
