apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: networksecuritybackendauthenticationconfigs.networksecurity.cnrm.cloud.google.com
spec:
  group: networksecurity.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: NetworkSecurityBackendAuthenticationConfig
    listKind: NetworkSecurityBackendAuthenticationConfigList
    plural: networksecuritybackendauthenticationconfigs
    shortNames:
    - gcpnetworksecuritybackendauthenticationconfig
    - gcpnetworksecuritybackendauthenticationconfigs
    singular: networksecuritybackendauthenticationconfig
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NetworkSecurityBackendAuthenticationConfig is the Schema for
          the NetworkSecurityBackendAuthenticationConfig API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NetworkSecurityBackendAuthenticationConfigSpec defines the
              desired state of NetworkSecurityBackendAuthenticationConfig
            properties:
              clientCertificateRef:
                description: |-
                  Optional. A reference to a certificatemanager.googleapis.com.Certificate
                   resource. This is a relative resource path following the form
                   "projects/{project}/locations/{location}/certificates/{certificate}".

                   Used by a BackendService to negotiate mTLS when the backend connection uses
                   TLS and the backend requests a client certificate. Must have a CLIENT_AUTH
                   scope.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed CertificateManagerCertificate
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/certificates/{{certificate}}".
                    type: string
                  name:
                    description: The name of a CertificateManagerCertificate resource.
                    type: string
                  namespace:
                    description: The namespace of a CertificateManagerCertificate
                      resource.
                    type: string
                type: object
              description:
                description: Optional. Free-text description of the resource.
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Set of label tags associated with the resource.
                type: object
              location:
                description: The location of this resource.
                type: string
              projectRef:
                description: The project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              resourceID:
                description: The NetworkSecurityBackendAuthenticationConfig name.
                  If not given, the metadata.name will be used.
                type: string
              trustConfigRef:
                description: |-
                  Optional. A reference to a TrustConfig resource from the
                   certificatemanager.googleapis.com namespace. This is a relative resource
                   path following the form
                   "projects/{project}/locations/{location}/trustConfigs/{trust_config}".

                   A BackendService uses the chain of trust represented by this TrustConfig,
                   if specified, to validate the server certificates presented by the backend.
                   Required unless wellKnownRoots is set to PUBLIC_ROOTS.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed CertificateManagerTrustConfig
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/trustConfigs/{{trustConfig}}".
                    type: string
                  name:
                    description: The name of a CertificateManagerTrustConfig resource.
                    type: string
                  namespace:
                    description: The namespace of a CertificateManagerTrustConfig
                      resource.
                    type: string
                type: object
              wellKnownRoots:
                description: Well known roots to use for server certificate validation.
                enum:
                - WELL_KNOWN_ROOTS_UNSPECIFIED
                - NONE
                - PUBLIC_ROOTS
                type: string
            required:
            - projectRef
            type: object
          status:
            description: NetworkSecurityBackendAuthenticationConfigStatus defines
              the config connector machine state of NetworkSecurityBackendAuthenticationConfig
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the NetworkSecurityBackendAuthenticationConfig
                  resource in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  createTime:
                    description: Output only. The timestamp when the resource was
                      created.
                    type: string
                  etag:
                    description: Output only. Etag of the resource.
                    type: string
                  updateTime:
                    description: Output only. The timestamp when the resource was
                      updated.
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
