apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/stability-level: alpha
    cnrm.cloud.google.com/system: "true"
  name: networksecuritymirroringendpointgroups.networksecurity.cnrm.cloud.google.com
spec:
  group: networksecurity.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: NetworkSecurityMirroringEndpointGroup
    listKind: NetworkSecurityMirroringEndpointGroupList
    plural: networksecuritymirroringendpointgroups
    shortNames:
    - gcpnetworksecuritymirroringendpointgroup
    - gcpnetworksecuritymirroringendpointgroups
    singular: networksecuritymirroringendpointgroup
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NetworkSecurityMirroringEndpointGroup is the Schema for the NetworkSecurityMirroringEndpointGroup
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NetworkSecurityMirroringEndpointGroupSpec defines the desired
              state of NetworkSecurityMirroringEndpointGroup
            properties:
              description:
                description: Optional. User-provided description of the endpoint group.
                  Used as additional context for the endpoint group.
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Optional. Labels are key/value pairs that help to organize
                  and filter resources.
                type: object
              location:
                description: The location of this resource.
                type: string
              mirroringDeploymentGroupRef:
                description: 'Immutable. The deployment group that this DIRECT endpoint
                  group is connected to, for example: `projects/123456789/locations/global/mirroringDeploymentGroups/my-dg`.
                  See https://google.aip.dev/124.'
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed NetworkSecurityMirroringDeploymentGroup
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/mirroringDeploymentGroups/{{mirroringDeploymentGroupID}}".
                    type: string
                  name:
                    description: The name field of a NetworkSecurityMirroringDeploymentGroup
                      resource.
                    type: string
                  namespace:
                    description: The namespace field of a NetworkSecurityMirroringDeploymentGroup
                      resource.
                    type: string
                type: object
              projectRef:
                description: The project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              resourceID:
                description: The NetworkSecurityMirroringEndpointGroup name. If not
                  given, the metadata.name will be used.
                type: string
              type:
                description: Immutable. The type of the endpoint group. If left unspecified,
                  defaults to DIRECT.
                type: string
            required:
            - location
            - mirroringDeploymentGroupRef
            - projectRef
            type: object
          status:
            description: NetworkSecurityMirroringEndpointGroupStatus defines the config
              connector machine state of NetworkSecurityMirroringEndpointGroup
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the NetworkSecurityMirroringEndpointGroup
                  resource in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  associations:
                    description: Output only. List of associations to this endpoint
                      group.
                    items:
                      properties:
                        name:
                          description: 'Output only. The connected association''s
                            resource name, for example: `projects/123456789/locations/global/mirroringEndpointGroupAssociations/my-ega`.
                            See https://google.aip.dev/124.'
                          type: string
                        network:
                          description: 'Output only. The associated network, for example:
                            projects/123456789/global/networks/my-network. See https://google.aip.dev/124.'
                          type: string
                        state:
                          description: Output only. Most recent known state of the
                            association.
                          type: string
                      type: object
                    type: array
                  connectedDeploymentGroups:
                    description: Output only. List of details about the connected
                      deployment groups to this endpoint group.
                    items:
                      properties:
                        locations:
                          description: Output only. The list of locations where the
                            deployment group is present.
                          items:
                            properties:
                              location:
                                description: Output only. The cloud location, e.g.
                                  "us-central1-a" or "asia-south1".
                                type: string
                              state:
                                description: Output only. The current state of the
                                  association in this location.
                                type: string
                            type: object
                          type: array
                        name:
                          description: 'Output only. The connected deployment group''s
                            resource name, for example: `projects/123456789/locations/global/mirroringDeploymentGroups/my-dg`.
                            See https://google.aip.dev/124.'
                          type: string
                      type: object
                    type: array
                  createTime:
                    description: Output only. The timestamp when the resource was
                      created. See https://google.aip.dev/148#timestamps.
                    type: string
                  reconciling:
                    description: Output only. The current state of the resource does
                      not match the user's intended state, and the system is working
                      to reconcile them. This is part of the normal operation (e.g.
                      adding a new association to the group). See https://google.aip.dev/128.
                    type: boolean
                  state:
                    description: Output only. The current state of the endpoint group.
                      See https://google.aip.dev/216.
                    type: string
                  updateTime:
                    description: Output only. The timestamp when the resource was
                      most recently updated. See https://google.aip.dev/148#timestamps.
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
