apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/stability-level: stable
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: servicedirectoryendpoints.servicedirectory.cnrm.cloud.google.com
spec:
  group: servicedirectory.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ServiceDirectoryEndpoint
    listKind: ServiceDirectoryEndpointList
    plural: servicedirectoryendpoints
    shortNames:
    - gcpservicedirectoryendpoint
    - gcpservicedirectoryendpoints
    singular: servicedirectoryendpoint
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: ServiceDirectoryEndpoint is the Schema for the ServiceDirectoryEndpoint
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ServiceDirectoryEndpointSpec defines the desired state of
              ServiceDirectoryEndpoint
            properties:
              addressRef:
                description: Optional. The ComputeAddress resource whose IP address
                  this endpoint uses.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed ComputeAddress
                      resource. Should be in the format "projects/{{projectID}}/global/addresses/{{addressID}}"
                      or "projects/{{projectID}}/regions/{{region}}/addresses/{{addressID}}".
                    type: string
                  name:
                    description: The name of a ComputeAddress resource.
                    type: string
                  namespace:
                    description: The namespace of a ComputeAddress resource.
                    type: string
                type: object
              networkRef:
                description: Optional. The ComputeNetwork resource representing the
                  GCE network of this endpoint.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed ComputeNetwork
                      resource. Should be in the format "projects/{{projectID}}/global/networks/{{networkID}}".
                    type: string
                  name:
                    description: The name of a ComputeNetwork resource.
                    type: string
                  namespace:
                    description: The namespace of a ComputeNetwork resource.
                    type: string
                type: object
              port:
                description: Optional. Port that the endpoint is running on, must
                  be in the range of [0, 65535]. If unspecified, the default is 0.
                format: int32
                type: integer
              resourceID:
                description: Immutable. Optional. The endpointId of the resource.
                  Used for creation and acquisition. When unset, the value of `metadata.name`
                  is used as the default.
                type: string
              serviceRef:
                description: Required. The ServiceDirectoryService that this endpoint
                  belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed ServiceDirectoryService
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/namespaces/{{namespaceID}}/services/{{serviceID}}".
                    type: string
                  name:
                    description: The name of a ServiceDirectoryService resource.
                    type: string
                  namespace:
                    description: The namespace of a ServiceDirectoryService resource.
                    type: string
                type: object
            required:
            - serviceRef
            type: object
          status:
            description: ServiceDirectoryEndpointStatus defines the config connector
              machine state of ServiceDirectoryEndpoint
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              name:
                description: The resource name for the endpoint in the format 'projects/*/locations/*/namespaces/*/services/*/endpoints/*'.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
