// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1beta1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var ComputeExternalVPNGatewayGVK = GroupVersion.WithKind("ComputeExternalVPNGateway")

// ComputeExternalVPNGatewaySpec defines the desired state of ComputeExternalVPNGateway
// +kcc:spec:proto=google.cloud.compute.v1.ExternalVpnGateway
type ComputeExternalVPNGatewaySpec struct {
	// The project that this resource belongs to.
	ProjectRef *refsv1beta1.ProjectRef `json:"projectRef"`

	// The location of this resource.
	Location string `json:"location"`

	// The ComputeExternalVPNGateway name. If not given, the metadata.name will be used.
	ResourceID *string `json:"resourceID,omitempty"`

	// An optional description of this resource. Provide this property when you create the resource.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.description
	Description *string `json:"description,omitempty"`

	// A list of interfaces for this external VPN gateway. If your peer-side gateway is an on-premises gateway and non-AWS cloud providers' gateway, at most two interfaces can be provided for an external VPN gateway. If your peer side is an AWS virtual private gateway, four interfaces should be provided for an external VPN gateway.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.interfaces
	Interfaces []ExternalVPNGatewayInterface `json:"interfaces,omitempty"`

	// Labels for this resource. These can only be added or modified by the setLabels method. Each label key/value pair must comply with RFC1035. Label values may be empty.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Indicates the user-supplied redundancy type of this external VPN gateway.
	//  Check the RedundancyType enum for the list of possible values.
	// +kubebuilder:validation:Enum=FOUR_IPS_REDUNDANCY;SINGLE_IP_INTERNALLY_REDUNDANT;TWO_IPS_REDUNDANCY
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.redundancy_type
	RedundancyType *string `json:"redundancyType,omitempty"`
}

// ComputeExternalVPNGatewayStatus defines the config connector machine state of ComputeExternalVPNGateway
type ComputeExternalVPNGatewayStatus struct {
	/* Conditions represent the latest available observations of the
	   object's current state. */
	Conditions []v1alpha1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// A unique specifier for the ComputeExternalVPNGateway resource in GCP.
	ExternalRef *string `json:"externalRef,omitempty"`

	// ObservedState is the state of the resource as most recently observed in GCP.
	ObservedState *ComputeExternalVPNGatewayObservedState `json:"observedState,omitempty"`
}

// ComputeExternalVPNGatewayObservedState is the state of the ComputeExternalVPNGateway resource as most recently observed in GCP.
// +kcc:observedstate:proto=google.cloud.compute.v1.ExternalVpnGateway
type ComputeExternalVPNGatewayObservedState struct {
	// [Output Only] Creation timestamp in RFC3339 text format.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.creation_timestamp
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`

	// [Output Only] The unique identifier for the resource. This identifier is defined by the server.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.id
	ID *uint64 `json:"id,omitempty"`

	// [Output Only] Type of the resource. Always compute#externalVpnGateway for externalVpnGateways.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.kind
	Kind *string `json:"kind,omitempty"`

	// A fingerprint for the labels being applied to this ExternalVpnGateway, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error 412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve an ExternalVpnGateway.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.label_fingerprint
	LabelFingerprint *string `json:"labelFingerprint,omitempty"`

	// [Output Only] Server-defined URL for the resource.
	// +kcc:proto:field=google.cloud.compute.v1.ExternalVpnGateway.self_link
	SelfLink *string `json:"selfLink,omitempty"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories=gcp,shortName=gcpcomputeexternalvpngateway;gcpcomputeexternalvpngateways
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/managed-by-kcc=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/stability-level=stable"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/system=true"
// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type="date"
// +kubebuilder:printcolumn:name="Ready",JSONPath=".status.conditions[?(@.type=='Ready')].status",type="string",description="When 'True', the most recent reconcile of the resource succeeded"
// +kubebuilder:printcolumn:name="Status",JSONPath=".status.conditions[?(@.type=='Ready')].reason",type="string",description="The reason for the value in 'Ready'"
// +kubebuilder:printcolumn:name="Status Age",JSONPath=".status.conditions[?(@.type=='Ready')].lastTransitionTime",type="date",description="The last transition time for the value in 'Status'"

// ComputeExternalVPNGateway is the Schema for the ComputeExternalVPNGateway API
// +k8s:openapi-gen=true
type ComputeExternalVPNGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required
	Spec   ComputeExternalVPNGatewaySpec   `json:"spec,omitempty"`
	Status ComputeExternalVPNGatewayStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// ComputeExternalVPNGatewayList contains a list of ComputeExternalVPNGateway
type ComputeExternalVPNGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ComputeExternalVPNGateway `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ComputeExternalVPNGateway{}, &ComputeExternalVPNGatewayList{})
}
