// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: discoveryengine.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.discoveryengine.v1

package discoveryengine

import (
	pb "cloud.google.com/go/discoveryengine/apiv1/discoveryenginepb"
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/discoveryengine/v1alpha1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func CmekConfig_FromProto(mapCtx *direct.MapContext, in *pb.CmekConfig) *krm.CmekConfig {
	if in == nil {
		return nil
	}
	out := &krm.CmekConfig{}
	out.Name = direct.LazyPtr(in.GetName())
	out.KMSKey = direct.LazyPtr(in.GetKmsKey())
	out.KMSKeyVersion = direct.LazyPtr(in.GetKmsKeyVersion())
	// MISSING: State
	// MISSING: IsDefault
	// MISSING: LastRotationTimestampMicros
	out.SingleRegionKeys = direct.Slice_FromProto(mapCtx, in.SingleRegionKeys, SingleRegionKey_FromProto)
	// MISSING: NotebooklmState
	return out
}
func CmekConfig_ToProto(mapCtx *direct.MapContext, in *krm.CmekConfig) *pb.CmekConfig {
	if in == nil {
		return nil
	}
	out := &pb.CmekConfig{}
	out.Name = direct.ValueOf(in.Name)
	out.KmsKey = direct.ValueOf(in.KMSKey)
	out.KmsKeyVersion = direct.ValueOf(in.KMSKeyVersion)
	// MISSING: State
	// MISSING: IsDefault
	// MISSING: LastRotationTimestampMicros
	out.SingleRegionKeys = direct.Slice_ToProto(mapCtx, in.SingleRegionKeys, SingleRegionKey_ToProto)
	// MISSING: NotebooklmState
	return out
}
func Condition_FromProto(mapCtx *direct.MapContext, in *pb.Condition) *krm.Condition {
	if in == nil {
		return nil
	}
	out := &krm.Condition{}
	out.QueryTerms = direct.Slice_FromProto(mapCtx, in.QueryTerms, Condition_QueryTerm_FromProto)
	out.ActiveTimeRange = direct.Slice_FromProto(mapCtx, in.ActiveTimeRange, Condition_TimeRange_FromProto)
	out.QueryRegex = direct.LazyPtr(in.GetQueryRegex())
	return out
}
func Condition_ToProto(mapCtx *direct.MapContext, in *krm.Condition) *pb.Condition {
	if in == nil {
		return nil
	}
	out := &pb.Condition{}
	out.QueryTerms = direct.Slice_ToProto(mapCtx, in.QueryTerms, Condition_QueryTerm_ToProto)
	out.ActiveTimeRange = direct.Slice_ToProto(mapCtx, in.ActiveTimeRange, Condition_TimeRange_ToProto)
	out.QueryRegex = direct.ValueOf(in.QueryRegex)
	return out
}
func Condition_QueryTerm_FromProto(mapCtx *direct.MapContext, in *pb.Condition_QueryTerm) *krm.Condition_QueryTerm {
	if in == nil {
		return nil
	}
	out := &krm.Condition_QueryTerm{}
	out.Value = direct.LazyPtr(in.GetValue())
	out.FullMatch = direct.LazyPtr(in.GetFullMatch())
	return out
}
func Condition_QueryTerm_ToProto(mapCtx *direct.MapContext, in *krm.Condition_QueryTerm) *pb.Condition_QueryTerm {
	if in == nil {
		return nil
	}
	out := &pb.Condition_QueryTerm{}
	out.Value = direct.ValueOf(in.Value)
	out.FullMatch = direct.ValueOf(in.FullMatch)
	return out
}
func Condition_TimeRange_FromProto(mapCtx *direct.MapContext, in *pb.Condition_TimeRange) *krm.Condition_TimeRange {
	if in == nil {
		return nil
	}
	out := &krm.Condition_TimeRange{}
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	return out
}
func Condition_TimeRange_ToProto(mapCtx *direct.MapContext, in *krm.Condition_TimeRange) *pb.Condition_TimeRange {
	if in == nil {
		return nil
	}
	out := &pb.Condition_TimeRange{}
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	return out
}
func Control_BoostAction_FromProto(mapCtx *direct.MapContext, in *pb.Control_BoostAction) *krm.Control_BoostAction {
	if in == nil {
		return nil
	}
	out := &krm.Control_BoostAction{}
	out.FixedBoost = direct.LazyPtr(in.GetFixedBoost())
	out.InterpolationBoostSpec = Control_BoostAction_InterpolationBoostSpec_FromProto(mapCtx, in.GetInterpolationBoostSpec())
	out.Boost = direct.LazyPtr(in.GetBoost())
	out.Filter = direct.LazyPtr(in.GetFilter())
	if in.GetDataStore() != "" {
		out.DataStoreRef = &krm.DiscoveryEngineDataStoreRef{External: in.GetDataStore()}
	}
	return out
}
func Control_BoostAction_ToProto(mapCtx *direct.MapContext, in *krm.Control_BoostAction) *pb.Control_BoostAction {
	if in == nil {
		return nil
	}
	out := &pb.Control_BoostAction{}
	if oneof := Control_BoostAction_FixedBoost_ToProto(mapCtx, in.FixedBoost); oneof != nil {
		out.BoostSpec = oneof
	}
	if oneof := Control_BoostAction_InterpolationBoostSpec_ToProto(mapCtx, in.InterpolationBoostSpec); oneof != nil {
		out.BoostSpec = &pb.Control_BoostAction_InterpolationBoostSpec_{InterpolationBoostSpec: oneof}
	}
	out.Boost = direct.ValueOf(in.Boost)
	out.Filter = direct.ValueOf(in.Filter)
	if in.DataStoreRef != nil {
		out.DataStore = in.DataStoreRef.External
	}
	return out
}
func Control_BoostAction_FixedBoost_ToProto(mapCtx *direct.MapContext, in *float32) *pb.Control_BoostAction_FixedBoost {
	if in == nil {
		return nil
	}
	return &pb.Control_BoostAction_FixedBoost{FixedBoost: *in}
}
func Control_BoostAction_InterpolationBoostSpec_FromProto(mapCtx *direct.MapContext, in *pb.Control_BoostAction_InterpolationBoostSpec) *krm.Control_BoostAction_InterpolationBoostSpec {
	if in == nil {
		return nil
	}
	out := &krm.Control_BoostAction_InterpolationBoostSpec{}
	out.FieldName = direct.LazyPtr(in.GetFieldName())
	out.AttributeType = direct.Enum_FromProto(mapCtx, in.GetAttributeType())
	out.InterpolationType = direct.Enum_FromProto(mapCtx, in.GetInterpolationType())
	out.ControlPoints = direct.Slice_FromProto(mapCtx, in.ControlPoints, Control_BoostAction_InterpolationBoostSpec_ControlPoint_FromProto)
	return out
}
func Control_BoostAction_InterpolationBoostSpec_ToProto(mapCtx *direct.MapContext, in *krm.Control_BoostAction_InterpolationBoostSpec) *pb.Control_BoostAction_InterpolationBoostSpec {
	if in == nil {
		return nil
	}
	out := &pb.Control_BoostAction_InterpolationBoostSpec{}
	out.FieldName = direct.ValueOf(in.FieldName)
	out.AttributeType = direct.Enum_ToProto[pb.Control_BoostAction_InterpolationBoostSpec_AttributeType](mapCtx, in.AttributeType)
	out.InterpolationType = direct.Enum_ToProto[pb.Control_BoostAction_InterpolationBoostSpec_InterpolationType](mapCtx, in.InterpolationType)
	out.ControlPoints = direct.Slice_ToProto(mapCtx, in.ControlPoints, Control_BoostAction_InterpolationBoostSpec_ControlPoint_ToProto)
	return out
}
func Control_BoostAction_InterpolationBoostSpec_ControlPoint_FromProto(mapCtx *direct.MapContext, in *pb.Control_BoostAction_InterpolationBoostSpec_ControlPoint) *krm.Control_BoostAction_InterpolationBoostSpec_ControlPoint {
	if in == nil {
		return nil
	}
	out := &krm.Control_BoostAction_InterpolationBoostSpec_ControlPoint{}
	out.AttributeValue = direct.LazyPtr(in.GetAttributeValue())
	out.BoostAmount = direct.LazyPtr(in.GetBoostAmount())
	return out
}
func Control_BoostAction_InterpolationBoostSpec_ControlPoint_ToProto(mapCtx *direct.MapContext, in *krm.Control_BoostAction_InterpolationBoostSpec_ControlPoint) *pb.Control_BoostAction_InterpolationBoostSpec_ControlPoint {
	if in == nil {
		return nil
	}
	out := &pb.Control_BoostAction_InterpolationBoostSpec_ControlPoint{}
	out.AttributeValue = direct.ValueOf(in.AttributeValue)
	out.BoostAmount = direct.ValueOf(in.BoostAmount)
	return out
}
func Control_FilterAction_FromProto(mapCtx *direct.MapContext, in *pb.Control_FilterAction) *krm.Control_FilterAction {
	if in == nil {
		return nil
	}
	out := &krm.Control_FilterAction{}
	out.Filter = direct.LazyPtr(in.GetFilter())
	if in.GetDataStore() != "" {
		out.DataStoreRef = &krm.DiscoveryEngineDataStoreRef{External: in.GetDataStore()}
	}
	return out
}
func Control_FilterAction_ToProto(mapCtx *direct.MapContext, in *krm.Control_FilterAction) *pb.Control_FilterAction {
	if in == nil {
		return nil
	}
	out := &pb.Control_FilterAction{}
	out.Filter = direct.ValueOf(in.Filter)
	if in.DataStoreRef != nil {
		out.DataStore = in.DataStoreRef.External
	}
	return out
}
func Control_PromoteAction_FromProto(mapCtx *direct.MapContext, in *pb.Control_PromoteAction) *krm.Control_PromoteAction {
	if in == nil {
		return nil
	}
	out := &krm.Control_PromoteAction{}
	if in.GetDataStore() != "" {
		out.DataStoreRef = &krm.DiscoveryEngineDataStoreRef{External: in.GetDataStore()}
	}
	out.SearchLinkPromotion = SearchLinkPromotion_FromProto(mapCtx, in.GetSearchLinkPromotion())
	return out
}
func Control_PromoteAction_ToProto(mapCtx *direct.MapContext, in *krm.Control_PromoteAction) *pb.Control_PromoteAction {
	if in == nil {
		return nil
	}
	out := &pb.Control_PromoteAction{}
	if in.DataStoreRef != nil {
		out.DataStore = in.DataStoreRef.External
	}
	out.SearchLinkPromotion = SearchLinkPromotion_ToProto(mapCtx, in.SearchLinkPromotion)
	return out
}
func Control_RedirectAction_FromProto(mapCtx *direct.MapContext, in *pb.Control_RedirectAction) *krm.Control_RedirectAction {
	if in == nil {
		return nil
	}
	out := &krm.Control_RedirectAction{}
	out.RedirectURI = direct.LazyPtr(in.GetRedirectUri())
	return out
}
func Control_RedirectAction_ToProto(mapCtx *direct.MapContext, in *krm.Control_RedirectAction) *pb.Control_RedirectAction {
	if in == nil {
		return nil
	}
	out := &pb.Control_RedirectAction{}
	out.RedirectUri = direct.ValueOf(in.RedirectURI)
	return out
}
func Control_SynonymsAction_FromProto(mapCtx *direct.MapContext, in *pb.Control_SynonymsAction) *krm.Control_SynonymsAction {
	if in == nil {
		return nil
	}
	out := &krm.Control_SynonymsAction{}
	out.Synonyms = in.Synonyms
	return out
}
func Control_SynonymsAction_ToProto(mapCtx *direct.MapContext, in *krm.Control_SynonymsAction) *pb.Control_SynonymsAction {
	if in == nil {
		return nil
	}
	out := &pb.Control_SynonymsAction{}
	out.Synonyms = in.Synonyms
	return out
}
func ConversationContext_FromProto(mapCtx *direct.MapContext, in *pb.ConversationContext) *krm.ConversationContext {
	if in == nil {
		return nil
	}
	out := &krm.ConversationContext{}
	out.ContextDocuments = in.ContextDocuments
	out.ActiveDocument = direct.LazyPtr(in.GetActiveDocument())
	return out
}
func ConversationContext_ToProto(mapCtx *direct.MapContext, in *krm.ConversationContext) *pb.ConversationContext {
	if in == nil {
		return nil
	}
	out := &pb.ConversationContext{}
	out.ContextDocuments = in.ContextDocuments
	out.ActiveDocument = direct.ValueOf(in.ActiveDocument)
	return out
}
func ConversationMessage_FromProto(mapCtx *direct.MapContext, in *pb.ConversationMessage) *krm.ConversationMessage {
	if in == nil {
		return nil
	}
	out := &krm.ConversationMessage{}
	out.UserInput = TextInput_FromProto(mapCtx, in.GetUserInput())
	out.Reply = Reply_FromProto(mapCtx, in.GetReply())
	// MISSING: CreateTime
	return out
}
func ConversationMessage_ToProto(mapCtx *direct.MapContext, in *krm.ConversationMessage) *pb.ConversationMessage {
	if in == nil {
		return nil
	}
	out := &pb.ConversationMessage{}
	if oneof := TextInput_ToProto(mapCtx, in.UserInput); oneof != nil {
		out.Message = &pb.ConversationMessage_UserInput{UserInput: oneof}
	}
	if oneof := Reply_ToProto(mapCtx, in.Reply); oneof != nil {
		out.Message = &pb.ConversationMessage_Reply{Reply: oneof}
	}
	// MISSING: CreateTime
	return out
}
func DataStore_BillingEstimation_FromProto(mapCtx *direct.MapContext, in *pb.DataStore_BillingEstimation) *krm.DataStore_BillingEstimation {
	if in == nil {
		return nil
	}
	out := &krm.DataStore_BillingEstimation{}
	out.StructuredDataSize = direct.LazyPtr(in.GetStructuredDataSize())
	out.UnstructuredDataSize = direct.LazyPtr(in.GetUnstructuredDataSize())
	out.WebsiteDataSize = direct.LazyPtr(in.GetWebsiteDataSize())
	out.StructuredDataUpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStructuredDataUpdateTime())
	out.UnstructuredDataUpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUnstructuredDataUpdateTime())
	out.WebsiteDataUpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetWebsiteDataUpdateTime())
	return out
}
func DataStore_BillingEstimation_ToProto(mapCtx *direct.MapContext, in *krm.DataStore_BillingEstimation) *pb.DataStore_BillingEstimation {
	if in == nil {
		return nil
	}
	out := &pb.DataStore_BillingEstimation{}
	out.StructuredDataSize = direct.ValueOf(in.StructuredDataSize)
	out.UnstructuredDataSize = direct.ValueOf(in.UnstructuredDataSize)
	out.WebsiteDataSize = direct.ValueOf(in.WebsiteDataSize)
	out.StructuredDataUpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.StructuredDataUpdateTime)
	out.UnstructuredDataUpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UnstructuredDataUpdateTime)
	out.WebsiteDataUpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.WebsiteDataUpdateTime)
	return out
}
func DiscoveryEngineControlObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Control) *krm.DiscoveryEngineControlObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineControlObservedState{}
	// MISSING: Name
	// MISSING: AssociatedServingConfigIds
	return out
}
func DiscoveryEngineControlObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineControlObservedState) *pb.Control {
	if in == nil {
		return nil
	}
	out := &pb.Control{}
	// MISSING: Name
	// MISSING: AssociatedServingConfigIds
	return out
}
func DiscoveryEngineControlSpec_FromProto(mapCtx *direct.MapContext, in *pb.Control) *krm.DiscoveryEngineControlSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineControlSpec{}
	out.BoostAction = Control_BoostAction_FromProto(mapCtx, in.GetBoostAction())
	out.FilterAction = Control_FilterAction_FromProto(mapCtx, in.GetFilterAction())
	out.RedirectAction = Control_RedirectAction_FromProto(mapCtx, in.GetRedirectAction())
	out.SynonymsAction = Control_SynonymsAction_FromProto(mapCtx, in.GetSynonymsAction())
	out.PromoteAction = Control_PromoteAction_FromProto(mapCtx, in.GetPromoteAction())
	// MISSING: Name
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	// MISSING: AssociatedServingConfigIds
	out.SolutionType = direct.Enum_FromProto(mapCtx, in.GetSolutionType())
	out.UseCases = direct.EnumSlice_FromProto(mapCtx, in.UseCases)
	out.Conditions = direct.Slice_FromProto(mapCtx, in.Conditions, Condition_FromProto)
	return out
}
func DiscoveryEngineControlSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineControlSpec) *pb.Control {
	if in == nil {
		return nil
	}
	out := &pb.Control{}
	if oneof := Control_BoostAction_ToProto(mapCtx, in.BoostAction); oneof != nil {
		out.Action = &pb.Control_BoostAction_{BoostAction: oneof}
	}
	if oneof := Control_FilterAction_ToProto(mapCtx, in.FilterAction); oneof != nil {
		out.Action = &pb.Control_FilterAction_{FilterAction: oneof}
	}
	if oneof := Control_RedirectAction_ToProto(mapCtx, in.RedirectAction); oneof != nil {
		out.Action = &pb.Control_RedirectAction_{RedirectAction: oneof}
	}
	if oneof := Control_SynonymsAction_ToProto(mapCtx, in.SynonymsAction); oneof != nil {
		out.Action = &pb.Control_SynonymsAction_{SynonymsAction: oneof}
	}
	if oneof := Control_PromoteAction_ToProto(mapCtx, in.PromoteAction); oneof != nil {
		out.Action = &pb.Control_PromoteAction_{PromoteAction: oneof}
	}
	// MISSING: Name
	out.DisplayName = direct.ValueOf(in.DisplayName)
	// MISSING: AssociatedServingConfigIds
	out.SolutionType = direct.Enum_ToProto[pb.SolutionType](mapCtx, in.SolutionType)
	out.UseCases = direct.EnumSlice_ToProto[pb.SearchUseCase](mapCtx, in.UseCases)
	out.Conditions = direct.Slice_ToProto(mapCtx, in.Conditions, Condition_ToProto)
	return out
}
func DiscoveryEngineConversationObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Conversation) *krm.DiscoveryEngineConversationObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineConversationObservedState{}
	// MISSING: Name
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	return out
}
func DiscoveryEngineConversationObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineConversationObservedState) *pb.Conversation {
	if in == nil {
		return nil
	}
	out := &pb.Conversation{}
	// MISSING: Name
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	return out
}
func DiscoveryEngineConversationSpec_FromProto(mapCtx *direct.MapContext, in *pb.Conversation) *krm.DiscoveryEngineConversationSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineConversationSpec{}
	// MISSING: Name
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.UserPseudoID = direct.LazyPtr(in.GetUserPseudoId())
	out.Messages = direct.Slice_FromProto(mapCtx, in.Messages, ConversationMessage_FromProto)
	return out
}
func DiscoveryEngineConversationSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineConversationSpec) *pb.Conversation {
	if in == nil {
		return nil
	}
	out := &pb.Conversation{}
	// MISSING: Name
	out.State = direct.Enum_ToProto[pb.Conversation_State](mapCtx, in.State)
	out.UserPseudoId = direct.ValueOf(in.UserPseudoID)
	out.Messages = direct.Slice_ToProto(mapCtx, in.Messages, ConversationMessage_ToProto)
	return out
}
func DiscoveryEngineDataStoreObservedState_FromProto(mapCtx *direct.MapContext, in *pb.DataStore) *krm.DiscoveryEngineDataStoreObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineDataStoreObservedState{}
	// MISSING: Name
	out.DefaultSchemaID = direct.LazyPtr(in.GetDefaultSchemaId())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	// MISSING: AdvancedSiteSearchConfig
	// MISSING: KMSKeyName
	// MISSING: CmekConfig
	out.BillingEstimation = DataStore_BillingEstimation_FromProto(mapCtx, in.GetBillingEstimation())
	// MISSING: AclEnabled
	// MISSING: DocumentProcessingConfig
	// MISSING: StartingSchema
	// MISSING: HealthcareFhirConfig
	// MISSING: IdentityMappingStore
	return out
}
func DiscoveryEngineDataStoreObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineDataStoreObservedState) *pb.DataStore {
	if in == nil {
		return nil
	}
	out := &pb.DataStore{}
	// MISSING: Name
	out.DefaultSchemaId = direct.ValueOf(in.DefaultSchemaID)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	// MISSING: AdvancedSiteSearchConfig
	// MISSING: KMSKeyName
	// MISSING: CmekConfig
	out.BillingEstimation = DataStore_BillingEstimation_ToProto(mapCtx, in.BillingEstimation)
	// MISSING: AclEnabled
	// MISSING: DocumentProcessingConfig
	// MISSING: StartingSchema
	// MISSING: HealthcareFhirConfig
	// MISSING: IdentityMappingStore
	return out
}
func DiscoveryEngineDataStoreSpec_FromProto(mapCtx *direct.MapContext, in *pb.DataStore) *krm.DiscoveryEngineDataStoreSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineDataStoreSpec{}
	// MISSING: Name
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.IndustryVertical = direct.Enum_FromProto(mapCtx, in.GetIndustryVertical())
	out.SolutionTypes = direct.EnumSlice_FromProto(mapCtx, in.SolutionTypes)
	out.ContentConfig = direct.Enum_FromProto(mapCtx, in.GetContentConfig())
	// MISSING: AdvancedSiteSearchConfig
	// MISSING: KMSKeyName
	// MISSING: CmekConfig
	// MISSING: AclEnabled
	out.WorkspaceConfig = WorkspaceConfig_FromProto(mapCtx, in.GetWorkspaceConfig())
	// MISSING: DocumentProcessingConfig
	// MISSING: StartingSchema
	// MISSING: HealthcareFhirConfig
	// MISSING: IdentityMappingStore
	return out
}
func DiscoveryEngineDataStoreSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineDataStoreSpec) *pb.DataStore {
	if in == nil {
		return nil
	}
	out := &pb.DataStore{}
	// MISSING: Name
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.IndustryVertical = direct.Enum_ToProto[pb.IndustryVertical](mapCtx, in.IndustryVertical)
	out.SolutionTypes = direct.EnumSlice_ToProto[pb.SolutionType](mapCtx, in.SolutionTypes)
	out.ContentConfig = direct.Enum_ToProto[pb.DataStore_ContentConfig](mapCtx, in.ContentConfig)
	// MISSING: AdvancedSiteSearchConfig
	// MISSING: KMSKeyName
	// MISSING: CmekConfig
	// MISSING: AclEnabled
	out.WorkspaceConfig = WorkspaceConfig_ToProto(mapCtx, in.WorkspaceConfig)
	// MISSING: DocumentProcessingConfig
	// MISSING: StartingSchema
	// MISSING: HealthcareFhirConfig
	// MISSING: IdentityMappingStore
	return out
}
func DiscoveryEngineDataStoreTargetSiteObservedState_FromProto(mapCtx *direct.MapContext, in *pb.TargetSite) *krm.DiscoveryEngineDataStoreTargetSiteObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineDataStoreTargetSiteObservedState{}
	// MISSING: Name
	out.GeneratedURIPattern = direct.LazyPtr(in.GetGeneratedUriPattern())
	out.RootDomainURI = direct.LazyPtr(in.GetRootDomainUri())
	out.SiteVerificationInfo = SiteVerificationInfo_FromProto(mapCtx, in.GetSiteVerificationInfo())
	out.IndexingStatus = direct.Enum_FromProto(mapCtx, in.GetIndexingStatus())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.FailureReason = TargetSite_FailureReason_FromProto(mapCtx, in.GetFailureReason())
	return out
}
func DiscoveryEngineDataStoreTargetSiteObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineDataStoreTargetSiteObservedState) *pb.TargetSite {
	if in == nil {
		return nil
	}
	out := &pb.TargetSite{}
	// MISSING: Name
	out.GeneratedUriPattern = direct.ValueOf(in.GeneratedURIPattern)
	out.RootDomainUri = direct.ValueOf(in.RootDomainURI)
	out.SiteVerificationInfo = SiteVerificationInfo_ToProto(mapCtx, in.SiteVerificationInfo)
	out.IndexingStatus = direct.Enum_ToProto[pb.TargetSite_IndexingStatus](mapCtx, in.IndexingStatus)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.FailureReason = TargetSite_FailureReason_ToProto(mapCtx, in.FailureReason)
	return out
}
func DiscoveryEngineDataStoreTargetSiteSpec_FromProto(mapCtx *direct.MapContext, in *pb.TargetSite) *krm.DiscoveryEngineDataStoreTargetSiteSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineDataStoreTargetSiteSpec{}
	// MISSING: Name
	out.ProvidedURIPattern = direct.LazyPtr(in.GetProvidedUriPattern())
	out.Type = direct.Enum_FromProto(mapCtx, in.GetType())
	out.ExactMatch = direct.LazyPtr(in.GetExactMatch())
	return out
}
func DiscoveryEngineDataStoreTargetSiteSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineDataStoreTargetSiteSpec) *pb.TargetSite {
	if in == nil {
		return nil
	}
	out := &pb.TargetSite{}
	// MISSING: Name
	out.ProvidedUriPattern = direct.ValueOf(in.ProvidedURIPattern)
	out.Type = direct.Enum_ToProto[pb.TargetSite_Type](mapCtx, in.Type)
	out.ExactMatch = direct.ValueOf(in.ExactMatch)
	return out
}
func DiscoveryEngineEngineObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Engine) *krm.DiscoveryEngineEngineObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineEngineObservedState{}
	// MISSING: MediaRecommendationEngineConfig
	// MISSING: ChatEngineMetadata
	// MISSING: Name
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: DataStoreIds
	return out
}
func DiscoveryEngineEngineObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineEngineObservedState) *pb.Engine {
	if in == nil {
		return nil
	}
	out := &pb.Engine{}
	// MISSING: MediaRecommendationEngineConfig
	// MISSING: ChatEngineMetadata
	// MISSING: Name
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: DataStoreIds
	return out
}
func DiscoveryEngineIdentityMappingStoreObservedState_FromProto(mapCtx *direct.MapContext, in *pb.IdentityMappingStore) *krm.DiscoveryEngineIdentityMappingStoreObservedState {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineIdentityMappingStoreObservedState{}
	// MISSING: Name
	out.CmekConfig = CmekConfig_FromProto(mapCtx, in.GetCmekConfig())
	return out
}
func DiscoveryEngineIdentityMappingStoreObservedState_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineIdentityMappingStoreObservedState) *pb.IdentityMappingStore {
	if in == nil {
		return nil
	}
	out := &pb.IdentityMappingStore{}
	// MISSING: Name
	out.CmekConfig = CmekConfig_ToProto(mapCtx, in.CmekConfig)
	return out
}
func DiscoveryEngineIdentityMappingStoreSpec_FromProto(mapCtx *direct.MapContext, in *pb.IdentityMappingStore) *krm.DiscoveryEngineIdentityMappingStoreSpec {
	if in == nil {
		return nil
	}
	out := &krm.DiscoveryEngineIdentityMappingStoreSpec{}
	// MISSING: Name
	out.KMSKeyName = direct.LazyPtr(in.GetKmsKeyName())
	return out
}
func DiscoveryEngineIdentityMappingStoreSpec_ToProto(mapCtx *direct.MapContext, in *krm.DiscoveryEngineIdentityMappingStoreSpec) *pb.IdentityMappingStore {
	if in == nil {
		return nil
	}
	out := &pb.IdentityMappingStore{}
	// MISSING: Name
	out.KmsKeyName = direct.ValueOf(in.KMSKeyName)
	return out
}
func Engine_ChatEngineConfig_FromProto(mapCtx *direct.MapContext, in *pb.Engine_ChatEngineConfig) *krm.Engine_ChatEngineConfig {
	if in == nil {
		return nil
	}
	out := &krm.Engine_ChatEngineConfig{}
	out.AgentCreationConfig = Engine_ChatEngineConfig_AgentCreationConfig_FromProto(mapCtx, in.GetAgentCreationConfig())
	out.DialogflowAgentToLink = direct.LazyPtr(in.GetDialogflowAgentToLink())
	out.AllowCrossRegion = direct.LazyPtr(in.GetAllowCrossRegion())
	return out
}
func Engine_ChatEngineConfig_ToProto(mapCtx *direct.MapContext, in *krm.Engine_ChatEngineConfig) *pb.Engine_ChatEngineConfig {
	if in == nil {
		return nil
	}
	out := &pb.Engine_ChatEngineConfig{}
	out.AgentCreationConfig = Engine_ChatEngineConfig_AgentCreationConfig_ToProto(mapCtx, in.AgentCreationConfig)
	out.DialogflowAgentToLink = direct.ValueOf(in.DialogflowAgentToLink)
	out.AllowCrossRegion = direct.ValueOf(in.AllowCrossRegion)
	return out
}
func Engine_ChatEngineConfig_AgentCreationConfig_FromProto(mapCtx *direct.MapContext, in *pb.Engine_ChatEngineConfig_AgentCreationConfig) *krm.Engine_ChatEngineConfig_AgentCreationConfig {
	if in == nil {
		return nil
	}
	out := &krm.Engine_ChatEngineConfig_AgentCreationConfig{}
	out.Business = direct.LazyPtr(in.GetBusiness())
	out.DefaultLanguageCode = direct.LazyPtr(in.GetDefaultLanguageCode())
	out.TimeZone = direct.LazyPtr(in.GetTimeZone())
	out.Location = direct.LazyPtr(in.GetLocation())
	return out
}
func Engine_ChatEngineConfig_AgentCreationConfig_ToProto(mapCtx *direct.MapContext, in *krm.Engine_ChatEngineConfig_AgentCreationConfig) *pb.Engine_ChatEngineConfig_AgentCreationConfig {
	if in == nil {
		return nil
	}
	out := &pb.Engine_ChatEngineConfig_AgentCreationConfig{}
	out.Business = direct.ValueOf(in.Business)
	out.DefaultLanguageCode = direct.ValueOf(in.DefaultLanguageCode)
	out.TimeZone = direct.ValueOf(in.TimeZone)
	out.Location = direct.ValueOf(in.Location)
	return out
}
func Engine_CommonConfig_FromProto(mapCtx *direct.MapContext, in *pb.Engine_CommonConfig) *krm.Engine_CommonConfig {
	if in == nil {
		return nil
	}
	out := &krm.Engine_CommonConfig{}
	out.CompanyName = direct.LazyPtr(in.GetCompanyName())
	return out
}
func Engine_CommonConfig_ToProto(mapCtx *direct.MapContext, in *krm.Engine_CommonConfig) *pb.Engine_CommonConfig {
	if in == nil {
		return nil
	}
	out := &pb.Engine_CommonConfig{}
	out.CompanyName = direct.ValueOf(in.CompanyName)
	return out
}
func Engine_SearchEngineConfig_FromProto(mapCtx *direct.MapContext, in *pb.Engine_SearchEngineConfig) *krm.Engine_SearchEngineConfig {
	if in == nil {
		return nil
	}
	out := &krm.Engine_SearchEngineConfig{}
	out.SearchTier = direct.Enum_FromProto(mapCtx, in.GetSearchTier())
	out.SearchAddOns = direct.EnumSlice_FromProto(mapCtx, in.SearchAddOns)
	return out
}
func Engine_SearchEngineConfig_ToProto(mapCtx *direct.MapContext, in *krm.Engine_SearchEngineConfig) *pb.Engine_SearchEngineConfig {
	if in == nil {
		return nil
	}
	out := &pb.Engine_SearchEngineConfig{}
	out.SearchTier = direct.Enum_ToProto[pb.SearchTier](mapCtx, in.SearchTier)
	out.SearchAddOns = direct.EnumSlice_ToProto[pb.SearchAddOn](mapCtx, in.SearchAddOns)
	return out
}
func Reply_FromProto(mapCtx *direct.MapContext, in *pb.Reply) *krm.Reply {
	if in == nil {
		return nil
	}
	out := &krm.Reply{}
	out.Summary = SearchResponse_Summary_FromProto(mapCtx, in.GetSummary())
	return out
}
func Reply_ToProto(mapCtx *direct.MapContext, in *krm.Reply) *pb.Reply {
	if in == nil {
		return nil
	}
	out := &pb.Reply{}
	out.Summary = SearchResponse_Summary_ToProto(mapCtx, in.Summary)
	return out
}
func SearchLinkPromotion_FromProto(mapCtx *direct.MapContext, in *pb.SearchLinkPromotion) *krm.SearchLinkPromotion {
	if in == nil {
		return nil
	}
	out := &krm.SearchLinkPromotion{}
	out.Title = direct.LazyPtr(in.GetTitle())
	out.URI = direct.LazyPtr(in.GetUri())
	out.Document = direct.LazyPtr(in.GetDocument())
	out.ImageURI = direct.LazyPtr(in.GetImageUri())
	out.Description = direct.LazyPtr(in.GetDescription())
	out.Enabled = direct.LazyPtr(in.GetEnabled())
	return out
}
func SearchLinkPromotion_ToProto(mapCtx *direct.MapContext, in *krm.SearchLinkPromotion) *pb.SearchLinkPromotion {
	if in == nil {
		return nil
	}
	out := &pb.SearchLinkPromotion{}
	out.Title = direct.ValueOf(in.Title)
	out.Uri = direct.ValueOf(in.URI)
	out.Document = direct.ValueOf(in.Document)
	out.ImageUri = direct.ValueOf(in.ImageURI)
	out.Description = direct.ValueOf(in.Description)
	out.Enabled = direct.ValueOf(in.Enabled)
	return out
}
func SingleRegionKey_FromProto(mapCtx *direct.MapContext, in *pb.SingleRegionKey) *krm.SingleRegionKey {
	if in == nil {
		return nil
	}
	out := &krm.SingleRegionKey{}
	out.KMSKey = direct.LazyPtr(in.GetKmsKey())
	return out
}
func SingleRegionKey_ToProto(mapCtx *direct.MapContext, in *krm.SingleRegionKey) *pb.SingleRegionKey {
	if in == nil {
		return nil
	}
	out := &pb.SingleRegionKey{}
	out.KmsKey = direct.ValueOf(in.KMSKey)
	return out
}
func SiteVerificationInfo_FromProto(mapCtx *direct.MapContext, in *pb.SiteVerificationInfo) *krm.SiteVerificationInfo {
	if in == nil {
		return nil
	}
	out := &krm.SiteVerificationInfo{}
	out.SiteVerificationState = direct.Enum_FromProto(mapCtx, in.GetSiteVerificationState())
	out.VerifyTime = direct.StringTimestamp_FromProto(mapCtx, in.GetVerifyTime())
	return out
}
func SiteVerificationInfo_ToProto(mapCtx *direct.MapContext, in *krm.SiteVerificationInfo) *pb.SiteVerificationInfo {
	if in == nil {
		return nil
	}
	out := &pb.SiteVerificationInfo{}
	out.SiteVerificationState = direct.Enum_ToProto[pb.SiteVerificationInfo_SiteVerificationState](mapCtx, in.SiteVerificationState)
	out.VerifyTime = direct.StringTimestamp_ToProto(mapCtx, in.VerifyTime)
	return out
}
func TargetSite_FailureReason_FromProto(mapCtx *direct.MapContext, in *pb.TargetSite_FailureReason) *krm.TargetSite_FailureReason {
	if in == nil {
		return nil
	}
	out := &krm.TargetSite_FailureReason{}
	out.QuotaFailure = TargetSite_FailureReason_QuotaFailure_FromProto(mapCtx, in.GetQuotaFailure())
	return out
}
func TargetSite_FailureReason_ToProto(mapCtx *direct.MapContext, in *krm.TargetSite_FailureReason) *pb.TargetSite_FailureReason {
	if in == nil {
		return nil
	}
	out := &pb.TargetSite_FailureReason{}
	if oneof := TargetSite_FailureReason_QuotaFailure_ToProto(mapCtx, in.QuotaFailure); oneof != nil {
		out.Failure = &pb.TargetSite_FailureReason_QuotaFailure_{QuotaFailure: oneof}
	}
	return out
}
func TargetSite_FailureReason_QuotaFailure_FromProto(mapCtx *direct.MapContext, in *pb.TargetSite_FailureReason_QuotaFailure) *krm.TargetSite_FailureReason_QuotaFailure {
	if in == nil {
		return nil
	}
	out := &krm.TargetSite_FailureReason_QuotaFailure{}
	out.TotalRequiredQuota = direct.LazyPtr(in.GetTotalRequiredQuota())
	return out
}
func TargetSite_FailureReason_QuotaFailure_ToProto(mapCtx *direct.MapContext, in *krm.TargetSite_FailureReason_QuotaFailure) *pb.TargetSite_FailureReason_QuotaFailure {
	if in == nil {
		return nil
	}
	out := &pb.TargetSite_FailureReason_QuotaFailure{}
	out.TotalRequiredQuota = direct.ValueOf(in.TotalRequiredQuota)
	return out
}
func TextInput_FromProto(mapCtx *direct.MapContext, in *pb.TextInput) *krm.TextInput {
	if in == nil {
		return nil
	}
	out := &krm.TextInput{}
	out.Input = direct.LazyPtr(in.GetInput())
	out.Context = ConversationContext_FromProto(mapCtx, in.GetContext())
	return out
}
func TextInput_ToProto(mapCtx *direct.MapContext, in *krm.TextInput) *pb.TextInput {
	if in == nil {
		return nil
	}
	out := &pb.TextInput{}
	out.Input = direct.ValueOf(in.Input)
	out.Context = ConversationContext_ToProto(mapCtx, in.Context)
	return out
}
func WorkspaceConfig_FromProto(mapCtx *direct.MapContext, in *pb.WorkspaceConfig) *krm.WorkspaceConfig {
	if in == nil {
		return nil
	}
	out := &krm.WorkspaceConfig{}
	out.Type = direct.Enum_FromProto(mapCtx, in.GetType())
	out.DasherCustomerID = direct.LazyPtr(in.GetDasherCustomerId())
	out.SuperAdminServiceAccount = direct.LazyPtr(in.GetSuperAdminServiceAccount())
	out.SuperAdminEmailAddress = direct.LazyPtr(in.GetSuperAdminEmailAddress())
	return out
}
func WorkspaceConfig_ToProto(mapCtx *direct.MapContext, in *krm.WorkspaceConfig) *pb.WorkspaceConfig {
	if in == nil {
		return nil
	}
	out := &pb.WorkspaceConfig{}
	out.Type = direct.Enum_ToProto[pb.WorkspaceConfig_Type](mapCtx, in.Type)
	out.DasherCustomerId = direct.ValueOf(in.DasherCustomerID)
	out.SuperAdminServiceAccount = direct.ValueOf(in.SuperAdminServiceAccount)
	out.SuperAdminEmailAddress = direct.ValueOf(in.SuperAdminEmailAddress)
	return out
}
